//HintName: UserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<User> CreateUserAsync(string name, string email)
    {
        var request = new
        {
            Name = name,
            Email = email,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/CreateUserAsync",
            request);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
