//HintName: IDataServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class DataServiceClient : IDataService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/data";

    public DataServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<int>>> GetMappingAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetMappingAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<int>>>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
