//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MyApp.Services;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services)
    {
        services.AddHttpClient<ITestService, TestServiceClient>();

        return services;
    }
}
