//HintName: ISyncServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class SyncServiceClient : ISyncService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/sync";

    public SyncServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public Result Process()
    {
        var response = _httpClient.PostAsync(
            $"{BaseRoute}/Process",
            null).GetAwaiter().GetResult();

        response.EnsureSuccessStatusCode();

        return response.Content.ReadFromJsonAsync<Result>().GetAwaiter().GetResult()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
