//HintName: ITestServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class TestServiceClient : ITestService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/test";

    public TestServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> TestMethodAsync(string value = "hello", bool isActive = true, string? nullable = null, int count = 10, double percentage = 0.5)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Value"] = value.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["IsActive"] = isActive.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["Nullable"] = nullable?.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["Count"] = count.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["Percentage"] = percentage.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/TestMethodAsync?{queryString}");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<string>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
