//HintName: IUserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<User> UpdateUserAsync(int id, string name)
    {
        var request = new
        {
            Id = id,
            Name = name,
        };

        var requestMessage = new HttpRequestMessage
        {
            Method = HttpMethod.Put,
            RequestUri = new Uri($"{BaseRoute}/UpdateUserAsync", UriKind.Relative),
            Content = JsonContent.Create(request)
        };
        var response = await _httpClient.SendAsync(requestMessage);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
