//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using System;
using Microsoft.Extensions.DependencyInjection;
using BlazorServerFunctions.Sample.Shared;

namespace Tests;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services,
        Uri? baseAddress = null)
    {
        services.AddHttpClient<IWeatherService, WeatherServiceClient>()
            .ConfigureHttpClient(c => { if (baseAddress != null) c.BaseAddress = baseAddress; });

        return services;
    }
}
