//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using MyApp.Services.Products;
using MyApp.Services.Users;

namespace Tests;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services)
    {
        services.AddHttpClient<IUserService, UserServiceClient>();
        services.AddHttpClient<IProductService, ProductServiceClient>();

        return services;
    }
}
