//HintName: PingServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class PingServiceClient : IPingService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/ping";

    public PingServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task PingAsync(string correlationId)
    {
        var requestMessage = new HttpRequestMessage
        {
            Method = HttpMethod.Post,
            RequestUri = new Uri($"{BaseRoute}/PingAsync", UriKind.Relative)
        };
        requestMessage.Headers.Add("X-Correlation-Id", correlationId.ToString());
        var response = await _httpClient.SendAsync(requestMessage);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

    }

}
