//HintName: DataServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class DataServiceClient : IDataService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/data";

    public DataServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<int>>> GetMappingAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetMappingAsync");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<int>>?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
