//HintName: UserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<User> PatchUserAsync(int id, string name)
    {
        var request = new
        {
            Id = id,
            Name = name,
        };

        var requestMessage = new HttpRequestMessage
        {
            Method = HttpMethod.Patch,
            RequestUri = new Uri($"{BaseRoute}/PatchUserAsync", UriKind.Relative),
            Content = JsonContent.Create(request)
        };
        var response = await _httpClient.SendAsync(requestMessage);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
