//HintName: SearchServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class SearchServiceClient : ISearchService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/search";

    public SearchServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<System.Collections.Generic.List<Result>> SearchAsync(string searchTerm, int pageNumber, int pageSize)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["SearchTerm"] = searchTerm.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["PageNumber"] = pageNumber.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["PageSize"] = pageSize.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/SearchAsync?{queryString}");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<System.Collections.Generic.List<Result>>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

    public async Task<User> CreateUserAsync(string firstName, string lastName, string emailAddress)
    {
        var request = new
        {
            FirstName = firstName,
            LastName = lastName,
            EmailAddress = emailAddress,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/CreateUserAsync",
            request);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
