//HintName: IProductServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class ProductServiceClient : IProductService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/products";

    public ProductServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<Product[]> GetAllProductsAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetAllProductsAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<Product[]>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
