//HintName: CounterServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class CounterServiceClient : ICounterService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/counter";

    public CounterServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<int> GetCountAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetCountAsync");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<int?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
