//HintName: EventServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading;
using System.Threading.Tasks;

namespace MyApp.Services;

public class EventServiceClient : IEventService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/events";

    public EventServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async IAsyncEnumerable<string> StreamEventsAsync([EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/StreamEventsAsync",
            HttpCompletionOption.ResponseHeadersRead,
            cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        await foreach (var item in response.Content.ReadFromJsonAsAsyncEnumerable<string>(cancellationToken)!)
            yield return item!;
    }

}
