//HintName: IUserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task DeleteUserAsync(int id)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Id"] = id.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.DeleteAsync(
            $"{BaseRoute}/DeleteUserAsync?{queryString}");

        response.EnsureSuccessStatusCode();

    }

}
