//HintName: CacheServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class CacheServiceClient : ICacheService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/cache";

    public CacheServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task ClearAllAsync()
    {
        var response = await _httpClient.DeleteAsync(
            $"{BaseRoute}/ClearAllAsync");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

    }

}
