//HintName: UserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<User> GetUserAsync(int id, CancellationToken cancellationToken = default)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Id"] = id.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetUserAsync?{queryString}",
            cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

    public async Task<User> CreateUserAsync(string name, CancellationToken cancellationToken = default)
    {
        var request = new
        {
            Name = name,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/CreateUserAsync",
            request,
            cancellationToken);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync(cancellationToken);
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<User>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
