//HintName: NotificationServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class NotificationServiceClient : INotificationService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/notifications";

    public NotificationServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task SendNotificationAsync(string message)
    {
        var request = new
        {
            Message = message,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/SendNotificationAsync",
            request);

        response.EnsureSuccessStatusCode();

    }

}
