//HintName: ICounterServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class CounterServiceClient : ICounterService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/counter";

    public CounterServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<int?> GetCountAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetCountAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<int?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
