//HintName: ICacheServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class CacheServiceClient : ICacheService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/cache";

    public CacheServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public void ClearAllAsync()
    {
        var response = _httpClient.DeleteAsync(
            $"{BaseRoute}/ClearAllAsync").GetAwaiter().GetResult();

        response.EnsureSuccessStatusCode();

    }

}
