//HintName: ValueTaskServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class ValueTaskServiceClient : IValueTaskService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/valuetasks";

    public ValueTaskServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async ValueTask<Result> ProcessAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/ProcessAsync",
            null);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<Result>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
