//HintName: OrderServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class OrderServiceClient : IOrderService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/orders";

    public OrderServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> CreateOrderAsync(string tenantId, string productId, int quantity)
    {
        var request = new
        {
            ProductId = productId,
            Quantity = quantity,
        };

        var requestMessage = new HttpRequestMessage
        {
            Method = HttpMethod.Post,
            RequestUri = new Uri($"{BaseRoute}/CreateOrderAsync", UriKind.Relative),
            Content = JsonContent.Create(request)
        };
        requestMessage.Headers.Add("X-Tenant-Id", tenantId.ToString());
        var response = await _httpClient.SendAsync(requestMessage);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<string?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
