//HintName: UserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<User?> FindUserAsync(int id)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Id"] = id.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/FindUserAsync?{queryString}");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<User?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
