//HintName: FileServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class FileServiceClient : IFileService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/fileservice";

    public FileServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<long> UploadAsync(System.IO.Stream file)
    {
        var form = new MultipartFormDataContent();
        form.Add(new StreamContent(file), "file", "file");

        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/UploadAsync",
            form);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<long?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
