//HintName: IMessageServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class MessageServiceClient : IMessageService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/messages";

    public MessageServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> GetMessageAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetMessageAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<string>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
