//HintName: SearchServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class SearchServiceClient : ISearchService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/search";

    public SearchServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<System.Collections.Generic.List<Result>> SearchAsync(string query, int pageSize)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Query"] = query.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["PageSize"] = pageSize.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/SearchAsync?{queryString}");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<System.Collections.Generic.List<Result>?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
