//HintName: ServiceWithoutPrefixClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class ServiceWithoutPrefixClient : IServiceWithoutPrefix
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/servicewithoutprefix";

    public ServiceWithoutPrefixClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> GetAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<string>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
