//HintName: IDataServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class DataServiceClient : IDataService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/data";

    public DataServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<Result> ProcessAsync(System.Guid id, System.DateTime timestamp, System.Collections.Generic.List<int> numbers, System.Collections.Generic.Dictionary<string, string> metadata)
    {
        var request = new
        {
            Id = id,
            Timestamp = timestamp,
            Numbers = numbers,
            Metadata = metadata,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/ProcessAsync",
            request);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<Result>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
