//HintName: ActionServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class ActionServiceClient : IActionService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/actions";

    public ActionServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task TriggerActionAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/TriggerActionAsync",
            null);

        response.EnsureSuccessStatusCode();

    }

}
