//HintName: UserServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class UserServiceClient : IUserService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/users";

    public UserServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<System.Collections.Generic.List<User>> GetAllUsersAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetAllUsersAsync");

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<System.Collections.Generic.List<User>>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
