//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using MyApp.Services;

namespace Tests;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services)
    {
        services.AddHttpClient<INestedService, NestedServiceClient>();

        return services;
    }
}
