using System.Text;
using BlazorServerFunctions.Abstractions;

namespace BlazorServerFunctions.Generator;

internal static class ClientRegistrationGenerator
{
    public static string Generate(List<InterfaceInfo> interfaces)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        
        // Use the namespace of the first interface, or default
        var ns = interfaces.FirstOrDefault()?.Namespace ?? "Generated";
        sb.AppendLine($"namespace {ns}.Generated;");
        sb.AppendLine();
        sb.AppendLine("public static class ServerFunctionClientsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddServerFunctionClients(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var name in interfaces.Select(interfaceInfo => interfaceInfo.Name))
        {
            var clientClassName = name.TrimStart('I') + "Client";
            
            sb.AppendLine($"        services.AddHttpClient<{name}, {clientClassName}>();");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}