using System.Text;
using BlazorServerFunctions.Abstractions;

namespace BlazorServerFunctions.Generator.CodeGenerators;

internal static class ClientProxyGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine($"namespace {interfaceInfo.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public class {interfaceInfo.Name.TrimStart('I')}Client : {interfaceInfo.Name}");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine($"    private const string BaseRoute = \"/api/functions/{interfaceInfo.RoutePrefix}\";");
        sb.AppendLine();
        sb.AppendLine($"    public {interfaceInfo.Name.TrimStart('I')}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate method implementations
        foreach (var method in interfaceInfo.Methods)
        {
            GenerateClientMethod(sb, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateClientMethod(StringBuilder sb, MethodInfo method)
    {
        var routeName = method.CustomRoute ?? method.Name;
        var hasParameters = method.Parameters.Count > 0;
        var httpMethodLower = method.HttpMethod.ToLowerInvariant();
        
        // Method signature
        sb.Append($"    public async Task");
        if (method.ReturnType != "void")
        {
            sb.Append($"<{method.ReturnType}>");
        }
        sb.Append($" {method.Name}(");
        
        // Parameters
        var paramDeclarations = method.Parameters.Select(p =>
        {
            var declaration = $"{p.Type} {p.Name}";
            if (p.HasDefaultValue)
            {
                var defaultValue = FormatDefaultValue(p);
                declaration += $" = {defaultValue}";
            }
            return declaration;
        });
        
        sb.Append(string.Join(", ", paramDeclarations));
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // Build request object if there are parameters
        if (hasParameters)
        {
            sb.AppendLine("        var request = new");
            sb.AppendLine("        {");
            
            foreach (var parameterName in method.Parameters.Select(parameter => parameter.Name))
            {
                var propertyName = char.ToUpper(parameterName[0]) + parameterName.Substring(1);
                sb.AppendLine($"            {propertyName} = {parameterName},");
            }
            
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        // Make HTTP call based on method type
        if (httpMethodLower == "post")
        {
            if (hasParameters)
            {
                sb.AppendLine($"        var response = await _httpClient.PostAsJsonAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\",");
                sb.AppendLine("            request);");
            }
            else
            {
                sb.AppendLine($"        var response = await _httpClient.PostAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\",");
                sb.AppendLine("            null);");
            }
        }
        else if (httpMethodLower == "get")
        {
            if (hasParameters)
            {
                sb.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");
                foreach (var paramName in method.Parameters.Select(param => param.Name))
                {
                    var propertyName = char.ToUpper(paramName[0]) + paramName.Substring(1);
                    sb.AppendLine($"        queryString[\"{propertyName}\"] = {paramName}?.ToString();");
                }
                sb.AppendLine($"        var response = await _httpClient.GetAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}?{{queryString}}\");");
            }
            else
            {
                sb.AppendLine($"        var response = await _httpClient.GetAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\");");
            }
        }
        else // PUT, DELETE, PATCH
        {
            var httpMethodUpper = httpMethodLower.ToUpperInvariant();
            sb.AppendLine("        var request = new HttpRequestMessage");
            sb.AppendLine("        {");
            sb.AppendLine($"            Method = HttpMethod.{httpMethodUpper},");
            sb.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{routeName}\", UriKind.Relative)");
            
            if (hasParameters)
            {
                sb.AppendLine("            Content = JsonContent.Create(request)");
            }
            
            sb.AppendLine("        };");
            sb.AppendLine("        var response = await _httpClient.SendAsync(request);");
        }

        sb.AppendLine();
        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine();

        // Handle response
        if (method.ReturnType != "void")
        {
            sb.AppendLine($"        return await response.Content.ReadFromJsonAsync<{method.ReturnType}>()");
            sb.AppendLine($"            ?? throw new InvalidOperationException(\"Response deserialization returned null\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static string FormatDefaultValue(ParameterInfo param)
    {
        if (param.DefaultValue == null)
        {
            return "null";
        }

        // Handle common default value types
        if (param.Type == "string")
        {
            return $"\"{param.DefaultValue}\"";
        }
        
        if (param.Type == "bool")
        {
            return param.DefaultValue.ToLowerInvariant();
        }

        if (param.Type.Contains('?') && param.DefaultValue == "null")
        {
            return "null";
        }

        // For numeric types, return as-is
        return param.DefaultValue;
    }
}