using System.Text;

namespace BlazorServerFunctions.Generator;

internal static class ServerRegistrationGenerator
{
    public static string Generate(System.Collections.IEnumerable interfaces)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        
        // Use the namespace of the first interface, or default
        string ns = "Generated";
        var interfaceList = new List<object>();
        foreach (var i in interfaces)
        {
            interfaceList.Add(i);
        }

        if (interfaceList.Count > 0)
        {
            var first = interfaceList[0];
            ns = (string)first.GetType().GetProperty("Namespace").GetValue(first);
        }

        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine("public static class ServerFunctionEndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapServerFunctionEndpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var i in interfaceList)
        {
            var name = (string)i.GetType().GetProperty("Name").GetValue(i);
            sb.AppendLine($"        endpoints.Map{name}Endpoints();");
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}