using System.Text;
using BlazorServerFunctions.Abstractions;

namespace BlazorServerFunctions.Generator;

internal static class ServerEndpointGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {interfaceInfo.Namespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal static class {interfaceInfo.Name}ServerExtensions");
        sb.AppendLine("{");
        
        // Generate MapEndpoints method
        sb.AppendLine($"    internal static IEndpointRouteBuilder Map{interfaceInfo.Name}Endpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var group = endpoints.MapGroup(\"/api/functions/{interfaceInfo.RoutePrefix}\");");
        sb.AppendLine();

        // Generate endpoint for each method
        foreach (var method in interfaceInfo.Methods)
        {
            GenerateEndpoint(sb, interfaceInfo, method);
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");

        // Generate request DTOs
        foreach (var method in interfaceInfo.Methods)
        {
            if (method.Parameters.Count > 0)
            {
                GenerateRequestDto(sb, method);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateEndpoint(StringBuilder sb, InterfaceInfo interfaceInfo, MethodInfo method)
    {
        var routeName = method.CustomRoute ?? method.Name;
        var hasParameters = method.Parameters.Count > 0;
        var httpMethodLower = method.HttpMethod.ToLowerInvariant();

        sb.AppendLine($"        group.Map{char.ToUpper(httpMethodLower[0]) + httpMethodLower.Substring(1)}(\"/{routeName}\",");
        
        if (hasParameters)
        {
            sb.AppendLine($"            async ([FromBody] {method.Name}Request request, {interfaceInfo.Name} service) =>");
        }
        else
        {
            sb.AppendLine($"            async ({interfaceInfo.Name} service) =>");
        }
        
        sb.AppendLine("            {");

        // Call the service
        sb.Append("                ");
        if (method.ReturnType != "void")
        {
            sb.Append("var result = ");
        }
        
        sb.Append($"await service.{method.Name}(");
        
        if (hasParameters)
        {
            var paramCalls = method.Parameters.Select(p => $"request.{char.ToUpper(p.Name[0])}{p.Name.Substring(1)}");
            sb.Append(string.Join(", ", paramCalls));
        }
        
        sb.AppendLine(");");

        // Return result
        if (method.ReturnType != "void")
        {
            sb.AppendLine("                return Results.Ok(result);");
        }
        else
        {
            sb.AppendLine("                return Results.Ok();");
        }

        sb.AppendLine("            })");
        sb.AppendLine($"            .WithName(\"{interfaceInfo.Name}_{method.Name}\");");
        sb.AppendLine();
    }

    private static void GenerateRequestDto(StringBuilder sb, MethodInfo method)
    {
        sb.AppendLine();
        sb.Append($"    private record {method.Name}Request(");
        
        var properties = method.Parameters.Select(p => 
            $"{p.Type} {char.ToUpper(p.Name[0])}{p.Name.Substring(1)}");
        
        sb.Append(string.Join(", ", properties));
        sb.AppendLine(");");
    }
}