using System.Text;
using BlazorServerFunctions.Abstractions;

namespace BlazorServerFunctions.Generator;

internal static class ServerRegistrationGenerator
{
    public static string Generate(List<InterfaceInfo> interfaces)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        
        // Use the namespace of the first interface, or default
        var ns = interfaces.FirstOrDefault()?.Namespace ?? "Generated";
        sb.AppendLine($"namespace {ns}.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class ServerFunctionEndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    internal static IEndpointRouteBuilder MapServerFunctionEndpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var interfaceInfo in interfaces)
        {
            sb.AppendLine($"        endpoints.Map{interfaceInfo.Name}Endpoints();");
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}