using System.Text;

namespace BlazorServerFunctions.Generator;

internal static class ServerEndpointGenerator
{
    public static string Generate(object interfaceInfoObj)
    {
        var interfaceInfo = interfaceInfoObj;
        var type = interfaceInfo.GetType();
        var name = (string)type.GetProperty("Name").GetValue(interfaceInfo);
        var ns = (string)type.GetProperty("Namespace").GetValue(interfaceInfo);
        var routePrefix = (string)type.GetProperty("RoutePrefix").GetValue(interfaceInfo);
        var methods = (System.Collections.IEnumerable)type.GetProperty("Methods").GetValue(interfaceInfo);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"internal static class {name}ServerExtensions");
        sb.AppendLine("{");
        
        // Generate MapEndpoints method
        sb.AppendLine($"    internal static IEndpointRouteBuilder Map{name}Endpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var group = endpoints.MapGroup(\"/api/functions/{routePrefix}\");");
        sb.AppendLine();

        // Generate endpoint for each method
        foreach (var method in methods)
        {
            GenerateEndpoint(sb, name, method);
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");

        // Generate request DTOs
        foreach (var method in methods)
        {
            var parameters = (System.Collections.ICollection)method.GetType().GetProperty("Parameters").GetValue(method);
            if (parameters.Count > 0)
            {
                GenerateRequestDto(sb, method);
            }
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateEndpoint(StringBuilder sb, string interfaceName, object method)
    {
        var methodType = method.GetType();
        var methodName = (string)methodType.GetProperty("Name").GetValue(method);
        var customRoute = (string)methodType.GetProperty("CustomRoute").GetValue(method);
        var httpMethodLower = ((string)methodType.GetProperty("HttpMethod").GetValue(method)).ToLowerInvariant();
        var returnType = (string)methodType.GetProperty("ReturnType").GetValue(method);
        var parameters = (System.Collections.ICollection)methodType.GetProperty("Parameters").GetValue(method);
        
        var routeName = customRoute ?? methodName;
        var hasParameters = parameters.Count > 0;

        sb.AppendLine($"        group.Map{char.ToUpper(httpMethodLower[0]) + httpMethodLower.Substring(1)}(\"/{routeName}\",");
        
        if (hasParameters)
        {
            sb.AppendLine($"            async ([FromBody] {methodName}Request request, {interfaceName} service) =>");
        }
        else
        {
            sb.AppendLine($"            async ({interfaceName} service) =>");
        }
        
        sb.AppendLine("            {");

        // Call the service
        sb.Append("                ");
        if (returnType != "void")
        {
            sb.Append("var result = ");
        }
        
        sb.Append($"await service.{methodName}(");
        
        if (hasParameters)
        {
            var paramList = new List<string>();
            foreach (var p in (System.Collections.IEnumerable)parameters)
            {
                var pName = (string)p.GetType().GetProperty("Name").GetValue(p);
                paramList.Add($"request.{char.ToUpper(pName[0])}{pName.Substring(1)}");
            }
            sb.Append(string.Join(", ", paramList));
        }
        
        sb.AppendLine(");");

        // Return result
        if (returnType != "void")
        {
            sb.AppendLine("                return Results.Ok(result);");
        }
        else
        {
            sb.AppendLine("                return Results.Ok();");
        }

        sb.AppendLine("            })");
        sb.AppendLine($"            .WithName(\"{interfaceName}_{methodName}\");");
        sb.AppendLine();
    }

    private static void GenerateRequestDto(StringBuilder sb, object method)
    {
        var methodType = method.GetType();
        var methodName = (string)methodType.GetProperty("Name").GetValue(method);
        var parameters = (System.Collections.IEnumerable)methodType.GetProperty("Parameters").GetValue(method);

        sb.AppendLine();
        sb.Append($"    private record {methodName}Request(");
        
        var properties = new List<string>();
        foreach (var p in parameters)
        {
            var pType = (string)p.GetType().GetProperty("Type").GetValue(p);
            var pName = (string)p.GetType().GetProperty("Name").GetValue(p);
            properties.Add($"{pType} {char.ToUpper(pName[0])}{pName.Substring(1)}");
        }
        
        sb.Append(string.Join(", ", properties));
        sb.AppendLine(");");
    }
}