using System.Collections.ObjectModel;
using BlazorServerFunctions.Generator.Generators;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Shouldly;

namespace BlazorServerFunctions.Generator.IntegrationTests;

public sealed class IntegrationTestHost
{
    //private readonly CSharpCompilation _compilation;
    private readonly GeneratorDriverRunResult _runResult;
    private readonly Compilation _updatedCompilation;

    private IntegrationTestHost(
        //CSharpCompilation compilation,
        GeneratorDriverRunResult runResult,
        Compilation updatedCompilation)
    {
        //_compilation = compilation;
        _runResult = runResult;
        _updatedCompilation = updatedCompilation;
    }

    public static IntegrationTestHost Create(
        ReadOnlyCollection<string> projects,
        ReadOnlyCollection<string> sourceFiles)
    {
        var syntaxTrees = projects
            .SelectMany(TestHelpers.GetProjectFiles)
            .Where(file => sourceFiles.Any(file.EndsWith))
            .Select(f => CSharpSyntaxTree.ParseText(File.ReadAllText(f), path: f))
            .ToArray();

        var references = IntegrationTestReferences.GetAll();

        var compilation = CSharpCompilation.Create(
            "IntegrationTestAssembly",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var generator = new ServerFunctionCollectionGenerator();
        GeneratorDriver driver = CSharpGeneratorDriver.Create(generator);

        driver = driver.RunGeneratorsAndUpdateCompilation(
            compilation,
            out var updatedCompilation,
            out _);

        var runResult = driver.GetRunResult();

        return new IntegrationTestHost(
            //compilation,
            runResult,
            updatedCompilation);
    }

    public void AssertNoGeneratorErrors()
    {
        var errors = _runResult.Diagnostics
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        errors.ShouldBeEmpty("the generator should not produce errors");
    }

    public void AssertFilesAreGenerated(params string[] expectedFiles)
        => AssertFilesAreGenerated((IEnumerable<string>)expectedFiles);

    public void AssertFilesAreGenerated(IEnumerable<string> expectedFiles)
    {
        var generated = _runResult.GeneratedTrees
            .Select(t => Path.GetFileName(t.FilePath))
            .ToList();

        generated.ShouldBe(expectedFiles, "these files should be generated by the source generator");
    }

    public void AssertCompilationSucceeds()
    {
        using var ms = new MemoryStream();
        var emit = _updatedCompilation.Emit(ms);

        emit.Diagnostics
            .Where(d => d.Severity is DiagnosticSeverity.Error or DiagnosticSeverity.Warning)
            .ShouldBeEmpty("there should be no compilation errors");
        
        emit.Success.ShouldBeTrue("the generated code must compile");
    }

    public void AssertTypesExist(params string[] types)
        => AssertTypesExist((IEnumerable<string>)types);

    public void AssertTypesExist(IEnumerable<string> types)
    {
        var missing = types
            .Where(t => _updatedCompilation.GetTypeByMetadataName(t) == null)
            .ToList();

        missing.ShouldBeEmpty("all expected generated types must exist");
    }

    public void AssertTypesExistInCompilation(
        IEnumerable<string> fileNames,
        IEnumerable<string> types)
    {
        AssertNoGeneratorErrors();
        AssertFilesAreGenerated(fileNames);
        AssertTypesExist(types);
        AssertCompilationSucceeds();
    }
}
