//HintName: GrpcServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class GrpcServiceCallAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract(Name = "GrpcServiceGrpcService")]
public interface IGrpcServiceGrpcContract
{
    [OperationContract]
    Task<string> CallAsync(GrpcServiceCallAsyncGrpcRequest request, CallContext context = default);
}

public class GrpcServiceGrpcClient : IGrpcService
{
    private readonly IGrpcServiceGrpcContract _grpcService;

    public GrpcServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IGrpcServiceGrpcContract>();
    }

    public Task<string> CallAsync(int id) => _grpcService.CallAsync(new GrpcServiceCallAsyncGrpcRequest { Id = id });

}
