//HintName: SecretServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ServiceContract(Name = "SecretServiceGrpcService")]
public interface ISecretServiceGrpcContract
{
    [OperationContract]
    Task<string> GetSecretAsync(CallContext context = default);
}

public class SecretServiceGrpcClient : ISecretService
{
    private readonly ISecretServiceGrpcContract _grpcService;

    public SecretServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<ISecretServiceGrpcContract>();
    }

    public Task<string> GetSecretAsync() => _grpcService.GetSecretAsync();

}
