//HintName: StreamServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.Collections.Generic;
using System.ServiceModel;
using System.Threading;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class StreamServiceStreamNamesAsyncGrpcRequest
{
    [ProtoMember(1)]
    public string Prefix { get; set; } = default!;
}

[ServiceContract(Name = "StreamServiceGrpcService")]
public interface IStreamServiceGrpcContract
{
    [OperationContract]
    IAsyncEnumerable<string> StreamNamesAsync(StreamServiceStreamNamesAsyncGrpcRequest request, CallContext context = default);
}

public class StreamServiceGrpcClient : IStreamService
{
    private readonly IStreamServiceGrpcContract _grpcService;

    public StreamServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IStreamServiceGrpcContract>();
    }

    public IAsyncEnumerable<string> StreamNamesAsync(string prefix) => _grpcService.StreamNamesAsync(new StreamServiceStreamNamesAsyncGrpcRequest { Prefix = prefix });

}
