//HintName: OrderServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class OrderServiceCreateOrderAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Quantity { get; set; }
}

[ServiceContract(Name = "OrderServiceGrpcService")]
public interface IOrderServiceGrpcContract
{
    [OperationContract]
    Task<string> CreateOrderAsync(OrderServiceCreateOrderAsyncGrpcRequest request, CallContext context = default);
}

public class OrderServiceGrpcClient : IOrderService
{
    private readonly IOrderServiceGrpcContract _grpcService;

    public OrderServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IOrderServiceGrpcContract>();
    }

    public Task<string> CreateOrderAsync(int quantity, CancellationToken cancellationToken = default) => _grpcService.CreateOrderAsync(new OrderServiceCreateOrderAsyncGrpcRequest { Quantity = quantity }, new CallContext(cancellationToken: cancellationToken));

}
