//HintName: PingServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ServiceContract(Name = "PingServiceGrpcService")]
public interface IPingServiceGrpcContract
{
    [OperationContract]
    Task PingAsync(CallContext context = default);
}

public class PingServiceGrpcClient : IPingService
{
    private readonly IPingServiceGrpcContract _grpcService;

    public PingServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IPingServiceGrpcContract>();
    }

    public Task PingAsync() => _grpcService.PingAsync();

}
