//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using System;
using Grpc.Net.Client;
using Grpc.Net.Client.Web;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using MyApp.Services;

namespace Tests;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services,
        Uri? baseAddress = null,
        Action<IHttpClientBuilder>? configureClient = null,
        HttpMessageHandler? innerGrpcHttpHandler = null)
    {
        Register(services.AddHttpClient<IRestService, RestServiceClient>()
            .ConfigureHttpClient(c => { if (baseAddress != null) c.BaseAddress = baseAddress; }));

        // gRPC channel — TryAddSingleton allows tests/advanced users to pre-register their own
        services.TryAddSingleton(sp => GrpcChannel.ForAddress(
            baseAddress ?? throw new InvalidOperationException(
                "Provide baseAddress to AddServerFunctionClients() when gRPC services are registered."),
            new GrpcChannelOptions { HttpHandler = new GrpcWebHandler(innerGrpcHttpHandler ?? new HttpClientHandler()) }));

        // gRPC client registrations
        services.AddTransient<IGrpcService, GrpcServiceGrpcClient>();

        return services;

        void Register(IHttpClientBuilder builder) => configureClient?.Invoke(builder);
    }
}
