//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using System;
using Grpc.Net.Client;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using MyApp.Services;

namespace Tests;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services,
        Uri? baseAddress = null,
        Action<IHttpClientBuilder>? configureClient = null)
    {

        // gRPC channel — TryAddSingleton allows tests/advanced users to pre-register their own
        services.TryAddSingleton(sp => GrpcChannel.ForAddress(
            baseAddress ?? throw new InvalidOperationException(
                "Provide baseAddress to AddServerFunctionClients() when gRPC services are registered.")));

        // gRPC client registrations
        services.AddTransient<IStreamService, StreamServiceGrpcClient>();

        return services;

        void Register(IHttpClientBuilder builder) => configureClient?.Invoke(builder);
    }
}
