//HintName: ProductServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class ProductServiceGetProductAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract(Name = "ProductServiceGrpcService")]
public interface IProductServiceGrpcContract
{
    [OperationContract]
    Task<string> GetProductAsync(ProductServiceGetProductAsyncGrpcRequest request, CallContext context = default);
}

public class ProductServiceGrpcClient : IProductService
{
    private readonly IProductServiceGrpcContract _grpcService;

    public ProductServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IProductServiceGrpcContract>();
    }

    public Task<string> GetProductAsync(int id) => _grpcService.GetProductAsync(new ProductServiceGetProductAsyncGrpcRequest { Id = id });

}
