//HintName: UserServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class UserServiceCreateUserAsyncGrpcRequest
{
    [ProtoMember(1)]
    public MyApp.Services.CreateUserRequest Request { get; set; } = default!;
}

[ServiceContract(Name = "UserServiceGrpcService")]
public interface IUserServiceGrpcContract
{
    [OperationContract]
    Task<MyApp.Services.UserDto> CreateUserAsync(UserServiceCreateUserAsyncGrpcRequest request, CallContext context = default);
}

public class UserServiceGrpcClient : IUserService
{
    private readonly IUserServiceGrpcContract _grpcService;

    public UserServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<IUserServiceGrpcContract>();
    }

    public Task<MyApp.Services.UserDto> CreateUserAsync(MyApp.Services.CreateUserRequest request) => _grpcService.CreateUserAsync(new UserServiceCreateUserAsyncGrpcRequest { Request = request });

}
