//HintName: CommandServiceGrpcClient.g.cs
// <auto-generated />
#nullable enable

using Grpc.Net.Client;
using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Client;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class CommandServiceDeleteAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract(Name = "CommandServiceGrpcService")]
public interface ICommandServiceGrpcContract
{
    [OperationContract]
    Task DeleteAsync(CommandServiceDeleteAsyncGrpcRequest request, CallContext context = default);
}

public class CommandServiceGrpcClient : ICommandService
{
    private readonly ICommandServiceGrpcContract _grpcService;

    public CommandServiceGrpcClient(GrpcChannel channel)
    {
        _grpcService = channel.CreateGrpcService<ICommandServiceGrpcContract>();
    }

    public Task DeleteAsync(int id) => _grpcService.DeleteAsync(new CommandServiceDeleteAsyncGrpcRequest { Id = id });

}
