//HintName: ServerFunctionClientsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace BlazorServerFunctions.Sample.Shared;

public static class ServerFunctionClientsRegistration
{
    public static IServiceCollection AddServerFunctionClients(
        this IServiceCollection services)
    {
        services.AddHttpClient<IWeatherService, WeatherServiceClient>();

        return services;
    }
}
