//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/by-id",
            async ([AsParameters] GetUserByIdAsyncRequest request, IUserService service) =>
            {
                var result = await service.GetUserByIdAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IUserService_GetUserByIdAsync");

        return endpoints;
    }

    private record GetUserByIdAsyncRequest(int Id);
}
