//HintName: IItemServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IItemServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIItemServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/items");

        group.MapDelete("/{id}",
            async (int id, IItemService service) =>
            {
                await service.DeleteAsync(id);
                return Results.Ok();
            })
            .WithName("IItemService_DeleteAsync");

        return endpoints;
    }
}
