//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapPost("/CreateAsync",
            async Task<Results<Ok<User>, ProblemHttpResult>> ([FromBody] CreateAsyncRequest request, IUserService service) =>
            {
                var result = await service.CreateAsync(request.Name, request.Email);
                return TypedResults.Ok(result);
            })
            .WithName("IUserService_CreateAsync")
            .WithTags("UserService");

        return endpoints;
    }

    private record CreateAsyncRequest(string Name, string Email);
}
