//HintName: IProductServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IProductServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIProductServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/products");

        group.MapGet("/GetAllProductsAsync",
            async Task<Results<Ok<System.Collections.Generic.List<Product>>, ProblemHttpResult>> (IProductService service) =>
            {
                var result = await service.GetAllProductsAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IProductService_GetAllProductsAsync")
            .WithTags("ProductService");

        return endpoints;
    }
}
