//HintName: IAdminServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IAdminServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAdminServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/admin");
        group.RequireAuthorization();

        group.MapGet("/GetStatsAsync",
            async (IAdminService service) =>
            {
                var result = await service.GetStatsAsync();
                return Results.Ok(result);
            })
            .WithName("IAdminService_GetStatsAsync")
            .WithTags("AdminService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .RequireAuthorization("AdminOnly");

        group.MapGet("/GetStatusAsync",
            async (IAdminService service) =>
            {
                var result = await service.GetStatusAsync();
                return Results.Ok(result);
            })
            .WithName("IAdminService_GetStatusAsync")
            .WithTags("AdminService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
