//HintName: IBetaServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IBetaServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIBetaServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/betaservice");

        group.MapPost("/CreateAsync",
            async ([FromBody] CreateAsyncRequest request, IBetaService service) =>
            {
                await service.CreateAsync(request.Name);
                return Results.Ok();
            })
            .WithName("IBetaService_CreateAsync")
            .WithTags("BetaService")
            .Produces(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record CreateAsyncRequest(string Name);
}
