//HintName: ITestServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class ITestServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapITestServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/test");

        group.MapGet("/GetAllMessagesAsync",
            async (ITestService service) =>
            {
                var result = await service.GetAllMessagesAsync();
                return Results.Ok(result);
            })
            .WithName("ITestService_GetAllMessagesAsync");

        group.MapPost("/CreateAsync",
            async ([FromBody] CreateAsyncRequest request, ITestService service) =>
            {
                var result = await service.CreateAsync(request.Id, request.Name);
                return Results.Ok(result);
            })
            .WithName("ITestService_CreateAsync");

        group.MapPost("/AnotherMethodAsync",
            async (ITestService service) =>
            {
                await service.AnotherMethodAsync();
                return Results.Ok();
            })
            .WithName("ITestService_AnotherMethodAsync");

        return endpoints;
    }

    private record CreateAsyncRequest(int Id, string Name);
}
