//HintName: ServerFunctionEndpointsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using MyApp.Services;

namespace Tests;

public static class ServerFunctionEndpointsRegistration
{
    public static IEndpointRouteBuilder MapServerFunctionEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapINestedServiceEndpoints();
        return endpoints;
    }
}
