//HintName: ISearchServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class ISearchServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapISearchServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/search");

        group.MapPost("/SearchAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> ([FromQuery] int page, [FromQuery] int pageSize, [FromBody] SearchAsyncRequest request, ISearchService service) =>
            {
                var result = await service.SearchAsync(page, pageSize, request.Filter);
                return TypedResults.Ok(result);
            })
            .WithName("ISearchService_SearchAsync")
            .WithTags("SearchService");

        return endpoints;
    }

    private record SearchAsyncRequest(string Filter);
}
