//HintName: INestedServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class INestedServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapINestedServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/api/v2/nested/service");

        group.MapGet("/GetAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (INestedService service) =>
            {
                var result = await service.GetAsync();
                return TypedResults.Ok(result);
            })
            .WithName("INestedService_GetAsync")
            .WithTags("NestedService");

        return endpoints;
    }
}
