//HintName: ICustomServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace Custom.Deeply.Nested.Namespace.Services;

internal static class ICustomServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapICustomServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/custom");

        group.MapGet("/GetAsync",
            async (ICustomService service) =>
            {
                var result = await service.GetAsync();
                return Results.Ok(result);
            })
            .WithName("ICustomService_GetAsync");

        return endpoints;
    }
}
