//HintName: IAlphaServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IAlphaServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAlphaServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/alphaservice");

        group.MapGet("/GetAsync",
            async (IAlphaService service) =>
            {
                var result = await service.GetAsync();
                return Results.Ok(result);
            })
            .WithName("IAlphaService_GetAsync")
            .WithTags("AlphaService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
