//HintName: IMessageServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class IMessageServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIMessageServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/messages");

        group.MapGet("/GetAllMessagesAsync",
            async (IMessageService service) =>
            {
                var result = await service.GetAllMessagesAsync();
                return Results.Ok(result);
            })
            .WithName("IMessageService_GetAllMessagesAsync");

        return endpoints;
    }
}
