//HintName: ICounterServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class ICounterServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapICounterServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/counter");

        group.MapGet("/GetCountAsync",
            async Task<Results<Ok<int>, ProblemHttpResult>> (ICounterService service) =>
            {
                var result = await service.GetCountAsync();
                return TypedResults.Ok(result);
            })
            .WithName("ICounterService_GetCountAsync")
            .WithTags("CounterService");

        return endpoints;
    }
}
