//HintName: ICounterServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class ICounterServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapICounterServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/counters");

        group.MapGet("/GetCountAsync",
            async (ICounterService service) =>
            {
                var result = await service.GetCountAsync();
                return Results.Ok(result);
            })
            .WithName("ICounterService_GetCountAsync")
            .WithTags("CounterService")
            .Produces<int>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .RequireRateLimiting("fixed");

        group.MapPost("/IncrementAsync",
            async (ICounterService service) =>
            {
                var result = await service.IncrementAsync();
                return Results.Ok(result);
            })
            .WithName("ICounterService_IncrementAsync")
            .WithTags("CounterService")
            .Produces<int>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
