//HintName: INotificationServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class INotificationServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapINotificationServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/notifications");

        group.MapPost("/SendNotificationAsync",
            async Task<Results<Ok, ProblemHttpResult>> ([FromBody] SendNotificationAsyncRequest request, INotificationService service) =>
            {
                await service.SendNotificationAsync(request.Message);
                return TypedResults.Ok();
            })
            .WithName("INotificationService_SendNotificationAsync")
            .WithTags("NotificationService");

        return endpoints;
    }

    private record SendNotificationAsyncRequest(string Message);
}
