//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapPost("/CreateAsync",
            async ([FromBody] CreateAsyncRequest request, IUserService service) =>
            {
                var result = await service.CreateAsync(request.Name, request.Email);
                return Results.Ok(result);
            })
            .WithName("IUserService_CreateAsync")
            .WithTags("UserService")
            .Produces<User>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record CreateAsyncRequest(string Name, string Email);
}
