//HintName: IProductServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IProductServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIProductServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/productservice");

        group.MapGet("/GetProductAsync",
            async ([AsParameters] GetProductAsyncRequest request, IProductService service) =>
            {
                var result = await service.GetProductAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IProductService_GetProductAsync")
            .WithTags("Products", "Catalog")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetProductAsyncRequest(int Id);
}
