//HintName: IMessageServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IMessageServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIMessageServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/messages");

        group.MapGet("/GetAllMessagesAsync",
            async Task<Results<Ok<System.Collections.Generic.List<Message>>, ProblemHttpResult>> (IMessageService service) =>
            {
                var result = await service.GetAllMessagesAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IMessageService_GetAllMessagesAsync")
            .WithTags("MessageService");

        return endpoints;
    }
}
