//HintName: IFileServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IFileServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIFileServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/fileservice");

        group.MapPost("/UploadAsync",
            async (IFormFile file, [FromForm] string fileName, [FromForm] int categoryId, IFileService service) =>
            {
                var result = await service.UploadAsync(file.OpenReadStream(), fileName, categoryId);
                return Results.Ok(result);
            })
            .WithName("IFileService_UploadAsync")
            .WithTags("FileService")
            .Produces<long>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .DisableAntiforgery();

        return endpoints;
    }
}
