//HintName: IUserPostServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IUserPostServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserPostServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/users/{id}/posts",
            async (int id, [AsParameters] GetUserPostsAsyncRequest request, IUserPostService service) =>
            {
                var result = await service.GetUserPostsAsync(id, request.Page);
                return Results.Ok(result);
            })
            .WithName("IUserPostService_GetUserPostsAsync")
            .WithTags("UserPostService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetUserPostsAsyncRequest(int Page);
}
