//HintName: IEventServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading;
using MyApp.Services;

namespace Tests;

internal static class IEventServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIEventServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/events");

        group.MapGet("/StreamEventsAsync",
            (IEventService service, CancellationToken cancellationToken) =>
            {
                return service.StreamEventsAsync(cancellationToken);
            })
            .WithName("IEventService_StreamEventsAsync");

        return endpoints;
    }
}
