//HintName: IOrderServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services.Orders;

internal static class IOrderServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIOrderServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/orders");

        group.MapPost("/CreateOrderAsync",
            async ([FromBody] CreateOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.CreateOrderAsync(request.UserId);
                return Results.Ok(result);
            })
            .WithName("IOrderService_CreateOrderAsync");

        return endpoints;
    }

    private record CreateOrderAsyncRequest(int UserId);
}
