//HintName: IAlphaServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IAlphaServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAlphaServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/alphaservice");

        group.MapGet("/GetAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IAlphaService service) =>
            {
                var result = await service.GetAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IAlphaService_GetAsync")
            .WithTags("AlphaService");

        return endpoints;
    }
}
