//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetAllUsersAsync",
            async Task<Results<Ok<System.Collections.Generic.List<User>>, ProblemHttpResult>> (IUserService service) =>
            {
                var result = await service.GetAllUsersAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IUserService_GetAllUsersAsync")
            .WithTags("UserService");

        return endpoints;
    }
}
