//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapDelete("/users/{id}",
            async Task<Results<Ok, ProblemHttpResult>> (int id, IUserService service) =>
            {
                await service.DeleteUserAsync(id);
                return TypedResults.Ok();
            })
            .WithName("IUserService_DeleteUserAsync")
            .WithTags("UserService");

        return endpoints;
    }
}
