//HintName: IDataServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IDataServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDataServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/data");

        group.MapGet("/GetDataAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IDataService service) =>
            {
                var result = await service.GetDataAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IDataService_GetDataAsync")
            .WithTags("DataService");

        return endpoints;
    }
}
