//HintName: INotificationServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class INotificationServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapINotificationServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/notifications");

        group.MapPost("/SendNotificationAsync",
            async ([FromBody] SendNotificationAsyncRequest request, INotificationService service) =>
            {
                await service.SendNotificationAsync(request.Message);
                return Results.Ok();
            })
            .WithName("INotificationService_SendNotificationAsync");

        return endpoints;
    }

    private record SendNotificationAsyncRequest(string Message);
}
