//HintName: IDocumentServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IDocumentServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDocumentServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/docs");

        group.MapPost("/docs/{folderId}",
            async Task<Results<Ok<string>, ProblemHttpResult>> (int folderId, [FromHeader(Name = "X-Api-Key")] string apiKey, [FromQuery] string lang, [FromBody] CreateDocumentAsyncRequest request, IDocumentService service) =>
            {
                var result = await service.CreateDocumentAsync(folderId, apiKey, lang, request.Title, request.Content);
                return TypedResults.Ok(result);
            })
            .WithName("IDocumentService_CreateDocumentAsync")
            .WithTags("DocumentService");

        return endpoints;
    }

    private record CreateDocumentAsyncRequest(string Title, string Content);
}
