//HintName: ITestServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class ITestServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapITestServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/test");

        group.MapGet("/GetAllMessagesAsync",
            async Task<Results<Ok<System.Collections.Generic.List<Message>>, ProblemHttpResult>> (ITestService service) =>
            {
                var result = await service.GetAllMessagesAsync();
                return TypedResults.Ok(result);
            })
            .WithName("ITestService_GetAllMessagesAsync")
            .WithTags("TestService");

        group.MapPost("/CreateAsync",
            async Task<Results<Ok<User>, ProblemHttpResult>> ([FromBody] CreateAsyncRequest request, ITestService service) =>
            {
                var result = await service.CreateAsync(request.Id, request.Name);
                return TypedResults.Ok(result);
            })
            .WithName("ITestService_CreateAsync")
            .WithTags("TestService");

        group.MapPost("/AnotherMethodAsync",
            async Task<Results<Ok, ProblemHttpResult>> (ITestService service) =>
            {
                await service.AnotherMethodAsync();
                return TypedResults.Ok();
            })
            .WithName("ITestService_AnotherMethodAsync")
            .WithTags("TestService");

        return endpoints;
    }

    private record CreateAsyncRequest(int Id, string Name);
}
