//HintName: INotificationServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class INotificationServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapINotificationServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/notifications");

        group.MapPost("/SendAsync",
            async ([FromBody] SendAsyncRequest request, INotificationService service) =>
            {
                await service.SendAsync(request.Message);
                return Results.Ok();
            })
            .WithName("INotificationService_SendAsync")
            .WithTags("NotificationService")
            .Produces(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .WithOpenApi();

        return endpoints;
    }

    private record SendAsyncRequest(string Message);
}
