//HintName: INestedServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class INestedServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapINestedServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/api/v2/nested/service");

        group.MapGet("/GetAsync",
            async (INestedService service) =>
            {
                var result = await service.GetAsync();
                return Results.Ok(result);
            })
            .WithName("INestedService_GetAsync");

        return endpoints;
    }
}
