//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetAllUsersAsync",
            async (IUserService service) =>
            {
                var result = await service.GetAllUsersAsync();
                return Results.Ok(result);
            })
            .WithName("IUserService_GetAllUsersAsync")
            .WithTags("UserService")
            .Produces<System.Collections.Generic.List<User>>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
