//HintName: IWeatherServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IWeatherServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIWeatherServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/weather");

        group.MapGet("/StreamForecastsAsync",
            (IWeatherService service) =>
            {
                return service.StreamForecastsAsync();
            })
            .WithName("IWeatherService_StreamForecastsAsync")
            .WithTags("WeatherService");

        return endpoints;
    }
}
