//HintName: IDataServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp;

namespace Tests;

internal static class IDataServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDataServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/data");
        group.RequireCors("DefaultPolicy");

        group.MapGet("/GetDataAsync",
            async (IDataService service) =>
            {
                var result = await service.GetDataAsync();
                return Results.Ok(result);
            })
            .WithName("IDataService_GetDataAsync")
            .WithTags("DataService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
