//HintName: ITaskServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class ITaskServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapITaskServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/tasks");

        group.MapPost("/ProcessAsync",
            async (ITaskService service) =>
            {
                var result = await service.ProcessAsync();
                return Results.Ok(result);
            })
            .WithName("ITaskService_ProcessAsync")
            .WithTags("TaskService")
            .Produces<Result>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
