//HintName: ServerFunctionEndpointsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;

namespace Custom.Deeply.Nested.Namespace.Services;

public static class ServerFunctionEndpointsRegistration
{
    public static IEndpointRouteBuilder MapServerFunctionEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapICustomServiceEndpoints();
        return endpoints;
    }
}
