//HintName: ServerFunctionEndpointsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using MyApp.Services.Orders;
using MyApp.Services.Users;

namespace Tests;

public static class ServerFunctionEndpointsRegistration
{
    public static IEndpointRouteBuilder MapServerFunctionEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapIUserServiceEndpoints();
        endpoints.MapIOrderServiceEndpoints();
        return endpoints;
    }
}
