//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/FindUserAsync",
            async ([AsParameters] FindUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.FindUserAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IUserService_FindUserAsync");

        return endpoints;
    }

    private record FindUserAsyncRequest(int Id);
}
