//HintName: IOrderServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IOrderServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIOrderServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/orderservice");

        group.MapGet("/GetOrderAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> ([AsParameters] GetOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.GetOrderAsync(request.Id);
                return TypedResults.Ok(result);
            })
            .WithName("IOrderService_GetOrderAsync")
            .WithTags("OrderService");

        return endpoints;
    }

    private record GetOrderAsyncRequest(int Id);
}
