//HintName: ICalculatorServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class ICalculatorServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapICalculatorServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/calculator");

        group.MapPost("/AddAsync",
            async Task<Results<Ok<int>, ProblemHttpResult>> ([FromBody] AddAsyncRequest request, ICalculatorService service) =>
            {
                var result = await service.AddAsync(request.FirstNumber, request.SecondNumber);
                return TypedResults.Ok(result);
            })
            .WithName("ICalculatorService_AddAsync")
            .WithTags("CalculatorService");

        return endpoints;
    }

    private record AddAsyncRequest(int FirstNumber, int SecondNumber);
}
