//HintName: ICounterServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class ICounterServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapICounterServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/counter");

        group.MapGet("/GetCountAsync",
            async (ICounterService service) =>
            {
                var result = await service.GetCountAsync();
                return Results.Ok(result);
            })
            .WithName("ICounterService_GetCountAsync");

        return endpoints;
    }
}
