//HintName: IFileServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IFileServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIFileServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/fileservice");

        group.MapPost("/UploadAsync",
            async Task<Results<Ok<long>, ProblemHttpResult>> (IFormFileCollection files, IFileService service) =>
            {
                var result = await service.UploadAsync(files);
                return TypedResults.Ok(result);
            })
            .WithName("IFileService_UploadAsync")
            .WithTags("FileService")
            .DisableAntiforgery();

        return endpoints;
    }
}
