//HintName: IValueTaskServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IValueTaskServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIValueTaskServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/valuetasks");

        group.MapPost("/ProcessAsync",
            async Task<Results<Ok<Result>, ProblemHttpResult>> (IValueTaskService service) =>
            {
                var result = await service.ProcessAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IValueTaskService_ProcessAsync")
            .WithTags("ValueTaskService");

        return endpoints;
    }
}
