//HintName: IValueTaskServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IValueTaskServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIValueTaskServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/valuetasks");

        group.MapPost("/ProcessAsync",
            async (IValueTaskService service) =>
            {
                var result = await service.ProcessAsync();
                return Results.Ok(result);
            })
            .WithName("IValueTaskService_ProcessAsync")
            .WithTags("ValueTaskService")
            .Produces<Result>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
