//HintName: ISpecialServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class ISpecialServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapISpecialServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/special");

        group.MapGet("/SpecialMethodAsync",
            async Task<Results<Ok<Result>, ProblemHttpResult>> (ISpecialService service) =>
            {
                var result = await service.SpecialMethodAsync();
                return TypedResults.Ok(result);
            })
            .WithName("ISpecialService_SpecialMethodAsync")
            .WithTags("SpecialService");

        return endpoints;
    }
}
