//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetUserAsync",
            async ([AsParameters] GetUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.GetUserAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IUserService_GetUserAsync");

        return endpoints;
    }

    private record GetUserAsyncRequest(int Id);
}
