//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapPost("/CreateUserAsync",
            async Task<Results<Ok<User>, ProblemHttpResult>> ([FromBody] CreateUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.CreateUserAsync(request.Name, request.Email, request.Age);
                return TypedResults.Ok(result);
            })
            .WithName("IUserService_CreateUserAsync")
            .WithTags("UserService");

        return endpoints;
    }

    private record CreateUserAsyncRequest(string Name, string Email, int Age);
}
