//HintName: IProductServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class IProductServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIProductServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/products");

        group.MapGet("/GetAllProductsAsync",
            async (IProductService service) =>
            {
                var result = await service.GetAllProductsAsync();
                return Results.Ok(result);
            })
            .WithName("IProductService_GetAllProductsAsync");

        return endpoints;
    }
}
