//HintName: IItemServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp;

namespace Tests;

internal static class IItemServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIItemServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/items");

        group.MapGet("/GetItemAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IItemService service) =>
            {
                var result = await service.GetItemAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IItemService_GetItemAsync")
            .WithTags("ItemService")
            .RequireRateLimiting("fixed");

        group.MapGet("/GetOtherItemAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IItemService service) =>
            {
                var result = await service.GetOtherItemAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IItemService_GetOtherItemAsync")
            .WithTags("ItemService")
            .RequireRateLimiting("sliding");

        return endpoints;
    }
}
