//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapPost("/CreateUserAsync",
            async ([FromBody] CreateUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.CreateUserAsync(request.Name, request.Email, request.Age);
                return Results.Ok(result);
            })
            .WithName("IUserService_CreateUserAsync");

        return endpoints;
    }

    private record CreateUserAsyncRequest(string Name, string Email, int Age);
}
