//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace MyApp.Services;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetAllAsync",
            async (IUserService service) =>
            {
                var result = await service.GetAllAsync();
                return Results.Ok(result);
            })
            .WithName("IUserService_GetAllAsync");

        group.MapGet("/GetByIdAsync",
            async ([AsParameters] GetByIdAsyncRequest request, IUserService service) =>
            {
                var result = await service.GetByIdAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IUserService_GetByIdAsync");

        group.MapPost("/CreateAsync",
            async ([FromBody] CreateAsyncRequest request, IUserService service) =>
            {
                var result = await service.CreateAsync(request.Name, request.Email);
                return Results.Ok(result);
            })
            .WithName("IUserService_CreateAsync");

        return endpoints;
    }

    private record GetByIdAsyncRequest(int Id);

    private record CreateAsyncRequest(string Name, string Email);
}
