//HintName: IItemServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IItemServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIItemServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/items");

        group.MapPut("/{id}",
            async (int id, [FromBody] UpdateAsyncRequest request, IItemService service) =>
            {
                var result = await service.UpdateAsync(id, request.Value);
                return Results.Ok(result);
            })
            .WithName("IItemService_UpdateAsync")
            .WithTags("ItemService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record UpdateAsyncRequest(string Value);
}
