//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services.Users;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetUserAsync",
            async Task<Results<Ok<User>, ProblemHttpResult>> ([AsParameters] GetUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.GetUserAsync(request.Id);
                return TypedResults.Ok(result);
            })
            .WithName("IUserService_GetUserAsync")
            .WithTags("UserService");

        return endpoints;
    }

    private record GetUserAsyncRequest(int Id);
}
