//HintName: IDataServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IDataServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDataServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/data");

        group.MapGet("/StreamDataAsync",
            (IDataService service) =>
            {
                return service.StreamDataAsync();
            })
            .WithName("IDataService_StreamDataAsync")
            .WithTags("DataService")
            .RequireRateLimiting("fixed");

        return endpoints;
    }
}
