//HintName: IItemServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IItemServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIItemServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/items");

        group.MapGet("/GetAllAsync",
            async (IItemService service) =>
            {
                var result = await service.GetAllAsync();
                return Results.Ok(result);
            })
            .WithName("IItemService_GetAllAsync")
            .WithTags("ItemService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        group.MapDelete("/DeleteAsync",
            async ([AsParameters] DeleteAsyncRequest request, IItemService service) =>
            {
                await service.DeleteAsync(request.Id);
                return Results.Ok();
            })
            .WithName("IItemService_DeleteAsync")
            .WithTags("ItemService")
            .Produces(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .RequireAuthorization(new AuthorizeAttribute { Roles = "Admin" });

        return endpoints;
    }

    private record DeleteAsyncRequest(int Id);
}
