//HintName: IBetaServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IBetaServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIBetaServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/betaservice");

        group.MapPost("/CreateAsync",
            async Task<Results<Ok, ProblemHttpResult>> ([FromBody] CreateAsyncRequest request, IBetaService service) =>
            {
                await service.CreateAsync(request.Name);
                return TypedResults.Ok();
            })
            .WithName("IBetaService_CreateAsync")
            .WithTags("BetaService");

        return endpoints;
    }

    private record CreateAsyncRequest(string Name);
}
