//HintName: IItemServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IItemServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIItemServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/items");

        group.MapGet("/GetItemAsync",
            async (IItemService service) =>
            {
                var result = await service.GetItemAsync();
                return Results.Ok(result);
            })
            .WithName("IItemService_GetItemAsync")
            .WithTags("ItemService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .RequireAuthorization("AdminOnly");

        group.MapPost("/CreateItemAsync",
            async (IItemService service) =>
            {
                var result = await service.CreateItemAsync();
                return Results.Ok(result);
            })
            .WithName("IItemService_CreateItemAsync")
            .WithTags("ItemService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }
}
