//HintName: IAdminServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IAdminServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAdminServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/admin");
        group.RequireAuthorization();

        group.MapGet("/GetSecretAsync",
            async (IAdminService service) =>
            {
                var result = await service.GetSecretAsync();
                return Results.Ok(result);
            })
            .WithName("IAdminService_GetSecretAsync")
            .WithTags("AdminService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        group.MapPost("/DoActionAsync",
            async ([FromBody] DoActionAsyncRequest request, IAdminService service) =>
            {
                await service.DoActionAsync(request.Command);
                return Results.Ok();
            })
            .WithName("IAdminService_DoActionAsync")
            .WithTags("AdminService")
            .Produces(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record DoActionAsyncRequest(string Command);
}
