//HintName: IOrderServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IOrderServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIOrderServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/orderservice");

        group.MapGet("/GetOrderAsync",
            async ([AsParameters] GetOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.GetOrderAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IOrderService_GetOrderAsync")
            .WithTags("OrderService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetOrderAsyncRequest(int Id);
}
