//HintName: IAdminServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IAdminServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAdminServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/admin");

        group.MapGet("/GetStatsAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IAdminService service) =>
            {
                var result = await service.GetStatsAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IAdminService_GetStatsAsync")
            .WithTags("AdminService")
            .RequireAuthorization(new AuthorizeAttribute { Roles = "Admin" });

        return endpoints;
    }
}
