//HintName: IProductServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IProductServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIProductServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/productservice");

        group.MapGet("/GetProductAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> ([AsParameters] GetProductAsyncRequest request, IProductService service) =>
            {
                var result = await service.GetProductAsync(request.Id);
                return TypedResults.Ok(result);
            })
            .WithName("IProductService_GetProductAsync")
            .WithTags("ProductService")
            .Produces(404)
            .Produces(409);

        return endpoints;
    }

    private record GetProductAsyncRequest(int Id);
}
