//HintName: IDataServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IDataServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDataServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/data");

        group.MapPost("/SubmitDataAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> ([FromBody] SubmitDataAsyncRequest request, IDataService service) =>
            {
                var result = await service.SubmitDataAsync(request.Value);
                return TypedResults.Ok(result);
            })
            .WithName("IDataService_SubmitDataAsync")
            .WithTags("DataService")
            .AddEndpointFilter<global::MyApp.Services.FirstFilter>()
            .AddEndpointFilter<global::MyApp.Services.SecondFilter>();

        return endpoints;
    }

    private record SubmitDataAsyncRequest(string Value);
}
