//HintName: IAdminServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IAdminServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIAdminServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/admin");
        group.RequireAuthorization();

        group.MapGet("/GetSecretAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> (IAdminService service) =>
            {
                var result = await service.GetSecretAsync();
                return TypedResults.Ok(result);
            })
            .WithName("IAdminService_GetSecretAsync")
            .WithTags("AdminService");

        group.MapPost("/DoActionAsync",
            async Task<Results<Ok, ProblemHttpResult>> ([FromBody] DoActionAsyncRequest request, IAdminService service) =>
            {
                await service.DoActionAsync(request.Command);
                return TypedResults.Ok();
            })
            .WithName("IAdminService_DoActionAsync")
            .WithTags("AdminService");

        return endpoints;
    }

    private record DoActionAsyncRequest(string Command);
}
