//HintName: IWeatherServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.OpenApi;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IWeatherServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIWeatherServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/weather");

        group.MapGet("/GetForecastsAsync",
            async (IWeatherService service) =>
            {
                var result = await service.GetForecastsAsync();
                return Results.Ok(result);
            })
            .WithName("IWeatherService_GetForecastsAsync")
            .WithTags("WeatherService")
            .Produces<WeatherForecast[]>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError)
            .WithOpenApi();

        return endpoints;
    }
}
