//HintName: IDataServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IDataServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIDataServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/data");

        group.MapPost("/ProcessAsync",
            async ([FromBody] ProcessAsyncRequest request, IDataService service) =>
            {
                var result = await service.ProcessAsync(request.Id, request.Timestamp, request.Numbers, request.Metadata);
                return Results.Ok(result);
            })
            .WithName("IDataService_ProcessAsync")
            .WithTags("DataService")
            .Produces<Result>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record ProcessAsyncRequest(System.Guid Id, System.DateTime Timestamp, System.Collections.Generic.List<int> Numbers, System.Collections.Generic.Dictionary<string, string> Metadata);
}
