//HintName: IOrderServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IOrderServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIOrderServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/orders");

        group.MapPost("/CreateOrderAsync",
            async Task<Results<Ok<Order>, ProblemHttpResult>> ([FromBody] CreateOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.CreateOrderAsync(request.UserId, request.ProductId);
                return TypedResults.Ok(result);
            })
            .WithName("IOrderService_CreateOrderAsync")
            .WithTags("OrderService");

        return endpoints;
    }

    private record CreateOrderAsyncRequest(int UserId, int ProductId);
}
