using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ClientProxyGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        var hasCancellationToken = interfaceInfo.Methods.Any(m => m.HasCancellationToken);
        AddUsingDirectives(sb: sb, hasCancellationToken: hasCancellationToken);

        sb.Append("namespace ").Append(interfaceInfo.Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("public class ").Append(interfaceInfo.Name.TrimStart('I')).Append("Client : ").Append(interfaceInfo.Name).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine($"    private const string BaseRoute = \"/api/functions/{interfaceInfo.RoutePrefix}\";");
        sb.AppendLine();

        AddConstructor(sb: sb, name: interfaceInfo.Name);

        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
        {
            GenerateClientMethod(sb, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AddConstructor(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public {name.TrimStart('I')}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
    }

    private static void AddUsingDirectives(StringBuilder sb, bool hasCancellationToken)
    {
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        if (hasCancellationToken)
            sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
    }

    private static string GetAwaitKeyword(AsyncType asyncType) =>
        asyncType is not AsyncType.None ? "await " : string.Empty;

    private static string GetResultSuffix(AsyncType asyncType) =>
        asyncType is AsyncType.None ? ".GetAwaiter().GetResult()" : string.Empty;

    private static void GenerateClientMethod(StringBuilder sb, MethodInfo methodInfo)
    {
        GenerateMethodSignature(
            sb: sb,
            method: methodInfo);

        sb.AppendLine("    {");

        var hasParameters = methodInfo.Parameters.Count > 0;
        if (hasParameters && methodInfo.HttpMethod is HttpMethod.Post or HttpMethod.Put or HttpMethod.Patch)
            BuildRequestObject(sb: sb, parameters: methodInfo.Parameters);

        GenerateHttpRequest(
            sb: sb,
            method: methodInfo);

        sb.AppendLine();
        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine();

        if (!string.Equals(methodInfo.ReturnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            sb.Append("        return ")
                .Append(GetAwaitKeyword(methodInfo.AsyncType))
                .Append("response.Content.ReadFromJsonAsync<")
                .Append(methodInfo.ReturnType)
                .Append(">()")
                .Append(GetResultSuffix(methodInfo.AsyncType))
                .AppendLine();
            sb.AppendLine("            ?? throw new InvalidOperationException(\"Response deserialization returned null\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void BuildRequestObject(StringBuilder sb, List<ParameterInfo> parameters)
    {
        sb.AppendLine("        var request = new");
        sb.AppendLine("        {");

        foreach (var parameterName in parameters.Select(p => p.Name))
        {
            sb.Append("            ")
                .Append(parameterName.ToPascalCase())
                .Append(" = ")
                .Append(parameterName)
                .AppendLine(",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void GenerateMethodSignature(
        StringBuilder sb,
        MethodInfo method)
    {
        sb.Append("    public ");

        if (method.AsyncType is not AsyncType.None)
        {
            sb.Append("async ").Append(method.AsyncType.ToString());
            if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
                sb.Append('<').Append(method.ReturnType).Append('>');
        }
        else sb.Append(method.ReturnType);

        sb.Append(' ').Append(method.Name).Append('(');

        var paramDeclarations = method.Parameters.Select(p =>
        {
            var declaration = $"{p.Type} {p.Name}";
            if (p.HasDefaultValue)
            {
                declaration += $" = {FormatDefaultValue(p.Type, p.DefaultValue)}";
            }

            return declaration;
        }).ToList();

        if (method.HasCancellationToken)
        {
            if (paramDeclarations.Count > 0)
                sb.Append(string.Join(", ", paramDeclarations)).Append(", CancellationToken cancellationToken = default");
            else
                sb.Append("CancellationToken cancellationToken = default");
        }
        else
        {
            sb.Append(string.Join(", ", paramDeclarations));
        }

        sb.AppendLine(")");
    }

    private static void GenerateHttpRequest(StringBuilder sb, MethodInfo method)
    {
        var routeName = method.CustomRoute ?? method.Name;

        switch (method.HttpMethod)
        {
            case HttpMethod.Post:
                GeneratePostRequest(sb, routeName, method.Parameters.Count > 0, method.AsyncType, method.HasCancellationToken);
                break;

            case HttpMethod.Get:
            case HttpMethod.Delete:
                GenerateQueryStringRequest(sb, routeName, method.HttpMethod, method.Parameters, method.AsyncType, method.HasCancellationToken);
                break;

            default:
                GenerateOtherRequest(sb, routeName, method.HttpMethod, method.Parameters.Count > 0, method.AsyncType, method.HasCancellationToken);
                break;
        }
    }

    private static void GeneratePostRequest(StringBuilder sb, string routeName, bool hasParameters, AsyncType asyncType, bool hasCancellationToken)
    {
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        if (hasParameters)
        {
            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.PostAsJsonAsync(");
            sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
            if (hasCancellationToken)
            {
                sb.AppendLine("            request,");
                sb.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                sb.AppendLine($"            request){resultSuffix};");
            }
        }
        else
        {
            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.PostAsync(");
            sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
            if (hasCancellationToken)
            {
                sb.AppendLine("            null,");
                sb.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                sb.AppendLine($"            null){resultSuffix};");
            }
        }
    }

    private static void GenerateQueryStringRequest(
        StringBuilder sb,
        string routeName,
        HttpMethod httpMethod,
        List<ParameterInfo> parameters,
        AsyncType asyncType,
        bool hasCancellationToken)
    {
        var verb = httpMethod.ToString();
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        if (parameters.Count > 0)
        {
            sb.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");

            foreach (var parameter in parameters)
            {
                sb.Append("        queryString[\"")
                    .Append(parameter.Name.ToPascalCase())
                    .Append("\"] = ")
                    .Append(parameter.Name)
                    .AppendLine($"{(parameter.Type.EndsWith('?') ? "?" : string.Empty)}.ToString(System.Globalization.CultureInfo.InvariantCulture);");
            }

            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.{verb}Async(");
            if (hasCancellationToken)
            {
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}?{{queryString}}\",");
                sb.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}?{{queryString}}\"){resultSuffix};");
            }
        }
        else
        {
            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.{verb}Async(");
            if (hasCancellationToken)
            {
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\",");
                sb.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\"){resultSuffix};");
            }
        }
    }

    private static void GenerateOtherRequest(
        StringBuilder sb,
        string routeName,
        HttpMethod httpMethod,
        bool hasParameters,
        AsyncType asyncType,
        bool hasCancellationToken)
    {
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        sb.AppendLine("        var requestMessage = new HttpRequestMessage");
        sb.AppendLine("        {");
        sb.AppendLine($"            Method = HttpMethod.{httpMethod},");

        if (hasParameters)
        {
            sb.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{routeName}\", UriKind.Relative),");
            sb.AppendLine("            Content = JsonContent.Create(request)");
        }
        else
        {
            sb.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{routeName}\", UriKind.Relative)");
        }

        sb.AppendLine("        };");

        if (hasCancellationToken)
            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.SendAsync(requestMessage, cancellationToken){resultSuffix};");
        else
            sb.AppendLine($"        var response = {awaitKeyword}_httpClient.SendAsync(requestMessage){resultSuffix};");
    }

    private static string FormatDefaultValue(string type, object? defaultValue)
    {
        if (defaultValue == null)
        {
            return "null";
        }

        if (string.Equals(type, "string", StringComparison.OrdinalIgnoreCase))
        {
            return $"\"{defaultValue}\"";
        }

        if (string.Equals(type, "bool", StringComparison.OrdinalIgnoreCase))
        {
            return defaultValue.ToString()?.ToLowerInvariant() ?? false.ToString();
        }

        if (type.Contains('?') && string.Equals(defaultValue.ToString(), "null", StringComparison.OrdinalIgnoreCase))
        {
            return "null";
        }

        return Convert.ToString(defaultValue, System.Globalization.CultureInfo.InvariantCulture)!;
    }
}
