using System.Globalization;
using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ClientProxyGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        AddUsingDirectives(sb: sb);

        sb.Append("namespace ").Append(interfaceInfo.Namespace).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("public class ").Append(interfaceInfo.Name.TrimStart('I')).Append("Client : ").Append(interfaceInfo.Name).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine($"    private const string BaseRoute = \"/api/functions/{interfaceInfo.RoutePrefix}\";");
        sb.AppendLine();

        AddConstructor(sb: sb, name: interfaceInfo.Name);

        sb.AppendLine();

        // Generate method implementations
        foreach (var method in interfaceInfo.Methods)
        {
            GenerateClientMethod(sb, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AddConstructor(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public {name.TrimStart('I')}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
    }

    private static void AddUsingDirectives(StringBuilder sb)
    {
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
    }

    private static void GenerateClientMethod(StringBuilder sb, MethodInfo methodInfo)
    {
        GenerateMethodSignature(
            sb: sb,
            method: methodInfo);

        sb.AppendLine("    {");

        var hasParameters = methodInfo.Parameters.Count > 0;
        if (hasParameters)
            BuildRequestObject(sb: sb, parameters: methodInfo.Parameters);

        GenerateHttpRequest(
            sb: sb,
            method: methodInfo);

        sb.AppendLine();
        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine();

        // Handle response
        if (!string.Equals(methodInfo.ReturnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            sb.Append("        return await response.Content.ReadFromJsonAsync")
                .Append('<')
                .Append(methodInfo.ReturnType)
                .AppendLine(">()");
            sb.AppendLine("            ?? throw new InvalidOperationException(\"Response deserialization returned null\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void BuildRequestObject(StringBuilder sb, List<ParameterInfo> parameters)
    {
        sb.AppendLine("        var request = new");
        sb.AppendLine("        {");

        foreach (var parameterName in parameters.Select(p => p.Name))
        {
            sb.Append("            ")
                .Append(parameterName.ToPascalCase())
                .Append(" = ")
                .Append(parameterName)
                .AppendLine(",");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    internal static void GenerateMethodSignature(
        StringBuilder sb,
        MethodInfo method)
    {
        sb.Append("    public ");

        if (method.AsyncType is not AsyncType.None)
            sb.Append("async ")
                .Append(method.AsyncType.ToString())
                .Append('<')
                .Append(method.ReturnType)
                .Append('>');
        else sb.Append(method.ReturnType);

        sb.Append(' ').Append(method.Name).Append('(');

        var paramDeclarations = method.Parameters.Select(p =>
        {
            var declaration = $"{p.Type} {p.Name}";
            if (p.HasDefaultValue)
            {
                declaration += $" = {FormatDefaultValue(p.Type, p.DefaultValue)}";
            }

            return declaration;
        });

        sb.Append(string.Join(", ", paramDeclarations));
        sb.AppendLine(")");
    }

    private static void GenerateHttpRequest(StringBuilder sb, MethodInfo method)
    {
        var routeName = method.CustomRoute ?? method.Name;
        var httpMethod = method.HttpMethod.ToLowerInvariant();
        var hasParameters = method.Parameters.Count > 0;

        switch (httpMethod)
        {
            case "post":
                GeneratePostRequest(sb, routeName, hasParameters);
                break;

            case "get":
                GenerateGetRequest(sb, routeName, hasParameters, method.Parameters);
                break;

            default: // PUT, DELETE, PATCH
                GenerateOtherRequest(sb, routeName, httpMethod, hasParameters);
                break;
        }
    }

    private static void GeneratePostRequest(StringBuilder sb, string routeName, bool hasParameters)
    {
        if (hasParameters)
        {
            sb.AppendLine("        var response = await _httpClient.PostAsJsonAsync(");
            sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
            sb.AppendLine("            request);");
        }
        else
        {
            sb.AppendLine("        var response = await _httpClient.PostAsync(");
            sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
            sb.AppendLine("            null);");
        }
    }

    private static void GenerateGetRequest(
        StringBuilder sb,
        string routeName,
        bool hasParameters,
        List<ParameterInfo> parameters)
    {
        if (hasParameters)
        {
            sb.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");

            foreach (var parameterName in parameters.Select(p => p.Name))
            {
                sb.Append("        queryString[\"")
                    .Append(parameterName.ToPascalCase())
                    .Append("\"] = ")
                    .Append(parameterName)
                    .AppendLine("?.ToString();");
            }

            sb.AppendLine("        var response = await _httpClient.GetAsync(");
            sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}?{{queryString}}\");");
        }
        else
        {
            sb.AppendLine("        var response = await _httpClient.GetAsync(");
            sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\");");
        }
    }

    private static void GenerateOtherRequest(
        StringBuilder sb,
        string routeName,
        string httpMethod,
        bool hasParameters)
    {
        var httpMethodUpper = httpMethod.ToUpperInvariant();

        sb.AppendLine("        var requestMessage = new HttpRequestMessage");
        sb.AppendLine("        {");
        sb.AppendLine($"            Method = HttpMethod.{httpMethodUpper},");
        sb.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{routeName}\", UriKind.Relative)");

        if (hasParameters)
        {
            sb.AppendLine(",            Content = JsonContent.Create(request)");
        }

        sb.AppendLine("        };");
        sb.AppendLine("        var response = await _httpClient.SendAsync(requestMessage);");
    }

    private static string FormatDefaultValue(string type, object? defaultValue)
    {
        if (defaultValue == null)
        {
            return "null";
        }

        if (string.Equals(type, "string", StringComparison.OrdinalIgnoreCase))
        {
            return $"\"{defaultValue}\"";
        }

        if (string.Equals(type, "bool", StringComparison.OrdinalIgnoreCase))
        {
            return defaultValue.ToString()?.ToLowerInvariant() ?? false.ToString();
        }

        if (type.Contains('?') && string.Equals(defaultValue.ToString(), "null", StringComparison.OrdinalIgnoreCase))
        {
            return "null";
        }

        return defaultValue!.ToString()!;
    }
}