using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ClientRegistrationGenerator
{
    public static string Generate(IReadOnlyCollection<InterfaceInfo> interfaces, string? targetNamespace)
    {
        if (interfaces.Count == 0)
            return string.Empty;

        var sb = new StringBuilder();

        var ns = !string.IsNullOrEmpty(targetNamespace) ? targetNamespace : interfaces.First().Namespace;
        var externalNamespaces = interfaces
            .Select(i => i.Namespace)
            .Where(n => !string.Equals(n, ns, StringComparison.Ordinal) && !string.IsNullOrEmpty(n))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");

        foreach (var externalNs in externalNamespaces)
            sb.Append("using ").Append(externalNs).AppendLine(";");

        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("public static class ServerFunctionClientsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddServerFunctionClients(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        Uri? baseAddress = null)");
        sb.AppendLine("    {");

        foreach (var interfaceName in interfaces.Select(i => i.Name))
        {
            var clientClassName = interfaceName.TrimStart('I') + "Client";

            sb.Append("        services.AddHttpClient<")
                .Append(interfaceName)
                .Append(", ")
                .Append(clientClassName)
                .AppendLine(">()")
                .AppendLine("            .ConfigureHttpClient(c => { if (baseAddress != null) c.BaseAddress = baseAddress; });");
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
