using System.Globalization;
using System.Text;
using BlazorServerFunctions.Generator.Helpers;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ClientProxyGenerator
{
    public static string Generate(object interfaceInfoObj)
    {
        var interfaceInfo = interfaceInfoObj;
        var type = interfaceInfo.GetType();
        var name = (string)type.GetProperty("Name").GetValue(interfaceInfo);
        var ns = (string)type.GetProperty("Namespace").GetValue(interfaceInfo);
        var routePrefix = (string)type.GetProperty("RoutePrefix").GetValue(interfaceInfo);
        var methods = (System.Collections.IEnumerable)type.GetProperty("Methods").GetValue(interfaceInfo);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        AddUsingDirectives(sb: sb);

        sb.Append("namespace ").Append(ns).Append(';').AppendLine();
        sb.AppendLine();
        sb.Append("public class ").Append(name.TrimStart('I')).Append("Client : ").Append(name).AppendLine();
        sb.AppendLine("{");
        sb.AppendLine("    private readonly HttpClient _httpClient;");
        sb.AppendLine($"    private const string BaseRoute = \"/api/functions/{routePrefix}\";");
        sb.AppendLine();

        AddConstructor(sb: sb, name: name);

        sb.AppendLine();

        // Generate method implementations
        foreach (var method in methods)
        {
            GenerateClientMethod(sb, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AddConstructor(StringBuilder sb, string name)
    {
        sb.AppendLine($"    public {name.TrimStart('I')}Client(HttpClient httpClient)");
        sb.AppendLine("    {");
        sb.AppendLine("        _httpClient = httpClient;");
        sb.AppendLine("    }");
    }

    private static void AddUsingDirectives(StringBuilder sb)
    {
        sb.AppendLine("using System.Net.Http;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
    }

    private static void GenerateClientMethod(StringBuilder sb, object method)
    {
        var methodType = method.GetType();
        var methodName = (string)methodType.GetProperty("Name").GetValue(method);
        var httpMethodLower = ((string)methodType.GetProperty("HttpMethod").GetValue(method)).ToLowerInvariant();
        var returnType = (string)methodType.GetProperty("ReturnType").GetValue(method);
        
        var parameterList = new List<object>();
        var parameters = (System.Collections.IEnumerable)methodType.GetProperty("Parameters").GetValue(method);
        foreach (var p in parameters) parameterList.Add(p);
        
        GenerateMethodSignature(
            sb: sb,
            returnType: returnType,
            methodName: methodName,
            parameterList: parameterList);
        
        sb.AppendLine("    {");

        var hasParameters = parameterList.Count > 0;
        if (hasParameters)
            BuildRequestObject(sb: sb, parameterList: parameterList);

        GenerateHttpRequest(
            sb: sb,
            method: method,
            methodType: methodType,
            methodName: methodName,
            httpMethodLower: httpMethodLower,
            hasParameters: hasParameters,
            parameterList: parameterList);

        sb.AppendLine();
        sb.AppendLine("        response.EnsureSuccessStatusCode();");
        sb.AppendLine();

        // Handle response
        if (!string.Equals(returnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            sb.Append("        return await response.Content.ReadFromJsonAsync")
                .Append('<')
                .Append(returnType)
                .AppendLine(">()");
            sb.AppendLine("            ?? throw new InvalidOperationException(\"Response deserialization returned null\");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    private static void BuildRequestObject(StringBuilder sb, List<object> parameterList)
    {
        sb.AppendLine("        var request = new");
        sb.AppendLine("        {");

        foreach (var p in parameterList)
        {
            var pName = (string)p.GetType().GetProperty("Name").GetValue(p);
            sb.Append("            ").Append(pName.Capitalize()).Append(" = ").Append(pName).Append(',').AppendLine();
        }

        sb.AppendLine("        };");
        sb.AppendLine();
    }

    private static void GenerateMethodSignature(StringBuilder sb, string returnType, string methodName, List<object> parameterList)
    {
        sb.Append("    public async Task");
        if (!string.Equals(returnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            sb.Append('<').Append(returnType).Append('>');
        }

        sb.Append(' ').Append(methodName).Append('(');

        var paramDeclarations = new List<string>();
        
        foreach (var p in parameterList)
        {
            var pType = (string)p.GetType().GetProperty("Type").GetValue(p);
            var pName = (string)p.GetType().GetProperty("Name").GetValue(p);
            var pHasDefault = (bool)p.GetType().GetProperty("HasDefaultValue").GetValue(p);

            var declaration = $"{pType} {pName}";
            if (pHasDefault)
            {
                var pDefaultValue = p.GetType().GetProperty("DefaultValue").GetValue(p);
                declaration += $" = {FormatDefaultValue(pType, pDefaultValue)}";
            }

            paramDeclarations.Add(declaration);
        }

        sb.Append(string.Join(", ", paramDeclarations));
        sb.AppendLine(")");
    }

    private static void GenerateHttpRequest(StringBuilder sb, object method, Type methodType, string methodName, string httpMethodLower, bool hasParameters, List<object> parameterList)
    {
        var customRoute = (string)methodType.GetProperty("CustomRoute").GetValue(method);
        var routeName = customRoute ?? methodName;

        switch (httpMethodLower)
        {
            case "post" when hasParameters:
                sb.AppendLine($"        var response = await _httpClient.PostAsJsonAsync(");
                sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
                sb.AppendLine("            request);");
                break;
            case "post":
                sb.AppendLine($"        var response = await _httpClient.PostAsync(");
                sb.Append("            $\"{BaseRoute}/").Append(routeName).AppendLine("\",");
                sb.AppendLine("            null);");
                break;
            case "get" when hasParameters:
            {
                sb.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");
                foreach (var p in parameterList)
                {
                    var pName = (string)p.GetType().GetProperty("Name").GetValue(p);
                    var propertyName = char.ToUpper(pName[0], CultureInfo.InvariantCulture) + pName.Substring(1);
                    sb.Append("        queryString[\"").Append(propertyName).Append("\"] = ").Append(pName).AppendLine("?.ToString();");
                }

                sb.AppendLine($"        var response = await _httpClient.GetAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}?{{queryString}}\");");
                break;
            }
            case "get":
                sb.AppendLine($"        var response = await _httpClient.GetAsync(");
                sb.AppendLine($"            $\"{{BaseRoute}}/{routeName}\");");
                break;
            default: // PUT, DELETE, PATCH
            {
                var httpMethodUpper = httpMethodLower.ToUpperInvariant();
                sb.AppendLine("        var requestMessage = new HttpRequestMessage");
                sb.AppendLine("        {");
                sb.AppendLine($"            Method = HttpMethod.{httpMethodUpper},");
                sb.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{routeName}\", UriKind.Relative)");

                if (hasParameters)
                {
                    sb.AppendLine(",            Content = JsonContent.Create(request)");
                }

                sb.AppendLine("        };");
                sb.AppendLine("        var response = await _httpClient.SendAsync(requestMessage);");
                break;
            }
        }
    }

    private static string FormatDefaultValue(string type, object? defaultValue)
    {
        if (defaultValue == null)
        {
            return "null";
        }

        if (string.Equals(type, "string", StringComparison.OrdinalIgnoreCase))
        {
            return $"\"{defaultValue}\"";
        }

        if (string.Equals(type, "bool", StringComparison.OrdinalIgnoreCase))
        {
            return defaultValue.ToString().ToLowerInvariant();
        }

        if (type.Contains('?') && string.Equals(defaultValue.ToString(), "null", StringComparison.OrdinalIgnoreCase))
        {
            return "null";
        }

        return defaultValue.ToString();
    }
}