using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal sealed class ClientRegistrationGenerator
{
    private readonly IReadOnlyCollection<InterfaceInfo> _interfaces;
    private readonly string? _targetNamespace;
    private readonly StringBuilder _stringBuilder = new();

    private ClientRegistrationGenerator(IReadOnlyCollection<InterfaceInfo> interfaces, string? targetNamespace)
    {
        _interfaces = interfaces;
        _targetNamespace = targetNamespace;
    }

    public static string Generate(IReadOnlyCollection<InterfaceInfo> interfaces, string? targetNamespace)
    {
        if (interfaces.Count == 0)
            return string.Empty;

        return new ClientRegistrationGenerator(interfaces, targetNamespace).GenerateCore();
    }

    private string GenerateCore()
    {
        var restInterfaces = _interfaces.Where(i => i.Configuration.ApiType != ApiType.GRPC).ToList();
        var grpcInterfaces = _interfaces.Where(i => i.Configuration.ApiType == ApiType.GRPC).ToList();

        using var enumerator = _interfaces.GetEnumerator();
        enumerator.MoveNext();
        var ns = !string.IsNullOrEmpty(_targetNamespace) ? _targetNamespace : enumerator.Current.Namespace;

        AppendFileHeader(ns, grpcInterfaces.Count > 0);
        AppendMethodBody(restInterfaces, grpcInterfaces);

        return _stringBuilder.ToString();
    }

    private void AppendFileHeader(string? ns, bool hasGrpc)
    {
        var externalNamespaces = _interfaces
            .Select(i => i.Namespace)
            .Where(n => !string.Equals(n, ns, StringComparison.Ordinal) && !string.IsNullOrEmpty(n))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        _stringBuilder.AppendLine("// <auto-generated />");
        _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("using System;");
        if (hasGrpc)
        {
            _stringBuilder.AppendLine("using Grpc.Net.Client;");
            _stringBuilder.AppendLine("using Grpc.Net.Client.Web;");
            _stringBuilder.AppendLine("using System.Net.Http;");
        }
        _stringBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        if (hasGrpc)
            _stringBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");

        foreach (var externalNs in externalNamespaces)
            _stringBuilder.Append("using ").Append(externalNs).AppendLine(";");

        _stringBuilder.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            _stringBuilder.Append("namespace ").Append(ns).AppendLine(";");
            _stringBuilder.AppendLine();
        }
    }

    private void AppendMethodBody(List<InterfaceInfo> restInterfaces, List<InterfaceInfo> grpcInterfaces)
    {
        _stringBuilder.AppendLine("public static class ServerFunctionClientsRegistration");
        _stringBuilder.AppendLine("{");
        _stringBuilder.AppendLine("    public static IServiceCollection AddServerFunctionClients(");
        _stringBuilder.AppendLine("        this IServiceCollection services,");
        _stringBuilder.AppendLine("        Uri? baseAddress = null,");
        if (grpcInterfaces.Count > 0)
        {
            _stringBuilder.AppendLine("        Action<IHttpClientBuilder>? configureClient = null,");
            _stringBuilder.AppendLine("        HttpMessageHandler? innerGrpcHttpHandler = null)");
        }
        else
        {
            _stringBuilder.AppendLine("        Action<IHttpClientBuilder>? configureClient = null)");
        }
        _stringBuilder.AppendLine("    {");

        foreach (var restInterface in restInterfaces)
            AppendRestClientRegistration(restInterface.Name);

        if (grpcInterfaces.Count > 0)
            AppendGrpcClientRegistrations(grpcInterfaces);

        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        return services;");
        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        void Register(IHttpClientBuilder builder) => configureClient?.Invoke(builder);");
        _stringBuilder.AppendLine("    }");
        _stringBuilder.AppendLine("}");
    }

    private void AppendRestClientRegistration(string interfaceName)
    {
        var clientClassName = interfaceName.TrimStart('I') + "Client";

        _stringBuilder.Append("        Register(services.AddHttpClient<")
            .Append(interfaceName)
            .Append(", ")
            .Append(clientClassName)
            .AppendLine(">()")
            .AppendLine("            .ConfigureHttpClient(c => { if (baseAddress != null) c.BaseAddress = baseAddress; }));");
    }

    private void AppendGrpcClientRegistrations(List<InterfaceInfo> grpcInterfaces)
    {
        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        // gRPC channel — TryAddSingleton allows tests/advanced users to pre-register their own");
        _stringBuilder.AppendLine("        services.TryAddSingleton(sp => GrpcChannel.ForAddress(");
        _stringBuilder.AppendLine("            baseAddress ?? throw new InvalidOperationException(");
        _stringBuilder.AppendLine("                \"Provide baseAddress to AddServerFunctionClients() when gRPC services are registered.\"),");
        _stringBuilder.AppendLine("            new GrpcChannelOptions { HttpHandler = new GrpcWebHandler(innerGrpcHttpHandler ?? new HttpClientHandler()) }));");
        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        // gRPC client registrations");
        foreach (var ifaceName in grpcInterfaces.Select(i => i.Name))
        {
            _stringBuilder.Append("        services.AddTransient<")
                .Append(ifaceName)
                .Append(", ")
                .Append(ifaceName.TrimStart('I') + "GrpcClient")
                .AppendLine(">();");
        }
    }
}
