using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

/// <summary>
/// Emits a <c>__BsfConfig_{InterfaceName}</c> static class with const fields that encode
/// the resolved <see cref="ConfigurationInfo"/> for an interface.
/// <para>
/// This manifest is generated for library (shared) projects so that server/client projects
/// can recover the configuration values from compiled metadata, where the config class's
/// constructor source is unavailable (cross-compilation limitation).
/// </para>
/// </summary>
internal static class ConfigManifestGenerator
{
    /// <summary>
    /// Generates the manifest class source for the given interface.
    /// Returns <c>null</c> when the interface uses the default configuration (no manifest needed).
    /// </summary>
    public static string? Generate(InterfaceInfo interfaceInfo)
    {
        var config = interfaceInfo.Configuration;
        if (config == ConfigurationInfo.Default)
            return null;

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Config manifest — lets server/client generators read cross-project configuration from compiled metadata.");

        if (!string.IsNullOrEmpty(interfaceInfo.Namespace))
        {
            sb.AppendLine();
            sb.AppendLine($"namespace {interfaceInfo.Namespace};");
        }

        sb.AppendLine();
        sb.AppendLine("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        sb.AppendLine("[global::System.Runtime.CompilerServices.CompilerGenerated]");
        sb.AppendLine($"public static class __BsfConfig_{interfaceInfo.Name}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string __BaseRoute = \"{EscapeString(config.BaseRoute)}\";");
        sb.AppendLine($"    public const int __RouteNaming = {(int)config.RouteNaming};");
        sb.AppendLine($"    public const string __DefaultHttpMethod = \"{EscapeString(config.DefaultHttpMethod ?? string.Empty)}\";");
        sb.AppendLine($"    public const bool __GenerateProblemDetails = {BoolLiteral(config.GenerateProblemDetails)};");
        sb.AppendLine($"    public const bool __EnableResilience = {BoolLiteral(config.EnableResilience)};");
        sb.AppendLine($"    public const bool __Nullable = {BoolLiteral(config.Nullable)};");
        sb.AppendLine($"    public const string __CustomHttpClientType = \"{EscapeString(config.CustomHttpClientType ?? string.Empty)}\";");
        sb.AppendLine($"    public const int __ApiType = {(int)config.ApiType};");
        sb.AppendLine($"    public const int __CacheSeconds = {config.CacheSeconds};");
        sb.AppendLine($"    public const string __RateLimitPolicy = \"{EscapeString(config.RateLimitPolicy ?? string.Empty)}\";");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    private static string EscapeString(string value)
    {
        var sb = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            if (c == '\\') sb.Append("\\\\");
            else if (c == '"') sb.Append("\\\"");
            else sb.Append(c);
        }

        return sb.ToString();
    }
}
