using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

/// <summary>
/// Generates a code-first gRPC client proxy class from a <c>[ServerFunctionCollection]</c> interface
/// configured with <c>ApiType = ApiType.GRPC</c>.
/// <para>
/// Uses <c>protobuf-net.Grpc</c> — no <c>.proto</c> files required. The generated
/// <c>{ServiceName}GrpcClient</c> class implements the BSF interface and delegates
/// every operation to an internal gRPC contract interface.
/// </para>
/// </summary>
internal sealed class GrpcClientProxyGenerator
{
    private readonly InterfaceInfo _interfaceInfo;
    private readonly StringBuilder _stringBuilder = new();
    private readonly string _serviceName;

    private GrpcClientProxyGenerator(InterfaceInfo interfaceInfo)
    {
        _interfaceInfo = interfaceInfo;
        _serviceName = interfaceInfo.Name.TrimStart('I');
    }

    public static string Generate(InterfaceInfo interfaceInfo) =>
        new GrpcClientProxyGenerator(interfaceInfo).GenerateCore();

    private string GenerateCore()
    {
        var config = _interfaceInfo.Configuration;
        var hasStreaming = _interfaceInfo.Methods.Any(m => m.AsyncType is AsyncType.AsyncEnumerable);
        var hasCancellationToken = _interfaceInfo.Methods.Any(m => m.HasCancellationToken);

        // ── Header ──────────────────────────────────────────────────────────
        _stringBuilder.AppendLine("// <auto-generated />");
        if (config.Nullable)
            _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();

        // ── Using directives ────────────────────────────────────────────────
        _stringBuilder.AppendLine("using Grpc.Net.Client;");
        _stringBuilder.AppendLine("using ProtoBuf;");
        _stringBuilder.AppendLine("using ProtoBuf.Grpc;");
        _stringBuilder.AppendLine("using ProtoBuf.Grpc.Client;");
        if (hasStreaming)
            _stringBuilder.AppendLine("using System.Collections.Generic;");
        _stringBuilder.AppendLine("using System.ServiceModel;");
        if (hasCancellationToken || hasStreaming)
            _stringBuilder.AppendLine("using System.Threading;");
        _stringBuilder.AppendLine("using System.Threading.Tasks;");
        _stringBuilder.AppendLine();

        // ── Namespace ────────────────────────────────────────────────────────
        _stringBuilder.Append("namespace ").Append(_interfaceInfo.Namespace).AppendLine(";");
        _stringBuilder.AppendLine();

        // ── Request wrapper types ────────────────────────────────────────────
        foreach (var method in _interfaceInfo.Methods)
        {
            if (method.Parameters.Count == 0)
                continue;

            GenerateRequestType(method, config.Nullable);
            _stringBuilder.AppendLine();
        }

        // ── gRPC contract interface ──────────────────────────────────────────
        GenerateContractInterface();
        _stringBuilder.AppendLine();

        // ── Client proxy class ───────────────────────────────────────────────
        GenerateClientClass();

        return _stringBuilder.ToString();
    }

    private void GenerateRequestType(MethodInfo method, bool nullable)
    {
        var typeName = _serviceName + method.Name + "GrpcRequest";

        _stringBuilder.AppendLine("[ProtoContract]");
        _stringBuilder.Append("public sealed class ").AppendLine(typeName);
        _stringBuilder.AppendLine("{");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            var p = method.Parameters[i];
            var propName = p.Name.ToPascalCase();

            _stringBuilder.Append("    [ProtoMember(").Append(i + 1).AppendLine(")]");
            _stringBuilder.Append("    public ").Append(p.Type).Append(' ').Append(propName)
                .Append(" { get; set; }");

            if (nullable && !p.IsValueType && !p.Type.EndsWith("?", StringComparison.Ordinal))
                _stringBuilder.Append(" = default!;");

            _stringBuilder.AppendLine();
        }

        _stringBuilder.AppendLine("}");
    }

    private void GenerateContractInterface()
    {
        _stringBuilder.Append("[ServiceContract(Name = \"").Append(_serviceName).AppendLine("GrpcService\")]");
        _stringBuilder.Append("public interface I").Append(_serviceName).AppendLine("GrpcContract");
        _stringBuilder.AppendLine("{");

        foreach (var method in _interfaceInfo.Methods)
        {
            var hasParams = method.Parameters.Count > 0;
            var requestTypeName = _serviceName + method.Name + "GrpcRequest";

            var returnType = BuildReturnType(method);

            _stringBuilder.AppendLine("    [OperationContract]");
            _stringBuilder.Append("    ").Append(returnType).Append(' ').Append(method.Name).Append('(');

            if (hasParams)
                _stringBuilder.Append(requestTypeName).Append(" request, CallContext context = default");
            else
                _stringBuilder.Append("CallContext context = default");

            _stringBuilder.AppendLine(");");
        }

        _stringBuilder.AppendLine("}");
    }

    private void GenerateClientClass()
    {
        var clientClassName = _serviceName + "GrpcClient";
        var contractInterface = "I" + _serviceName + "GrpcContract";

        _stringBuilder.Append("public class ").Append(clientClassName).Append(" : ").AppendLine(_interfaceInfo.Name);
        _stringBuilder.AppendLine("{");
        _stringBuilder.Append("    private readonly ").Append(contractInterface).AppendLine(" _grpcService;");
        _stringBuilder.AppendLine();
        _stringBuilder.Append("    public ").Append(clientClassName).AppendLine("(GrpcChannel channel)");
        _stringBuilder.AppendLine("    {");
        _stringBuilder.Append("        _grpcService = channel.CreateGrpcService<").Append(contractInterface).AppendLine(">();");
        _stringBuilder.AppendLine("    }");
        _stringBuilder.AppendLine();

        foreach (var method in _interfaceInfo.Methods)
        {
            GenerateClientMethod(method);
        }

        _stringBuilder.AppendLine("}");
    }

    private void GenerateClientMethod(MethodInfo method)
    {
        var hasParams = method.Parameters.Count > 0;
        var requestTypeName = _serviceName + method.Name + "GrpcRequest";
        var returnType = BuildReturnType(method);

        // ── Method signature ─────────────────────────────────────────────────
        _stringBuilder.Append("    public ").Append(returnType).Append(' ').Append(method.Name).Append('(');

        if (hasParams)
        {
            var paramList = method.Parameters.Select(p => $"{p.Type} {p.Name}");
            _stringBuilder.Append(string.Join(", ", paramList));
            if (method.HasCancellationToken)
                _stringBuilder.Append(", CancellationToken cancellationToken = default");
        }
        else if (method.HasCancellationToken)
        {
            _stringBuilder.Append("CancellationToken cancellationToken = default");
        }

        _stringBuilder.Append(')');

        // ── Method body (expression body) ────────────────────────────────────
        if (hasParams)
        {
            // Build the request object initializer
            var propInits = method.Parameters
                .Select(p => $"{p.Name.ToPascalCase()} = {p.Name}")
                .ToList();
            var requestInit = "new " + requestTypeName + " { " + string.Join(", ", propInits) + " }";

            if (method.HasCancellationToken)
                _stringBuilder.Append(" => _grpcService.").Append(method.Name).Append('(')
                    .Append(requestInit)
                    .AppendLine(", new CallContext(cancellationToken: cancellationToken));");
            else
                _stringBuilder.Append(" => _grpcService.").Append(method.Name).Append('(')
                    .Append(requestInit)
                    .AppendLine(");");
        }
        else
        {
            if (method.HasCancellationToken)
                _stringBuilder.Append(" => _grpcService.").Append(method.Name)
                    .AppendLine("(new CallContext(cancellationToken: cancellationToken));");
            else
                _stringBuilder.Append(" => _grpcService.").Append(method.Name).AppendLine("();");
        }

        _stringBuilder.AppendLine();
    }

    private static string BuildReturnType(MethodInfo method)
    {
        var isVoid = string.Equals(method.ReturnType, "void", System.StringComparison.Ordinal);
        return method.AsyncType switch
        {
            AsyncType.Task when isVoid => "Task",
            AsyncType.Task => "Task<" + method.ReturnType + ">",
            AsyncType.ValueTask when isVoid => "ValueTask",
            AsyncType.ValueTask => "ValueTask<" + method.ReturnType + ">",
            AsyncType.AsyncEnumerable => "IAsyncEnumerable<" + method.ReturnType + ">",
            _ => method.ReturnType,
        };
    }
}
