using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

/// <summary>
/// Generates a code-first gRPC client proxy class from a <c>[ServerFunctionCollection]</c> interface
/// configured with <c>ApiType = ApiType.GRPC</c>.
/// <para>
/// Uses <c>protobuf-net.Grpc</c> — no <c>.proto</c> files required. The generated
/// <c>{ServiceName}GrpcClient</c> class implements the BSF interface and delegates
/// every operation to an internal gRPC contract interface.
/// </para>
/// </summary>
internal static class GrpcClientProxyGenerator
{
    /// <summary>
    /// Value types (and struct types) whose properties do not require a <c>= default!</c>
    /// initializer under <c>#nullable enable</c> — they are zero-initialized by the runtime.
    /// </summary>
    private static readonly HashSet<string> s_valueTypes = new(StringComparer.Ordinal)
    {
        "int", "long", "short", "byte", "uint", "ulong", "ushort", "sbyte",
        "float", "double", "decimal", "bool", "char",
        "Guid", "DateTime", "DateTimeOffset", "DateOnly", "TimeOnly", "TimeSpan",
    };

    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();
        var config = interfaceInfo.Configuration;
        var serviceName = interfaceInfo.Name.TrimStart('I');
        var hasStreaming = interfaceInfo.Methods.Any(m => m.AsyncType is AsyncType.AsyncEnumerable);
        var hasCancellationToken = interfaceInfo.Methods.Any(m => m.HasCancellationToken);

        // ── Header ──────────────────────────────────────────────────────────
        sb.AppendLine("// <auto-generated />");
        if (config.Nullable)
            sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // ── Using directives ────────────────────────────────────────────────
        sb.AppendLine("using Grpc.Net.Client;");
        sb.AppendLine("using ProtoBuf;");
        sb.AppendLine("using ProtoBuf.Grpc;");
        sb.AppendLine("using ProtoBuf.Grpc.Client;");
        if (hasStreaming)
            sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ServiceModel;");
        if (hasCancellationToken || hasStreaming)
            sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        // ── Namespace ────────────────────────────────────────────────────────
        sb.Append("namespace ").Append(interfaceInfo.Namespace).AppendLine(";");
        sb.AppendLine();

        // ── Request wrapper types ────────────────────────────────────────────
        foreach (var method in interfaceInfo.Methods)
        {
            if (method.Parameters.Count == 0)
                continue;

            GenerateRequestType(sb, serviceName, method, config.Nullable);
            sb.AppendLine();
        }

        // ── gRPC contract interface ──────────────────────────────────────────
        GenerateContractInterface(sb, serviceName, interfaceInfo);
        sb.AppendLine();

        // ── Client proxy class ───────────────────────────────────────────────
        GenerateClientClass(sb, serviceName, interfaceInfo);

        return sb.ToString();
    }

    private static void GenerateRequestType(
        StringBuilder sb,
        string serviceName,
        MethodInfo method,
        bool nullable)
    {
        var typeName = serviceName + method.Name + "GrpcRequest";

        sb.AppendLine("[ProtoContract]");
        sb.Append("public sealed class ").AppendLine(typeName);
        sb.AppendLine("{");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            var p = method.Parameters[i];
            var propName = p.Name.ToPascalCase();

            sb.Append("    [ProtoMember(").Append(i + 1).AppendLine(")]");
            sb.Append("    public ").Append(p.Type).Append(' ').Append(propName)
                .Append(" { get; set; }");

            if (nullable && NeedsNullableInitializer(p.Type))
                sb.Append(" = default!;");

            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateContractInterface(
        StringBuilder sb,
        string serviceName,
        InterfaceInfo interfaceInfo)
    {
        sb.Append("[ServiceContract(Name = \"").Append(serviceName).AppendLine("GrpcService\")]");
        sb.Append("public interface I").Append(serviceName).AppendLine("GrpcContract");
        sb.AppendLine("{");

        foreach (var method in interfaceInfo.Methods)
        {
            var hasParams = method.Parameters.Count > 0;
            var requestTypeName = serviceName + method.Name + "GrpcRequest";

            var returnType = BuildReturnType(method);

            sb.AppendLine("    [OperationContract]");
            sb.Append("    ").Append(returnType).Append(' ').Append(method.Name).Append('(');

            if (hasParams)
                sb.Append(requestTypeName).Append(" request, CallContext context = default");
            else
                sb.Append("CallContext context = default");

            sb.AppendLine(");");
        }

        sb.AppendLine("}");
    }

    private static void GenerateClientClass(
        StringBuilder sb,
        string serviceName,
        InterfaceInfo interfaceInfo)
    {
        var clientClassName = serviceName + "GrpcClient";
        var contractInterface = "I" + serviceName + "GrpcContract";

        sb.Append("public class ").Append(clientClassName).Append(" : ").AppendLine(interfaceInfo.Name);
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(contractInterface).AppendLine(" _grpcService;");
        sb.AppendLine();
        sb.Append("    public ").Append(clientClassName).AppendLine("(GrpcChannel channel)");
        sb.AppendLine("    {");
        sb.Append("        _grpcService = channel.CreateGrpcService<").Append(contractInterface).AppendLine(">();");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
        {
            GenerateClientMethod(sb, serviceName, method);
        }

        sb.AppendLine("}");
    }

    private static void GenerateClientMethod(
        StringBuilder sb,
        string serviceName,
        MethodInfo method)
    {
        var hasParams = method.Parameters.Count > 0;
        var requestTypeName = serviceName + method.Name + "GrpcRequest";
        var returnType = BuildReturnType(method);

        // ── Method signature ─────────────────────────────────────────────────
        sb.Append("    public ").Append(returnType).Append(' ').Append(method.Name).Append('(');

        if (hasParams)
        {
            var paramList = method.Parameters.Select(p => $"{p.Type} {p.Name}");
            sb.Append(string.Join(", ", paramList));
            if (method.HasCancellationToken)
                sb.Append(", CancellationToken cancellationToken = default");
        }
        else if (method.HasCancellationToken)
        {
            sb.Append("CancellationToken cancellationToken = default");
        }

        sb.Append(')');

        // ── Method body (expression body) ────────────────────────────────────
        if (hasParams)
        {
            // Build the request object initializer
            var propInits = method.Parameters
                .Select(p => $"{p.Name.ToPascalCase()} = {p.Name}")
                .ToList();
            var requestInit = "new " + requestTypeName + " { " + string.Join(", ", propInits) + " }";

            if (method.HasCancellationToken)
                sb.Append(" => _grpcService.").Append(method.Name).Append('(')
                    .Append(requestInit)
                    .AppendLine(", new CallContext(cancellationToken: cancellationToken));");
            else
                sb.Append(" => _grpcService.").Append(method.Name).Append('(')
                    .Append(requestInit)
                    .AppendLine(");");
        }
        else
        {
            if (method.HasCancellationToken)
                sb.Append(" => _grpcService.").Append(method.Name)
                    .AppendLine("(new CallContext(cancellationToken: cancellationToken));");
            else
                sb.Append(" => _grpcService.").Append(method.Name).AppendLine("();");
        }

        sb.AppendLine();
    }

    private static string BuildReturnType(MethodInfo method)
    {
        var isVoid = string.Equals(method.ReturnType, "void", System.StringComparison.Ordinal);
        return method.AsyncType switch
        {
            AsyncType.Task when isVoid => "Task",
            AsyncType.Task => "Task<" + method.ReturnType + ">",
            AsyncType.ValueTask when isVoid => "ValueTask",
            AsyncType.ValueTask => "ValueTask<" + method.ReturnType + ">",
            AsyncType.AsyncEnumerable => "IAsyncEnumerable<" + method.ReturnType + ">",
            _ => method.ReturnType,
        };
    }

    /// <summary>
    /// Returns <c>true</c> when a property of the given type requires <c>= default!</c>
    /// to suppress CS8618 under <c>#nullable enable</c>.
    /// </summary>
    private static bool NeedsNullableInitializer(string typeName)
    {
        if (typeName.EndsWith("?", System.StringComparison.Ordinal))
            return false;

        if (s_valueTypes.Contains(typeName))
            return false;

        return true;
    }
}
