using System.Collections.Generic;
using System.Linq;
using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

/// <summary>
/// Generates a code-first gRPC service class from a <c>[ServerFunctionCollection]</c> interface
/// configured with <c>ApiType = ApiType.GRPC</c>.
/// <para>
/// Uses <c>protobuf-net.Grpc</c> — no <c>.proto</c> files required. The generated
/// <c>{Interface}GrpcService</c> class is decorated with <c>[ServiceContract]</c> and delegates
/// every operation to the injected <c>IXxxService</c>.
/// </para>
/// <para>
/// Each method with ≥1 parameter gets a generated <c>[ProtoContract]</c> request wrapper type
/// (<c>{ServiceName}{MethodName}GrpcRequest</c>) because gRPC transport requires a single
/// message per operation. Methods with no parameters use only a <c>CallContext</c> argument.
/// </para>
/// </summary>
internal static class GrpcServerGenerator
{
    /// <summary>
    /// Value types (and struct types) whose properties do not require a <c>= default!</c>
    /// initializer under <c>#nullable enable</c> — they are zero-initialized by the runtime.
    /// </summary>
    private static readonly HashSet<string> s_valueTypes = new(StringComparer.Ordinal)
    {
        "int", "long", "short", "byte", "uint", "ulong", "ushort", "sbyte",
        "float", "double", "decimal", "bool", "char",
        "Guid", "DateTime", "DateTimeOffset", "DateOnly", "TimeOnly", "TimeSpan",
    };

    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();
        var config = interfaceInfo.Configuration;
        var serviceName = interfaceInfo.Name.TrimStart('I');
        var hasStreaming = interfaceInfo.Methods.Any(m => m.AsyncType is AsyncType.AsyncEnumerable);

        // ── Header ──────────────────────────────────────────────────────────
        sb.AppendLine("// <auto-generated />");
        if (config.Nullable)
            sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // ── Using directives ────────────────────────────────────────────────
        sb.AppendLine("using ProtoBuf;");
        sb.AppendLine("using ProtoBuf.Grpc;");
        sb.AppendLine("using ProtoBuf.Grpc.Configuration;");
        if (hasStreaming)
            sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();

        // ── Namespace ────────────────────────────────────────────────────────
        sb.Append("namespace ").Append(interfaceInfo.Namespace).AppendLine(";");
        sb.AppendLine();

        // ── Request wrapper types ────────────────────────────────────────────
        foreach (var method in interfaceInfo.Methods)
        {
            if (method.Parameters.Count == 0)
                continue;

            GenerateRequestType(sb, serviceName, method, config.Nullable);
            sb.AppendLine();
        }

        // ── Service class ────────────────────────────────────────────────────
        var serviceClassName = serviceName + "GrpcService";
        sb.AppendLine("[ServiceContract]");
        sb.Append("public sealed class ").AppendLine(serviceClassName);
        sb.AppendLine("{");
        sb.Append("    private readonly ").Append(interfaceInfo.Name).AppendLine(" _service;");
        sb.AppendLine();
        sb.Append("    public ").Append(serviceClassName).Append('(')
            .Append(interfaceInfo.Name).AppendLine(" service) => _service = service;");
        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
        {
            GenerateMethod(sb, serviceName, method);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateRequestType(
        StringBuilder sb,
        string serviceName,
        MethodInfo method,
        bool nullable)
    {
        var typeName = serviceName + method.Name + "GrpcRequest";

        sb.AppendLine("[ProtoContract]");
        sb.Append("public sealed class ").AppendLine(typeName);
        sb.AppendLine("{");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            var p = method.Parameters[i];
            var propName = p.Name.ToPascalCase();

            sb.Append("    [ProtoMember(").Append(i + 1).AppendLine(")]");
            sb.Append("    public ").Append(p.Type).Append(' ').Append(propName)
                .Append(" { get; set; }");

            // Non-nullable reference type properties need an initializer under #nullable enable
            // to avoid CS8618 (uninitialized non-nullable property).
            if (nullable && NeedsNullableInitializer(p.Type))
                sb.Append(" = default!;");

            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateMethod(StringBuilder sb, string serviceName, MethodInfo method)
    {
        var hasParams = method.Parameters.Count > 0;
        var requestTypeName = serviceName + method.Name + "GrpcRequest";

        // ── Build the parameter signature ────────────────────────────────────
        string paramSignature;
        if (hasParams)
            paramSignature = requestTypeName + " request, CallContext context = default";
        else
            paramSignature = "CallContext context = default";

        // ── Build the delegate call argument list ────────────────────────────
        var callArgParts = new List<string>(method.Parameters.Count + 1);
        foreach (var p in method.Parameters)
            callArgParts.Add("request." + p.Name.ToPascalCase());
        if (method.HasCancellationToken)
            callArgParts.Add("context.CancellationToken");
        var callArgs = string.Join(", ", callArgParts);

        // ── Build the return type ────────────────────────────────────────────
        var isVoid = string.Equals(method.ReturnType, "void", System.StringComparison.Ordinal);
        var returnType = method.AsyncType switch
        {
            AsyncType.Task when isVoid => "Task",
            AsyncType.Task => "Task<" + method.ReturnType + ">",
            AsyncType.ValueTask when isVoid => "ValueTask",
            AsyncType.ValueTask => "ValueTask<" + method.ReturnType + ">",
            AsyncType.AsyncEnumerable => "IAsyncEnumerable<" + method.ReturnType + ">",
            _ => method.ReturnType,
        };

        sb.AppendLine("    [OperationContract]");
        sb.Append("    public ").Append(returnType).Append(' ').Append(method.Name)
            .Append('(').Append(paramSignature).AppendLine(")");
        sb.Append("        => _service.").Append(method.Name).Append('(').Append(callArgs)
            .AppendLine(");");
        sb.AppendLine();
    }

    /// <summary>
    /// Returns <c>true</c> when a property of the given type requires <c>= default!</c>
    /// to suppress CS8618 under <c>#nullable enable</c>.
    /// Value types and nullable-marked types (<c>?</c> suffix) are self-initializing.
    /// </summary>
    private static bool NeedsNullableInitializer(string typeName)
    {
        // Already nullable-annotated (string?, MyClass?, int?) — no initializer needed
        if (typeName.EndsWith("?", System.StringComparison.Ordinal))
            return false;

        // Known value types / structs are zero-initialized by the runtime
        if (s_valueTypes.Contains(typeName))
            return false;

        // Everything else is a reference type that needs an initializer
        return true;
    }
}
