using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

/// <summary>
/// Generates a code-first gRPC service class from a <c>[ServerFunctionCollection]</c> interface
/// configured with <c>ApiType = ApiType.GRPC</c>.
/// <para>
/// Uses <c>protobuf-net.Grpc</c> — no <c>.proto</c> files required. The generated
/// <c>{Interface}GrpcService</c> class is decorated with <c>[ServiceContract]</c> and delegates
/// every operation to the injected <c>IXxxService</c>.
/// </para>
/// <para>
/// Each method with ≥1 parameter gets a generated <c>[ProtoContract]</c> request wrapper type
/// (<c>{ServiceName}{MethodName}GrpcRequest</c>) because gRPC transport requires a single
/// message per operation. Methods with no parameters use only a <c>CallContext</c> argument.
/// </para>
/// </summary>
internal sealed class GrpcServerGenerator
{
    private readonly InterfaceInfo _interfaceInfo;
    private readonly bool _emitRequestTypes;
    private readonly StringBuilder _stringBuilder = new();
    private readonly string _serviceName;

    private GrpcServerGenerator(InterfaceInfo interfaceInfo, bool emitRequestTypes)
    {
        _interfaceInfo = interfaceInfo;
        _emitRequestTypes = emitRequestTypes;
        _serviceName = interfaceInfo.Name.TrimStart('I');
    }

    /// <param name="interfaceInfo">The interface to generate a service class for.</param>
    /// <param name="emitRequestTypes">
    /// When <see langword="true"/> (default), the request wrapper types are emitted alongside
    /// the service class.  Pass <see langword="false"/> when the interface is defined in a
    /// referenced assembly: the request types were already generated in that assembly and
    /// re-emitting them would cause CS0436 duplicate-type conflicts.
    /// </param>
    public static string Generate(InterfaceInfo interfaceInfo, bool emitRequestTypes = true) =>
        new GrpcServerGenerator(interfaceInfo, emitRequestTypes).GenerateCore();

    private string GenerateCore()
    {
        var config = _interfaceInfo.Configuration;
        var hasStreaming = _interfaceInfo.Methods.Any(m => m.AsyncType is AsyncType.AsyncEnumerable);

        // ── Determine which namespace to emit and which to import ────────────
        // The service class always lives in the server project's namespace
        // (interfaceInfo.Namespace is where the interface was declared).
        var serviceNs = _interfaceInfo.Namespace;

        // ── Header ──────────────────────────────────────────────────────────
        _stringBuilder.AppendLine("// <auto-generated />");
        if (config.Nullable)
            _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();

        // ── Using directives ────────────────────────────────────────────────
        if (!_emitRequestTypes && !string.IsNullOrEmpty(serviceNs))
            _stringBuilder.Append("using ").Append(serviceNs).AppendLine(";");
        if (_emitRequestTypes)
            _stringBuilder.AppendLine("using ProtoBuf;");
        _stringBuilder.AppendLine("using ProtoBuf.Grpc;");
        if (hasStreaming)
            _stringBuilder.AppendLine("using System.Collections.Generic;");
        if (_emitRequestTypes)
            _stringBuilder.AppendLine("using System.ServiceModel;");
        _stringBuilder.AppendLine("using System.Threading.Tasks;");
        _stringBuilder.AppendLine();

        // ── Namespace ────────────────────────────────────────────────────────
        _stringBuilder.Append("namespace ").Append(serviceNs).AppendLine(";");
        _stringBuilder.AppendLine();

        if (_emitRequestTypes)
            AppendRequestTypes();

        AppendServiceClass();

        return _stringBuilder.ToString();
    }

    private void AppendRequestTypes()
    {
        foreach (var method in _interfaceInfo.Methods)
        {
            if (method.Parameters.Count == 0)
                continue;

            GenerateRequestType(method);
            _stringBuilder.AppendLine();
        }
    }

    private void AppendServiceClass()
    {
        var serviceClassName = _serviceName + "GrpcService";
        var contractInterface = "I" + _serviceName + "GrpcContract";
        // The service class implements the contract interface (which carries [ServiceContract]).
        // This ensures protobuf-net.Grpc uses the same service name on client and server.
        if (_interfaceInfo.RequireAuthorization)
            _stringBuilder.AppendLine("[global::Microsoft.AspNetCore.Authorization.Authorize]");
        _stringBuilder.Append("public sealed class ").Append(serviceClassName)
            .Append(" : ").AppendLine(contractInterface);
        _stringBuilder.AppendLine("{");
        _stringBuilder.Append("    private readonly ").Append(_interfaceInfo.Name).AppendLine(" _service;");
        _stringBuilder.AppendLine();
        _stringBuilder.Append("    public ").Append(serviceClassName).Append('(')
            .Append(_interfaceInfo.Name).AppendLine(" service) => _service = service;");
        _stringBuilder.AppendLine();

        foreach (var method in _interfaceInfo.Methods)
        {
            GenerateMethod(method, _interfaceInfo.RequireAuthorization);
        }

        _stringBuilder.AppendLine("}");
    }

    private void GenerateRequestType(MethodInfo method)
    {
        var typeName = _serviceName + method.Name + "GrpcRequest";
        var nullable = _interfaceInfo.Configuration.Nullable;

        _stringBuilder.AppendLine("[ProtoContract]");
        _stringBuilder.Append("public sealed class ").AppendLine(typeName);
        _stringBuilder.AppendLine("{");

        for (var i = 0; i < method.Parameters.Count; i++)
        {
            var p = method.Parameters[i];
            var propName = p.Name.ToPascalCase();

            _stringBuilder.Append("    [ProtoMember(").Append(i + 1).AppendLine(")]");
            _stringBuilder.Append("    public ").Append(p.Type).Append(' ').Append(propName)
                .Append(" { get; set; }");

            // Non-nullable reference type properties need an initializer under #nullable enable
            // to avoid CS8618 (uninitialized non-nullable property).
            if (nullable && !p.IsValueType && !p.Type.EndsWith("?", StringComparison.Ordinal))
                _stringBuilder.Append(" = default!;");

            _stringBuilder.AppendLine();
        }

        _stringBuilder.AppendLine("}");
    }

    private void GenerateMethod(MethodInfo method, bool interfaceRequiresAuth = false)
    {
        var hasParams = method.Parameters.Count > 0;
        var requestTypeName = _serviceName + method.Name + "GrpcRequest";

        // ── Authorization attributes ─────────────────────────────────────────
        if (method.Policy != null)
            _stringBuilder.Append("    [global::Microsoft.AspNetCore.Authorization.Authorize(Policy = \"")
                .Append(method.Policy.EscapeStringLiteral())
                .AppendLine("\")]");
        if (method.Roles != null)
            _stringBuilder.Append("    [global::Microsoft.AspNetCore.Authorization.Authorize(Roles = \"")
                .Append(method.Roles.EscapeStringLiteral())
                .AppendLine("\")]");
        if (method.RequireAuthorization && !interfaceRequiresAuth && method.Policy == null && method.Roles == null)
            _stringBuilder.AppendLine("    [global::Microsoft.AspNetCore.Authorization.Authorize]");

        // ── Build the parameter signature ────────────────────────────────────
        string paramSignature;
        if (hasParams)
            paramSignature = requestTypeName + " request, CallContext context = default";
        else
            paramSignature = "CallContext context = default";

        // ── Build the delegate call argument list ────────────────────────────
        var callArgParts = new List<string>(method.Parameters.Count + 1);
        foreach (var p in method.Parameters)
            callArgParts.Add("request." + p.Name.ToPascalCase());
        if (method.HasCancellationToken)
            callArgParts.Add("context.CancellationToken");
        var callArgs = string.Join(", ", callArgParts);

        // ── Build the return type ────────────────────────────────────────────
        var isVoid = string.Equals(method.ReturnType, "void", System.StringComparison.Ordinal);
        var returnType = method.AsyncType switch
        {
            AsyncType.Task when isVoid => "Task",
            AsyncType.Task => "Task<" + method.ReturnType + ">",
            AsyncType.ValueTask when isVoid => "ValueTask",
            AsyncType.ValueTask => "ValueTask<" + method.ReturnType + ">",
            AsyncType.AsyncEnumerable => "IAsyncEnumerable<" + method.ReturnType + ">",
            _ => method.ReturnType,
        };

        _stringBuilder.Append("    public ").Append(returnType).Append(' ').Append(method.Name)
            .Append('(').Append(paramSignature).AppendLine(")");
        _stringBuilder.Append("        => _service.").Append(method.Name).Append('(').Append(callArgs)
            .AppendLine(");");
        _stringBuilder.AppendLine();
    }
}
