using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;

namespace BlazorServerFunctions.Generator.Generators;

internal sealed class RestServerEndpointGenerator
{
    private readonly InterfaceInfo _interfaceInfo;
    private readonly string? _targetNamespace;
    private readonly bool _hasOpenApiPackage;
    private readonly StringBuilder _stringBuilder = new();

    private RestServerEndpointGenerator(InterfaceInfo interfaceInfo, string? targetNamespace, bool hasOpenApiPackage)
    {
        _interfaceInfo = interfaceInfo;
        _targetNamespace = targetNamespace;
        _hasOpenApiPackage = hasOpenApiPackage;
    }

    public static string Generate(InterfaceInfo interfaceInfo, string? targetNamespace, bool hasOpenApiPackage = false) =>
        new RestServerEndpointGenerator(interfaceInfo, targetNamespace, hasOpenApiPackage).GenerateCore();

    private string GenerateCore()
    {
        var effectiveNamespace = !string.IsNullOrEmpty(_targetNamespace) ? _targetNamespace : _interfaceInfo.Namespace;

        // Add interface namespace as a using when it differs from the target namespace
        var interfaceUsingNs = !string.IsNullOrEmpty(_interfaceInfo.Namespace) &&
                               !string.Equals(_interfaceInfo.Namespace, effectiveNamespace, StringComparison.Ordinal)
            ? _interfaceInfo.Namespace
            : null;

        var hasAuthorization = _interfaceInfo.RequireAuthorization || _interfaceInfo.Methods.Any(m => m.RequireAuthorization || m.Policy != null || m.Roles != null);
        var hasCancellationToken = _interfaceInfo.Methods.Any(m => m.HasCancellationToken);
        var hasCaching = _interfaceInfo.Methods.Any(m => m.CacheSeconds > 0);
        var hasRateLimiting = _interfaceInfo.Methods.Any(m => m.RateLimitPolicy != null);
        var hasAntiForgery = _interfaceInfo.Methods.Any(m => m.RequireAntiForgery);

        GenerateFileHeader(_interfaceInfo.Configuration.Nullable);
        GenerateUsingDirectives(hasAuthorization, hasCancellationToken, hasCaching, hasRateLimiting, hasAntiForgery, interfaceUsingNs);

        if (!string.IsNullOrEmpty(effectiveNamespace))
        {
            _stringBuilder.Append("namespace ").Append(effectiveNamespace).AppendLine(";");
            _stringBuilder.AppendLine();
        }

        _stringBuilder.Append("internal static class ").Append(_interfaceInfo.Name).AppendLine("ServerExtensions");
        _stringBuilder.AppendLine("{");

        GenerateMapEndpointsMethod();
        GenerateRequestDtos();

        _stringBuilder.AppendLine("}");

        return _stringBuilder.ToString();
    }

    private void GenerateFileHeader(bool nullable)
    {
        _stringBuilder.AppendLine("// <auto-generated />");
        if (nullable)
            _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();
    }

    private void GenerateUsingDirectives(bool hasAuthorization, bool hasCancellationToken, bool hasCaching, bool hasRateLimiting, bool hasAntiForgery, string? additionalNamespace)
    {
        if (hasAntiForgery)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.Antiforgery;");
        if (hasAuthorization)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.Authorization;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Builder;");
        if (_hasOpenApiPackage)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.OpenApi;");
        if (hasCaching)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.OutputCaching;");
        if (hasRateLimiting)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.RateLimiting;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Routing;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Http;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Mvc;");
        _stringBuilder.AppendLine("using System.Text.Json;");
        if (hasCancellationToken)
            _stringBuilder.AppendLine("using System.Threading;");
        if (!string.IsNullOrEmpty(additionalNamespace))
            _stringBuilder.Append("using ").Append(additionalNamespace).AppendLine(";");
        _stringBuilder.AppendLine();
    }

    private void GenerateMapEndpointsMethod()
    {
        var baseRoute = $"/{_interfaceInfo.Configuration.BaseRoute.TrimStart('/')}/{_interfaceInfo.RoutePrefix}";
        var routeNaming = _interfaceInfo.Configuration.RouteNaming;

        _stringBuilder.Append("    internal static IEndpointRouteBuilder Map")
            .Append(_interfaceInfo.Name)
            .AppendLine("Endpoints(");
        _stringBuilder.AppendLine("        this IEndpointRouteBuilder endpoints)");
        _stringBuilder.AppendLine("    {");
        _stringBuilder.Append("        var group = endpoints.MapGroup(\"")
            .Append(baseRoute)
            .AppendLine("\");");

        if (_interfaceInfo.RequireAuthorization)
            _stringBuilder.AppendLine("        group.RequireAuthorization();");

        if (_interfaceInfo.CorsPolicy != null)
            _stringBuilder.Append("        group.RequireCors(\"")
              .Append(_interfaceInfo.CorsPolicy.EscapeStringLiteral())
              .AppendLine("\");");

        _stringBuilder.AppendLine();

        foreach (var method in _interfaceInfo.Methods)
        {
            GenerateEndpoint(method, routeNaming);
        }

        _stringBuilder.AppendLine("        return endpoints;");
        _stringBuilder.AppendLine("    }");
    }

    private void GenerateEndpoint(MethodInfo method, RouteNaming routeNaming)
    {
        // When the user specified an explicit Route, use it verbatim (no naming transformation).
        // ApplyRouteNaming is only applied to auto-derived method names.
        var routeSegment = method.CustomRoute ?? method.Name.ApplyRouteNaming(routeNaming);

        var routeParams = method.Parameters.Where(static p => p.IsRouteParameter).ToList();
        var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();
        var httpMethod = method.HttpMethod.ToString().ToPascalCase();

        _stringBuilder.Append("        group.Map").Append(httpMethod).Append("(\"/").Append(routeSegment).AppendLine("\",");

        var asyncKeyword = method.AsyncType is AsyncType.Task or AsyncType.ValueTask ? "async " : string.Empty;
        _stringBuilder.Append($"            {asyncKeyword}(");

        GenerateLambdaParameters(method, routeParams, nonRouteParams);

        _stringBuilder.AppendLine(") =>");
        _stringBuilder.AppendLine("            {");

        GenerateServiceCall(method);

        if (method.AsyncType is not AsyncType.AsyncEnumerable)
            GenerateResultReturn(method.ReturnType);

        _stringBuilder.AppendLine("            })");

        GenerateFluentChain(method);

        _stringBuilder.AppendLine();
    }

    private void GenerateFluentChain(MethodInfo method)
    {
        var config = _interfaceInfo.Configuration;
        var interfaceRequiresAuth = _interfaceInfo.RequireAuthorization;
        var interfaceName = _interfaceInfo.Name;

        var chain = new List<string>
        {
            $".WithName(\"{interfaceName}_{method.Name}\")",
            $".WithTags(\"{DeriveTag(interfaceName)}\")"
        };

        if (method.AsyncType is not AsyncType.AsyncEnumerable)
        {
            chain.Add(string.Equals(method.ReturnType, "void", StringComparison.Ordinal)
                ? ".Produces(StatusCodes.Status200OK)"
                : $".Produces<{method.ReturnType}>(StatusCodes.Status200OK)");

            if (config.GenerateProblemDetails)
                chain.Add(".ProducesProblem(StatusCodes.Status500InternalServerError)");
        }

        if (_hasOpenApiPackage)
            chain.Add(".WithOpenApi()");

        if (method.CacheSeconds > 0)
            chain.Add($".CacheOutput(p => p.Expire(System.TimeSpan.FromSeconds({method.CacheSeconds})))");

        if (method.RateLimitPolicy != null)
            chain.Add($".RequireRateLimiting(\"{method.RateLimitPolicy.EscapeStringLiteral()}\")");

        if (method.Policy != null)
            chain.Add($".RequireAuthorization(\"{method.Policy.EscapeStringLiteral()}\")");
        else if (method.RequireAuthorization && !interfaceRequiresAuth)
            chain.Add(".RequireAuthorization()");

        if (method.Roles != null)
            chain.Add($".RequireAuthorization(new AuthorizeAttribute {{ Roles = \"{method.Roles.EscapeStringLiteral()}\" }})");

        if (method.RequireAntiForgery)
            chain.Add(".WithMetadata(new RequireAntiforgeryTokenAttribute())");

        foreach (var filter in method.Filters)
            chain.Add($".AddEndpointFilter<{filter}>()");

        // File upload endpoints must opt out of anti-forgery validation (which is enforced automatically
        // when UseAntiforgery() middleware is active). Users who explicitly need anti-forgery on an upload
        // endpoint can set RequireAntiForgery = true, which adds RequireAntiforgeryTokenAttribute instead.
        bool hasFileParams = method.Parameters.Any(static p => p.FileKind != FileKind.None);
        if (hasFileParams && !method.RequireAntiForgery)
            chain.Add(".DisableAntiforgery()");

        for (int i = 0; i < chain.Count; i++)
        {
            _stringBuilder.Append("            ").Append(chain[i]);
            _stringBuilder.AppendLine(i == chain.Count - 1 ? ";" : "");
        }
    }

    private static string DeriveTag(string interfaceName) =>
        interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;

    private void GenerateLambdaParameters(
        MethodInfo method,
        List<ParameterInfo> routeParams,
        List<ParameterInfo> nonRouteParams)
    {
        // Route-bound params appear first as typed lambda arguments
        foreach (var rp in routeParams)
        {
            _stringBuilder.Append(rp.Type).Append(' ').Append(rp.Name).Append(", ");
        }

        bool hasFileParams = nonRouteParams.Any(static p => p.FileKind != FileKind.None);

        if (hasFileParams)
        {
            // File upload methods: list all non-route params inline with per-param binding attributes.
            // IFormFile / IFormFileCollection auto-bind from multipart form (no attribute needed).
            // Regular params need [FromForm] to bind from form fields instead of query/body.
            foreach (var p in nonRouteParams)
            {
                var (paramType, attribute) = p.FileKind switch
                {
                    FileKind.Stream => ("IFormFile", string.Empty),
                    FileKind.FormFile => ("IFormFile", string.Empty),
                    FileKind.FormFileCollection => ("IFormFileCollection", string.Empty),
                    _ => (p.Type, "[FromForm] "),
                };
                _stringBuilder.Append(attribute).Append(paramType).Append(' ').Append(p.Name).Append(", ");
            }
        }
        else if (nonRouteParams.Count > 0)
        {
            // Regular methods: bundle non-route params into a DTO
            var bindingAttribute = method.HttpMethod is HttpMethod.Get or HttpMethod.Delete
                ? "[AsParameters]"
                : "[FromBody]";

            _stringBuilder.Append(bindingAttribute).Append(' ')
                .Append(method.Name)
                .Append("Request request, ");
        }

        _stringBuilder.Append(_interfaceInfo.Name).Append(" service");

        if (method.HasCancellationToken)
            _stringBuilder.Append(", CancellationToken cancellationToken");
    }

    private void GenerateServiceCall(MethodInfo method)
    {
        _stringBuilder.Append("                ");

        // Streaming: return the IAsyncEnumerable<T> directly — ASP.NET Core handles chunked streaming.
        if (method.AsyncType is AsyncType.AsyncEnumerable)
        {
            _stringBuilder.Append("return ");
        }
        else
        {
            if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
                _stringBuilder.Append("var result = ");

            if (method.AsyncType is not AsyncType.None)
                _stringBuilder.Append("await ");
        }

        _stringBuilder.Append("service.").Append(method.Name).Append('(');

        if (method.Parameters.Count > 0)
        {
            bool hasFileParams = method.Parameters.Any(static p => p.FileKind != FileKind.None);

            var paramList = method.Parameters.Select(p =>
            {
                if (p.IsRouteParameter)
                    return p.Name;

                if (!hasFileParams)
                    return $"request.{p.Name.ToPascalCase()}";

                // File upload method: params are bound inline, not via request DTO.
                // Stream params are received as IFormFile on the server — extract via OpenReadStream().
                return p.FileKind == FileKind.Stream
                    ? $"{p.Name}.OpenReadStream()"
                    : p.Name;
            });

            _stringBuilder.Append(string.Join(", ", paramList));

            if (method.HasCancellationToken)
                _stringBuilder.Append(", cancellationToken");
        }
        else if (method.HasCancellationToken)
        {
            _stringBuilder.Append("cancellationToken");
        }

        _stringBuilder.AppendLine(");");
    }

    private void GenerateResultReturn(string returnType)
    {
        if (!string.Equals(returnType, "void", StringComparison.Ordinal))
        {
            _stringBuilder.AppendLine("                return Results.Ok(result);");
        }
        else
        {
            _stringBuilder.AppendLine("                return Results.Ok();");
        }
    }

    private void GenerateRequestDtos()
    {
        foreach (var method in _interfaceInfo.Methods)
        {
            var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();
            // File upload methods use inline lambda parameters — no DTO record needed.
            bool hasFileParams = nonRouteParams.Any(static p => p.FileKind != FileKind.None);
            if (nonRouteParams.Count > 0 && !hasFileParams)
            {
                GenerateRequestDto(method, nonRouteParams);
            }
        }
    }

    private void GenerateRequestDto(MethodInfo method, List<ParameterInfo> nonRouteParams)
    {
        _stringBuilder.AppendLine();
        _stringBuilder.Append("    private record ")
            .Append(method.Name)
            .Append("Request(");

        var properties = nonRouteParams
            .Select(p => $"{p.Type} {p.Name.ToPascalCase()}");

        _stringBuilder.Append(string.Join(", ", properties));
        _stringBuilder.AppendLine(");");
    }
}
