using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;
using RouteNaming = BlazorServerFunctions.Generator.Models.RouteNaming;

namespace BlazorServerFunctions.Generator.Generators;

internal sealed class RestServerEndpointGenerator
{
    private readonly InterfaceInfo _interfaceInfo;
    private readonly string? _targetNamespace;
    private readonly bool _hasOpenApiPackage;
    private readonly StringBuilder _stringBuilder = new();

    private RestServerEndpointGenerator(InterfaceInfo interfaceInfo, string? targetNamespace, bool hasOpenApiPackage)
    {
        _interfaceInfo = interfaceInfo;
        _targetNamespace = targetNamespace;
        _hasOpenApiPackage = hasOpenApiPackage;
    }

    public static string Generate(InterfaceInfo interfaceInfo, string? targetNamespace, bool hasOpenApiPackage = false) =>
        new RestServerEndpointGenerator(interfaceInfo, targetNamespace, hasOpenApiPackage).GenerateCore();

    private string GenerateCore()
    {
        var effectiveNamespace = !string.IsNullOrEmpty(_targetNamespace) ? _targetNamespace : _interfaceInfo.Namespace;

        // Add interface namespace as a using when it differs from the target namespace
        var interfaceUsingNs = !string.IsNullOrEmpty(_interfaceInfo.Namespace) &&
                               !string.Equals(_interfaceInfo.Namespace, effectiveNamespace, StringComparison.Ordinal)
            ? _interfaceInfo.Namespace
            : null;

        var hasAuthorization = _interfaceInfo.RequireAuthorization || _interfaceInfo.Methods.Any(m => m.RequireAuthorization || m.Policy != null || m.Roles != null);
        var hasCancellationToken = _interfaceInfo.Methods.Any(m => m.HasCancellationToken);
        var hasCaching = _interfaceInfo.Methods.Any(m => m.CacheSeconds > 0);
        var hasRateLimiting = _interfaceInfo.Methods.Any(m => m.RateLimitPolicy != null);
        var hasAntiForgery = _interfaceInfo.Methods.Any(m => m.RequireAntiForgery);

        GenerateFileHeader(_interfaceInfo.Configuration.Nullable);
        GenerateUsingDirectives(hasAuthorization, hasCancellationToken, hasCaching, hasRateLimiting, hasAntiForgery, interfaceUsingNs);

        if (!string.IsNullOrEmpty(effectiveNamespace))
        {
            _stringBuilder.Append("namespace ").Append(effectiveNamespace).AppendLine(";");
            _stringBuilder.AppendLine();
        }

        _stringBuilder.Append("internal static class ").Append(_interfaceInfo.Name).AppendLine("ServerExtensions");
        _stringBuilder.AppendLine("{");

        GenerateMapEndpointsMethod();
        GenerateRequestDtos();

        _stringBuilder.AppendLine("}");

        return _stringBuilder.ToString();
    }

    private void GenerateFileHeader(bool nullable)
    {
        _stringBuilder.AppendLine("// <auto-generated />");
        if (nullable)
            _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();
    }

    private void GenerateUsingDirectives(bool hasAuthorization, bool hasCancellationToken, bool hasCaching, bool hasRateLimiting, bool hasAntiForgery, string? additionalNamespace)
    {
        if (hasAntiForgery)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.Antiforgery;");
        if (hasAuthorization)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.Authorization;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Builder;");
        if (_hasOpenApiPackage)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.OpenApi;");
        if (hasCaching)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.OutputCaching;");
        if (hasRateLimiting)
            _stringBuilder.AppendLine("using Microsoft.AspNetCore.RateLimiting;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Routing;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Http;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Http.HttpResults;");
        _stringBuilder.AppendLine("using Microsoft.AspNetCore.Mvc;");
        _stringBuilder.AppendLine("using System.Text.Json;");
        _stringBuilder.AppendLine("using System.Threading.Tasks;");
        if (hasCancellationToken)
            _stringBuilder.AppendLine("using System.Threading;");
        if (!string.IsNullOrEmpty(additionalNamespace))
            _stringBuilder.Append("using ").Append(additionalNamespace).AppendLine(";");
        _stringBuilder.AppendLine();
    }

    private void GenerateMapEndpointsMethod()
    {
        var baseRoute = $"/{_interfaceInfo.Configuration.BaseRoute.TrimStart('/')}/{_interfaceInfo.RoutePrefix}";
        var routeNaming = _interfaceInfo.Configuration.RouteNaming;

        _stringBuilder.Append("    internal static IEndpointRouteBuilder Map")
            .Append(_interfaceInfo.Name)
            .AppendLine("Endpoints(");
        _stringBuilder.AppendLine("        this IEndpointRouteBuilder endpoints)");
        _stringBuilder.AppendLine("    {");
        _stringBuilder.Append("        var group = endpoints.MapGroup(\"")
            .Append(baseRoute)
            .AppendLine("\");");

        if (_interfaceInfo.RequireAuthorization)
            _stringBuilder.AppendLine("        group.RequireAuthorization();");

        if (_interfaceInfo.CorsPolicy != null)
            _stringBuilder.Append("        group.RequireCors(\"")
              .Append(_interfaceInfo.CorsPolicy.EscapeStringLiteral())
              .AppendLine("\");");

        _stringBuilder.AppendLine();

        foreach (var method in _interfaceInfo.Methods)
        {
            GenerateEndpoint(method, routeNaming);
        }

        _stringBuilder.AppendLine("        return endpoints;");
        _stringBuilder.AppendLine("    }");
    }

    private void GenerateEndpoint(MethodInfo method, RouteNaming routeNaming)
    {
        // When the user specified an explicit Route, use it verbatim (no naming transformation).
        // ApplyRouteNaming is only applied to auto-derived method names.
        var routeSegment = method.CustomRoute ?? method.Name.ApplyRouteNaming(routeNaming);

        var routeParams = method.Parameters.Where(static p => p.IsRouteParameter).ToList();
        var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();
        var httpMethod = method.HttpMethod.ToString().ToPascalCase();

        _stringBuilder.Append("        group.Map").Append(httpMethod).Append("(\"/").Append(routeSegment).AppendLine("\",");

        var asyncKeyword = method.AsyncType is AsyncType.Task or AsyncType.ValueTask ? "async " : string.Empty;
        var returnTypeAnnotation = BuildHandlerReturnType(method);
        var returnTypeSuffix = string.IsNullOrEmpty(returnTypeAnnotation) ? string.Empty : $"{returnTypeAnnotation} ";
        _stringBuilder.Append($"            {asyncKeyword}{returnTypeSuffix}(");

        GenerateLambdaParameters(method, routeParams, nonRouteParams);

        _stringBuilder.AppendLine(") =>");
        _stringBuilder.AppendLine("            {");

        GenerateServiceCall(method);

        if (method.AsyncType is not AsyncType.AsyncEnumerable)
            GenerateResultReturn(method.ReturnType);

        _stringBuilder.AppendLine("            })");

        GenerateFluentChain(method);

        _stringBuilder.AppendLine();
    }

    private void GenerateFluentChain(MethodInfo method)
    {
        var interfaceRequiresAuth = _interfaceInfo.RequireAuthorization;
        var interfaceName = _interfaceInfo.Name;

        var chain = new List<string>();
        chain.Add($".WithName(\"{interfaceName}_{method.Name}\")");
        AddOpenApiChainEntries(method, interfaceName, chain);

        if (method.CacheSeconds > 0)
            chain.Add($".CacheOutput(p => p.Expire(System.TimeSpan.FromSeconds({method.CacheSeconds})))");

        if (method.RateLimitPolicy != null)
            chain.Add($".RequireRateLimiting(\"{method.RateLimitPolicy.EscapeStringLiteral()}\")");

        if (method.Policy != null)
            chain.Add($".RequireAuthorization(\"{method.Policy.EscapeStringLiteral()}\")");
        else if (method.RequireAuthorization && !interfaceRequiresAuth)
            chain.Add(".RequireAuthorization()");

        if (method.Roles != null)
            chain.Add($".RequireAuthorization(new AuthorizeAttribute {{ Roles = \"{method.Roles.EscapeStringLiteral()}\" }})");

        if (method.RequireAntiForgery)
            chain.Add(".WithMetadata(new RequireAntiforgeryTokenAttribute())");

        foreach (var filter in method.Filters)
            chain.Add($".AddEndpointFilter<{filter}>()");

        // File upload endpoints must opt out of anti-forgery validation (which is enforced automatically
        // when UseAntiforgery() middleware is active). Users who explicitly need anti-forgery on an upload
        // endpoint can set RequireAntiForgery = true, which adds RequireAntiforgeryTokenAttribute instead.
        bool hasFileParams = method.Parameters.Any(static p => p.FileKind != FileKind.None);
        if (hasFileParams && !method.RequireAntiForgery)
            chain.Add(".DisableAntiforgery()");

        for (int i = 0; i < chain.Count; i++)
        {
            _stringBuilder.Append("            ").Append(chain[i]);
            _stringBuilder.AppendLine(i == chain.Count - 1 ? ";" : "");
        }
    }

    /// <summary>
    /// Populates <paramref name="chain"/> with all OpenAPI-related fluent calls:
    /// WithTags, WithSummary, WithDescription, extra status codes,
    /// ExcludeFromDescription / WithOpenApi.
    /// <para>
    /// <c>.Produces&lt;T&gt;(200)</c> and <c>.ProducesProblem(500)</c> are intentionally omitted —
    /// they are now inferred by ASP.NET Core OpenAPI from the typed lambda return annotation
    /// (<c>Results&lt;Ok&lt;T&gt;, ProblemHttpResult&gt;</c>).
    /// </para>
    /// </summary>
    private void AddOpenApiChainEntries(
        MethodInfo method,
        string interfaceName,
        List<string> chain)
    {
        var tagsCall = method.Tags is { Length: > 0 }
            ? $".WithTags({string.Join(", ", method.Tags.Select(t => $"\"{t.EscapeStringLiteral()}\""))})"
            : $".WithTags(\"{DeriveTag(interfaceName)}\")";
        chain.Add(tagsCall);

        if (method.Summary is not null)
            chain.Add($".WithSummary(\"{method.Summary.EscapeStringLiteral()}\")");
        if (method.Description is not null)
            chain.Add($".WithDescription(\"{method.Description.EscapeStringLiteral()}\")");

        // TypedResults fully describes the response schema via the lambda return type;
        // .Produces<T>() and .ProducesProblem() are no longer emitted.
        // Extra user-specified status codes (404, 409, etc.) are still documented explicitly.
        if (method.AsyncType is not AsyncType.AsyncEnumerable && method.ProducesStatusCodes is { Length: > 0 })
            foreach (var sc in method.ProducesStatusCodes)
                chain.Add($".Produces({sc})");

        if (method.ExcludeFromOpenApi)
            chain.Add(".ExcludeFromDescription()");
        else if (_hasOpenApiPackage)
            chain.Add(".WithOpenApi()");
    }

    private static string DeriveTag(string interfaceName) =>
        interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;

    /// <summary>
    /// Returns the lambda return type annotation string to insert before the parameter list,
    /// e.g. <c>Task&lt;Results&lt;Ok&lt;User&gt;, ProblemHttpResult&gt;&gt;</c>.
    /// Returns <see cref="string.Empty"/> for streaming methods (<see cref="AsyncType.AsyncEnumerable"/>),
    /// which return <c>IAsyncEnumerable&lt;T&gt;</c> directly and need no annotation.
    /// </summary>
    private string BuildHandlerReturnType(MethodInfo method)
    {
        if (method.AsyncType is AsyncType.AsyncEnumerable)
            return string.Empty;

        var resultUnion = BuildResultUnionType(method);

        return method.AsyncType is AsyncType.Task or AsyncType.ValueTask
            ? $"Task<{resultUnion}>"
            : resultUnion;
    }

    /// <summary>
    /// Computes the inner result union type for the handler return annotation:
    /// <c>Results&lt;Ok&lt;T&gt;, ProblemHttpResult&gt;</c> when <c>GenerateProblemDetails</c> is true,
    /// or <c>Ok&lt;T&gt;</c> when false.
    /// </summary>
    private string BuildResultUnionType(MethodInfo method)
    {
        bool generateProblemDetails = _interfaceInfo.Configuration.GenerateProblemDetails;

        if (string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
            return generateProblemDetails ? "Results<Ok, ProblemHttpResult>" : "Ok";

        string successType;
        if (_interfaceInfo.ResultMapperTypeName is not null)
        {
            var typeArgs = method.ReturnType.ExtractGenericTypeArgs();
            successType = typeArgs.Length > 0 ? typeArgs[0] : method.ReturnType;
        }
        else
        {
            successType = method.ReturnType;
        }

        return generateProblemDetails
            ? $"Results<Ok<{successType}>, ProblemHttpResult>"
            : $"Ok<{successType}>";
    }

    private void GenerateLambdaParameters(
        MethodInfo method,
        List<ParameterInfo> routeParams,
        List<ParameterInfo> nonRouteParams)
    {
        // Route-bound params appear first as typed lambda arguments (unchanged)
        foreach (var rp in routeParams)
            _stringBuilder.Append(rp.Type).Append(' ').Append(rp.Name).Append(", ");

        bool hasFileParams = nonRouteParams.Any(static p => p.FileKind != FileKind.None);

        if (hasFileParams)
        {
            // File upload methods: list all non-route params inline.
            // File params auto-bind from multipart; regular params use [FromForm] unless explicitly overridden.
            AppendFileUploadParameters(nonRouteParams);
        }
        else
        {
            // Emit explicitly-bound (header / query / body) params as individual lambda args first.
            AppendExplicitlyBoundParameters(nonRouteParams);

            // Bundle remaining auto params into a single DTO, if any.
            var autoParams = nonRouteParams.Where(static p => p.ExplicitSource == ParameterSource.Auto).ToList();
            if (autoParams.Count > 0)
            {
                var bindingAttribute = method.HttpMethod is HttpMethod.Get or HttpMethod.Delete
                    ? "[AsParameters]"
                    : "[FromBody]";
                _stringBuilder.Append(bindingAttribute).Append(' ')
                    .Append(method.Name).Append("Request request, ");
            }
        }

        _stringBuilder.Append(_interfaceInfo.Name).Append(" service");

        if (method.HasCancellationToken)
            _stringBuilder.Append(", CancellationToken cancellationToken");
    }

    /// <summary>
    /// Emits inline lambda parameters for file upload methods.
    /// File params: IFormFile / IFormFileCollection (no binding attribute).
    /// Regular params: use explicit binding if specified, otherwise <c>[FromForm]</c>.
    /// </summary>
    private void AppendFileUploadParameters(List<ParameterInfo> nonRouteParams)
    {
        foreach (var p in nonRouteParams)
        {
            if (p.FileKind != FileKind.None)
            {
                var (paramType, attribute) = p.FileKind switch
                {
                    FileKind.Stream => ("IFormFile", string.Empty),
                    FileKind.FormFile => ("IFormFile", string.Empty),
                    FileKind.FormFileCollection => ("IFormFileCollection", string.Empty),
                    _ => (p.Type, string.Empty),
                };
                _stringBuilder.Append(attribute).Append(paramType).Append(' ').Append(p.Name).Append(", ");
            }
            else
            {
                // Regular param in a file upload method — honour explicit binding or fall back to [FromForm].
                var bindAttr = GetExplicitBindingAttribute(p) ?? "[FromForm] ";
                _stringBuilder.Append(bindAttr).Append(p.Type).Append(' ').Append(p.Name).Append(", ");
            }
        }
    }

    /// <summary>
    /// Emits individual lambda parameters for all non-auto (header / query / body) explicit bindings.
    /// Auto params are handled separately via the DTO path.
    /// </summary>
    private void AppendExplicitlyBoundParameters(List<ParameterInfo> nonRouteParams)
    {
        foreach (var p in nonRouteParams.Where(static p => p.ExplicitSource != ParameterSource.Auto))
        {
            var bindAttr = GetExplicitBindingAttribute(p)!;
            _stringBuilder.Append(bindAttr).Append(p.Type).Append(' ').Append(p.Name).Append(", ");
        }
    }

    /// <summary>
    /// Returns the ASP.NET Core binding attribute string (including trailing space) for a parameter
    /// with an explicit <see cref="ParameterSource"/>, or <c>null</c> for <see cref="ParameterSource.Auto"/>.
    /// </summary>
    private static string? GetExplicitBindingAttribute(ParameterInfo p)
    {
        switch (p.ExplicitSource)
        {
            case ParameterSource.Header:
                var headerName = (p.ExplicitName ?? p.Name).EscapeStringLiteral();
                return $"[FromHeader(Name = \"{headerName}\")] ";
            case ParameterSource.Query when p.ExplicitName is not null:
                return $"[FromQuery(Name = \"{p.ExplicitName.EscapeStringLiteral()}\")] ";
            case ParameterSource.Query:
                return "[FromQuery] ";
            case ParameterSource.Body:
                return "[FromBody] ";
            default:
                return null;
        }
    }

    private void GenerateServiceCall(MethodInfo method)
    {
        _stringBuilder.Append("                ");

        // Streaming: return the IAsyncEnumerable<T> directly — ASP.NET Core handles chunked streaming.
        if (method.AsyncType is AsyncType.AsyncEnumerable)
        {
            _stringBuilder.Append("return ");
        }
        else
        {
            if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
                _stringBuilder.Append("var result = ");

            if (method.AsyncType is not AsyncType.None)
                _stringBuilder.Append("await ");
        }

        _stringBuilder.Append("service.").Append(method.Name).Append('(');

        if (method.Parameters.Count > 0)
        {
            bool hasFileParams = method.Parameters.Any(static p => p.FileKind != FileKind.None);

            var paramList = method.Parameters.Select(p =>
            {
                if (p.IsRouteParameter)
                    return p.Name;

                // File params are bound inline regardless — extract stream via OpenReadStream if needed.
                if (p.FileKind != FileKind.None)
                    return p.FileKind == FileKind.Stream ? $"{p.Name}.OpenReadStream()" : p.Name;

                // Explicitly-bound (header / query / body) and inline file-upload regular params
                // are direct lambda args — access by name.
                if (p.ExplicitSource != ParameterSource.Auto || hasFileParams)
                    return p.Name;

                // Auto params in non-file methods are bundled in the DTO.
                return $"request.{p.Name.ToPascalCase()}";
            });

            _stringBuilder.Append(string.Join(", ", paramList));

            if (method.HasCancellationToken)
                _stringBuilder.Append(", cancellationToken");
        }
        else if (method.HasCancellationToken)
        {
            _stringBuilder.Append("cancellationToken");
        }

        _stringBuilder.AppendLine(");");
    }

    private void GenerateResultReturn(string returnType)
    {
        if (string.Equals(returnType, "void", StringComparison.Ordinal))
        {
            _stringBuilder.AppendLine("                return TypedResults.Ok();");
            return;
        }

        // When no ResultMapper is configured, or the return type has no generic args
        // (e.g. plain string / int), fall back to the default TypedResults.Ok(result) path.
        // BSF030 warns about the non-generic case at parse time.
        var mapperTypeName = _interfaceInfo.ResultMapperTypeName;
        var typeArgs = returnType.ExtractGenericTypeArgs();

        if (mapperTypeName is null || typeArgs.Length == 0)
        {
            _stringBuilder.AppendLine("                return TypedResults.Ok(result);");
            return;
        }

        var mapperInstantiation = $"new {mapperTypeName}<{string.Join(", ", typeArgs)}>()";

        _stringBuilder.AppendLine($"                var __mapper = {mapperInstantiation};");
        _stringBuilder.AppendLine("                if (__mapper.IsSuccess(result))");
        _stringBuilder.AppendLine("                    return TypedResults.Ok(__mapper.GetValue(result));");
        _stringBuilder.AppendLine("                var __error = __mapper.GetError(result);");
        _stringBuilder.AppendLine("                return TypedResults.Problem(");
        _stringBuilder.AppendLine("                    __error.Detail,");
        _stringBuilder.AppendLine("                    statusCode: __error.Status,");
        _stringBuilder.AppendLine("                    title: __error.Title,");
        _stringBuilder.AppendLine("                    type: __error.Type);");
    }

    private void GenerateRequestDtos()
    {
        foreach (var method in _interfaceInfo.Methods)
        {
            // File upload methods use inline lambda parameters for all params — no DTO record needed.
            bool hasFileParams = method.Parameters.Any(static p => p.FileKind != FileKind.None);
            if (hasFileParams)
                continue;

            // The DTO contains only "auto" non-route params; explicitly-bound params are lambda args.
            var autoParams = method.Parameters.Where(static p =>
                !p.IsRouteParameter
                && p.ExplicitSource == ParameterSource.Auto
                && p.FileKind == FileKind.None).ToList();

            if (autoParams.Count > 0)
                GenerateRequestDto(method, autoParams);
        }
    }

    private void GenerateRequestDto(MethodInfo method, List<ParameterInfo> autoParams)
    {
        _stringBuilder.AppendLine();
        _stringBuilder.Append("    private record ")
            .Append(method.Name)
            .Append("Request(");

        var properties = autoParams.Select(p => $"{p.Type} {p.Name.ToPascalCase()}");

        _stringBuilder.Append(string.Join(", ", properties));
        _stringBuilder.AppendLine(");");
    }
}
