using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;

namespace BlazorServerFunctions.Generator.Generators;

internal sealed class RestClientProxyGenerator
{
    private readonly InterfaceInfo _interfaceInfo;
    private readonly StringBuilder _stringBuilder = new();

    private RestClientProxyGenerator(InterfaceInfo interfaceInfo) => _interfaceInfo = interfaceInfo;

    public static string Generate(InterfaceInfo interfaceInfo) =>
        new RestClientProxyGenerator(interfaceInfo).GenerateCore();

    private string GenerateCore()
    {
        var config = _interfaceInfo.Configuration;
        var httpClientType = config.CustomHttpClientType ?? "HttpClient";
        var baseRoute = $"/{config.BaseRoute.TrimStart('/')}/{_interfaceInfo.RoutePrefix}";

        _stringBuilder.AppendLine("// <auto-generated />");
        if (config.Nullable)
            _stringBuilder.AppendLine("#nullable enable");
        _stringBuilder.AppendLine();

        var hasCancellationToken = _interfaceInfo.Methods.Any(m => m.HasCancellationToken);
        var hasStreaming = _interfaceInfo.Methods.Any(m => m.AsyncType is AsyncType.AsyncEnumerable);
        AddUsingDirectives(hasCancellationToken: hasCancellationToken, hasStreaming: hasStreaming);

        _stringBuilder.Append("namespace ").Append(_interfaceInfo.Namespace).Append(';').AppendLine();
        _stringBuilder.AppendLine();
        _stringBuilder.Append("public class ").Append(_interfaceInfo.Name.TrimStart('I')).Append("Client : ").Append(_interfaceInfo.Name).AppendLine();
        _stringBuilder.AppendLine("{");
        _stringBuilder.Append("    private readonly ").Append(httpClientType).AppendLine(" _httpClient;");
        _stringBuilder.AppendLine($"    private const string BaseRoute = \"{baseRoute}\";");
        _stringBuilder.AppendLine();

        AddConstructor(name: _interfaceInfo.Name, httpClientType: httpClientType);

        _stringBuilder.AppendLine();

        foreach (var method in _interfaceInfo.Methods)
        {
            GenerateClientMethod(method, config.RouteNaming);
        }

        _stringBuilder.AppendLine("}");

        return _stringBuilder.ToString();
    }

    private void AddConstructor(string name, string httpClientType)
    {
        _stringBuilder.Append($"    public {name.TrimStart('I')}Client(").Append(httpClientType).AppendLine(" httpClient)");
        _stringBuilder.AppendLine("    {");
        _stringBuilder.AppendLine("        _httpClient = httpClient;");
        _stringBuilder.AppendLine("    }");
    }

    private void AddUsingDirectives(bool hasCancellationToken, bool hasStreaming)
    {
        _stringBuilder.AppendLine("using System;");
        _stringBuilder.AppendLine("using System.Net;");
        _stringBuilder.AppendLine("using System.Net.Http;");
        _stringBuilder.AppendLine("using System.Net.Http.Json;");
        if (hasStreaming)
        {
            _stringBuilder.AppendLine("using System.Collections.Generic;");
            _stringBuilder.AppendLine("using System.Runtime.CompilerServices;");
        }

        // Streaming methods always add a CancellationToken parameter even when the interface omits one
        if (hasCancellationToken || hasStreaming)
            _stringBuilder.AppendLine("using System.Threading;");
        _stringBuilder.AppendLine("using System.Threading.Tasks;");
        _stringBuilder.AppendLine();
    }

    private static string GetAwaitKeyword(AsyncType asyncType) =>
        asyncType is not AsyncType.None ? "await " : string.Empty;

    private static string GetResultSuffix(AsyncType asyncType) =>
        asyncType is AsyncType.None ? ".GetAwaiter().GetResult()" : string.Empty;

    /// <summary>
    /// Strips route constraints from route parameter tokens so they are valid C# interpolation expressions.
    /// For example: {id:int} → {id}, {slug:minlength(3)} → {slug}, {id?} → {id}.
    /// </summary>
    private static string RouteTemplateToInterpolation(string routeTemplate) =>
        RegexExpressions.RouteParameterRegex.Replace(routeTemplate, static m => "{" + m.Groups["name"].Value + "}");

    private void GenerateClientMethod(MethodInfo methodInfo, RouteNaming routeNaming)
    {
        GenerateMethodSignature(method: methodInfo);

        _stringBuilder.AppendLine("    {");

        if (methodInfo.AsyncType is AsyncType.AsyncEnumerable)
        {
            GenerateStreamingClientMethodBody(methodInfo, routeNaming);
            _stringBuilder.AppendLine("    }");
            _stringBuilder.AppendLine();
            return;
        }

        var nonRouteParams = methodInfo.Parameters.Where(static p => !p.IsRouteParameter).ToList();
        var hasNonRouteParams = nonRouteParams.Count > 0;

        if (hasNonRouteParams && methodInfo.HttpMethod is HttpMethod.Post or HttpMethod.Put or HttpMethod.Patch)
            BuildRequestObject(parameters: nonRouteParams);

        GenerateHttpRequest(
            method: methodInfo,
            nonRouteParams: nonRouteParams,
            routeNaming: routeNaming);

        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        if (!response.IsSuccessStatusCode)");
        _stringBuilder.AppendLine("        {");
        _stringBuilder.Append("            var errorBody = ")
            .Append(GetAwaitKeyword(methodInfo.AsyncType))
            .Append("response.Content.ReadAsStringAsync(");
        if (methodInfo.HasCancellationToken)
            _stringBuilder.Append("cancellationToken");
        _stringBuilder.Append(')').Append(GetResultSuffix(methodInfo.AsyncType)).AppendLine(";");
        _stringBuilder.AppendLine("            throw new HttpRequestException(errorBody, null, response.StatusCode);");
        _stringBuilder.AppendLine("        }");
        _stringBuilder.AppendLine();

        if (!string.Equals(methodInfo.ReturnType, "void", StringComparison.OrdinalIgnoreCase))
        {
            // Use a nullable type argument so that ?? throw works for both value types
            // (where ReadFromJsonAsync<T> may return T in .NET 10+) and reference types.
            var nullableReturnType = methodInfo.ReturnType.EndsWith("?", StringComparison.Ordinal)
                ? methodInfo.ReturnType
                : methodInfo.ReturnType + "?";

            _stringBuilder.Append("        return ")
                .Append(GetAwaitKeyword(methodInfo.AsyncType))
                .Append("response.Content.ReadFromJsonAsync<")
                .Append(nullableReturnType)
                .Append(">()")
                .Append(GetResultSuffix(methodInfo.AsyncType))
                .AppendLine();
            _stringBuilder.AppendLine("            ?? throw new InvalidOperationException(\"Response deserialization returned null\");");
        }

        _stringBuilder.AppendLine("    }");
        _stringBuilder.AppendLine();
    }

    private void BuildRequestObject(List<ParameterInfo> parameters)
    {
        _stringBuilder.AppendLine("        var request = new");
        _stringBuilder.AppendLine("        {");

        foreach (var parameterName in parameters.Select(p => p.Name))
        {
            _stringBuilder.Append("            ")
                .Append(parameterName.ToPascalCase())
                .Append(" = ")
                .Append(parameterName)
                .AppendLine(",");
        }

        _stringBuilder.AppendLine("        };");
        _stringBuilder.AppendLine();
    }

    private void GenerateMethodSignature(MethodInfo method)
    {
        _stringBuilder.Append("    public ");

        if (method.AsyncType is AsyncType.AsyncEnumerable)
            _stringBuilder.Append("async IAsyncEnumerable<").Append(method.ReturnType).Append('>');
        else if (method.AsyncType is not AsyncType.None)
        {
            _stringBuilder.Append("async ").Append(method.AsyncType.ToString());
            if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
                _stringBuilder.Append('<').Append(method.ReturnType).Append('>');
        }
        else
            _stringBuilder.Append(method.ReturnType);

        _stringBuilder.Append(' ').Append(method.Name).Append('(');

        var paramDeclarations = method.Parameters.Select(p =>
        {
            var declaration = $"{p.Type} {p.Name}";
            if (p.HasDefaultValue)
            {
                declaration += $" = {FormatDefaultValue(p.Type, p.DefaultValue)}";
            }

            return declaration;
        }).ToList();

        if (method.AsyncType is AsyncType.AsyncEnumerable)
        {
            // Streaming methods always expose [EnumeratorCancellation] CancellationToken
            if (paramDeclarations.Count > 0)
                _stringBuilder.Append(string.Join(", ", paramDeclarations)).Append(", ");
            _stringBuilder.Append("[EnumeratorCancellation] CancellationToken cancellationToken = default");
        }
        else if (method.HasCancellationToken)
        {
            if (paramDeclarations.Count > 0)
                _stringBuilder.Append(string.Join(", ", paramDeclarations)).Append(", CancellationToken cancellationToken = default");
            else
                _stringBuilder.Append("CancellationToken cancellationToken = default");
        }
        else
        {
            _stringBuilder.Append(string.Join(", ", paramDeclarations));
        }

        _stringBuilder.AppendLine(")");
    }

    private void GenerateHttpRequest(MethodInfo method, List<ParameterInfo> nonRouteParams, RouteNaming routeNaming)
    {
        // When the user specified an explicit Route, use it verbatim (stripping constraints for C# interpolation).
        // ApplyRouteNaming is only applied to auto-derived method names.
        var urlSegment = method.CustomRoute != null
            ? RouteTemplateToInterpolation(method.CustomRoute)
            : method.Name.ApplyRouteNaming(routeNaming);

        var hasNonRouteParams = nonRouteParams.Count > 0;

        switch (method.HttpMethod)
        {
            case HttpMethod.Post:
                GeneratePostRequest(urlSegment, hasNonRouteParams, method.AsyncType, method.HasCancellationToken);
                break;

            case HttpMethod.Get:
            case HttpMethod.Delete:
                GenerateQueryStringRequest(urlSegment, method.HttpMethod, nonRouteParams, method.AsyncType, method.HasCancellationToken);
                break;

            default:
                GenerateOtherRequest(urlSegment, method.HttpMethod, hasNonRouteParams, method.AsyncType, method.HasCancellationToken);
                break;
        }
    }

    private void GeneratePostRequest(string urlSegment, bool hasParameters, AsyncType asyncType, bool hasCancellationToken)
    {
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        if (hasParameters)
        {
            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.PostAsJsonAsync(");
            _stringBuilder.Append("            $\"{BaseRoute}/").Append(urlSegment).AppendLine("\",");
            if (hasCancellationToken)
            {
                _stringBuilder.AppendLine("            request,");
                _stringBuilder.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                _stringBuilder.AppendLine($"            request){resultSuffix};");
            }
        }
        else
        {
            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.PostAsync(");
            _stringBuilder.Append("            $\"{BaseRoute}/").Append(urlSegment).AppendLine("\",");
            if (hasCancellationToken)
            {
                _stringBuilder.AppendLine("            null,");
                _stringBuilder.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                _stringBuilder.AppendLine($"            null){resultSuffix};");
            }
        }
    }

    private void GenerateQueryStringRequest(
        string urlSegment,
        HttpMethod httpMethod,
        List<ParameterInfo> parameters,
        AsyncType asyncType,
        bool hasCancellationToken)
    {
        var verb = httpMethod.ToString();
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        if (parameters.Count > 0)
        {
            _stringBuilder.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");

            foreach (var parameter in parameters)
            {
                _stringBuilder.Append("        queryString[\"")
                    .Append(parameter.Name.ToPascalCase())
                    .Append("\"] = ")
                    .Append(parameter.Name)
                    .AppendLine($"{(parameter.Type.EndsWith("?", StringComparison.Ordinal) ? "?" : string.Empty)}.ToString(System.Globalization.CultureInfo.InvariantCulture);");
            }

            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.{verb}Async(");
            if (hasCancellationToken)
            {
                _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}?{{queryString}}\",");
                _stringBuilder.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}?{{queryString}}\"){resultSuffix};");
            }
        }
        else
        {
            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.{verb}Async(");
            if (hasCancellationToken)
            {
                _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}\",");
                _stringBuilder.AppendLine($"            cancellationToken){resultSuffix};");
            }
            else
            {
                _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}\"){resultSuffix};");
            }
        }
    }

    private void GenerateOtherRequest(
        string urlSegment,
        HttpMethod httpMethod,
        bool hasParameters,
        AsyncType asyncType,
        bool hasCancellationToken)
    {
        var awaitKeyword = GetAwaitKeyword(asyncType);
        var resultSuffix = GetResultSuffix(asyncType);

        _stringBuilder.AppendLine("        var requestMessage = new HttpRequestMessage");
        _stringBuilder.AppendLine("        {");
        _stringBuilder.AppendLine($"            Method = HttpMethod.{httpMethod},");

        if (hasParameters)
        {
            _stringBuilder.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{urlSegment}\", UriKind.Relative),");
            _stringBuilder.AppendLine("            Content = JsonContent.Create(request)");
        }
        else
        {
            _stringBuilder.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{urlSegment}\", UriKind.Relative)");
        }

        _stringBuilder.AppendLine("        };");

        if (hasCancellationToken)
            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.SendAsync(requestMessage, cancellationToken){resultSuffix};");
        else
            _stringBuilder.AppendLine($"        var response = {awaitKeyword}_httpClient.SendAsync(requestMessage){resultSuffix};");
    }

    private void GenerateStreamingClientMethodBody(MethodInfo method, RouteNaming routeNaming)
    {
        var urlSegment = method.CustomRoute != null
            ? RouteTemplateToInterpolation(method.CustomRoute)
            : method.Name.ApplyRouteNaming(routeNaming);

        var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();

        if (method.HttpMethod is HttpMethod.Get or HttpMethod.Delete)
        {
            GenerateStreamingQueryStringRequest(urlSegment, method.HttpMethod, nonRouteParams);
        }
        else
        {
            if (nonRouteParams.Count > 0)
                BuildRequestObject(nonRouteParams);
            GenerateStreamingOtherRequest(urlSegment, method.HttpMethod, nonRouteParams);
        }

        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine("        if (!response.IsSuccessStatusCode)");
        _stringBuilder.AppendLine("        {");
        _stringBuilder.AppendLine("            var errorBody = await response.Content.ReadAsStringAsync(cancellationToken);");
        _stringBuilder.AppendLine("            throw new HttpRequestException(errorBody, null, response.StatusCode);");
        _stringBuilder.AppendLine("        }");
        _stringBuilder.AppendLine();
        _stringBuilder.AppendLine($"        await foreach (var item in response.Content.ReadFromJsonAsAsyncEnumerable<{method.ReturnType}>(cancellationToken)!)");
        _stringBuilder.AppendLine("            yield return item!;");
    }

    private void GenerateStreamingQueryStringRequest(
        string urlSegment,
        HttpMethod httpMethod,
        List<ParameterInfo> nonRouteParams)
    {
        var verb = httpMethod.ToString();

        if (nonRouteParams.Count > 0)
        {
            _stringBuilder.AppendLine("        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);");
            foreach (var parameter in nonRouteParams)
            {
                _stringBuilder.Append("        queryString[\"")
                    .Append(parameter.Name.ToPascalCase())
                    .Append("\"] = ")
                    .Append(parameter.Name)
                    .AppendLine($"{(parameter.Type.EndsWith("?", StringComparison.Ordinal) ? "?" : string.Empty)}.ToString(System.Globalization.CultureInfo.InvariantCulture);");
            }

            _stringBuilder.AppendLine($"        var response = await _httpClient.{verb}Async(");
            _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}?{{queryString}}\",");
        }
        else
        {
            _stringBuilder.AppendLine($"        var response = await _httpClient.{verb}Async(");
            _stringBuilder.AppendLine($"            $\"{{BaseRoute}}/{urlSegment}\",");
        }

        _stringBuilder.AppendLine("            HttpCompletionOption.ResponseHeadersRead,");
        _stringBuilder.AppendLine("            cancellationToken);");
    }

    private void GenerateStreamingOtherRequest(
        string urlSegment,
        HttpMethod httpMethod,
        List<ParameterInfo> nonRouteParams)
    {
        _stringBuilder.AppendLine("        var requestMessage = new HttpRequestMessage");
        _stringBuilder.AppendLine("        {");
        _stringBuilder.AppendLine($"            Method = HttpMethod.{httpMethod},");

        if (nonRouteParams.Count > 0)
        {
            _stringBuilder.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{urlSegment}\", UriKind.Relative),");
            _stringBuilder.AppendLine("            Content = JsonContent.Create(request)");
        }
        else
        {
            _stringBuilder.AppendLine($"            RequestUri = new Uri($\"{{BaseRoute}}/{urlSegment}\", UriKind.Relative)");
        }

        _stringBuilder.AppendLine("        };");
        _stringBuilder.AppendLine("        var response = await _httpClient.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead, cancellationToken);");
    }

    private static string FormatDefaultValue(string type, object? defaultValue)
    {
        if (defaultValue == null)
        {
            return "null";
        }

        if (string.Equals(type, "string", StringComparison.OrdinalIgnoreCase))
        {
            return $"\"{defaultValue}\"";
        }

        if (string.Equals(type, "bool", StringComparison.OrdinalIgnoreCase))
        {
            return defaultValue.ToString()?.ToLowerInvariant() ?? false.ToString();
        }

        if (type.Contains('?') && string.Equals(defaultValue.ToString(), "null", StringComparison.OrdinalIgnoreCase))
        {
            return "null";
        }

        return Convert.ToString(defaultValue, System.Globalization.CultureInfo.InvariantCulture)!;
    }
}
