using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerRegistrationGenerator
{
    public static string Generate(IReadOnlyCollection<InterfaceInfo> interfaces, string? targetNamespace)
    {
        if (interfaces.Count == 0)
            return string.Empty;

        var ns = !string.IsNullOrEmpty(targetNamespace) ? targetNamespace : interfaces.First().Namespace;
        var externalNamespaces = interfaces
            .Select(i => i.Namespace)
            .Where(n => !string.Equals(n, ns, StringComparison.Ordinal) && !string.IsNullOrEmpty(n))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Diagnostics.HealthChecks;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Diagnostics.HealthChecks;");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");

        foreach (var externalNs in externalNamespaces)
            sb.Append("using ").Append(externalNs).AppendLine(";");

        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("public static class ServerFunctionEndpointsRegistration");
        sb.AppendLine("{");
        GenerateMapEndpointsMethod(sb, interfaces);
        GenerateAddHealthChecksMethod(sb, interfaces);
        GenerateMapHealthChecksMethod(sb);
        sb.AppendLine("}");
        sb.AppendLine();
        GenerateResolveCheckHelper(sb);

        return sb.ToString();
    }

    private static void GenerateMapEndpointsMethod(StringBuilder sb, IReadOnlyCollection<InterfaceInfo> interfaces)
    {
        sb.AppendLine("    public static IEndpointRouteBuilder MapServerFunctionEndpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var interfaceInfo in interfaces)
        {
            sb.Append("        endpoints.Map")
                .Append(interfaceInfo.Name)
                .AppendLine("Endpoints();");
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }

    private static void GenerateAddHealthChecksMethod(StringBuilder sb, IReadOnlyCollection<InterfaceInfo> interfaces)
    {
        sb.AppendLine();
        sb.AppendLine("    public static IServiceCollection AddServerFunctionHealthChecks(");
        sb.AppendLine("        this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.Append("        services.AddHealthChecks()");

        var list = interfaces.ToList();
        for (var i = 0; i < list.Count; i++)
        {
            var tag = DeriveTag(list[i].Name);
            sb.AppendLine();
            sb.AppendLine("            .Add(new HealthCheckRegistration(");
            sb.Append("                \"").Append(tag).AppendLine("\",");
            sb.Append("                sp => new __BsfResolveCheck<").Append(list[i].Name).AppendLine(">(sp),");
            sb.AppendLine("                HealthStatus.Unhealthy,");
            sb.Append("                tags: new[] { \"bsf\" }))");
            if (i == list.Count - 1)
                sb.AppendLine(";");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
    }

    private static void GenerateMapHealthChecksMethod(StringBuilder sb)
    {
        sb.AppendLine();
        sb.AppendLine("    public static IEndpointRouteBuilder MapServerFunctionHealthChecks(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints,");
        sb.AppendLine("        string pattern = \"/health/server-functions\")");
        sb.AppendLine("    {");
        sb.AppendLine("        endpoints.MapHealthChecks(pattern, new HealthCheckOptions");
        sb.AppendLine("        {");
        sb.AppendLine("            Predicate = check => check.Tags.Contains(\"bsf\"),");
        sb.AppendLine("        });");
        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }

    private static void GenerateResolveCheckHelper(StringBuilder sb)
    {
        sb.AppendLine("internal sealed class __BsfResolveCheck<TService> : IHealthCheck");
        sb.AppendLine("    where TService : class");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _sp;");
        sb.AppendLine("    internal __BsfResolveCheck(IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();
        sb.AppendLine("    public Task<HealthCheckResult> CheckHealthAsync(");
        sb.AppendLine("        HealthCheckContext context,");
        sb.AppendLine("        CancellationToken cancellationToken = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            using var scope = _sp.CreateScope();");
        sb.AppendLine("            _ = scope.ServiceProvider.GetRequiredService<TService>();");
        sb.AppendLine("            return Task.FromResult(HealthCheckResult.Healthy());");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            return Task.FromResult(HealthCheckResult.Unhealthy(ex.Message, ex));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static string DeriveTag(string interfaceName) =>
        interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
            ? interfaceName.Substring(1)
            : interfaceName;
}
