using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerEndpointGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo, string? targetNamespace)
    {
        var sb = new StringBuilder();
        var effectiveNamespace = !string.IsNullOrEmpty(targetNamespace) ? targetNamespace : interfaceInfo.Namespace;

        // Add interface namespace as a using when it differs from the target namespace
        var interfaceUsingNs = !string.IsNullOrEmpty(interfaceInfo.Namespace) &&
                               !string.Equals(interfaceInfo.Namespace, effectiveNamespace, StringComparison.Ordinal)
            ? interfaceInfo.Namespace
            : null;

        var hasAuthorization = interfaceInfo.RequireAuthorization || interfaceInfo.Methods.Any(m => m.RequireAuthorization);
        var hasCancellationToken = interfaceInfo.Methods.Any(m => m.HasCancellationToken);

        GenerateFileHeader(sb, interfaceInfo.Configuration.Nullable);
        GenerateUsingDirectives(sb, hasAuthorization, hasCancellationToken, interfaceUsingNs);

        if (!string.IsNullOrEmpty(effectiveNamespace))
        {
            sb.Append("namespace ").Append(effectiveNamespace).AppendLine(";");
            sb.AppendLine();
        }

        sb.Append("internal static class ").Append(interfaceInfo.Name).AppendLine("ServerExtensions");
        sb.AppendLine("{");

        GenerateMapEndpointsMethod(sb, interfaceInfo);
        GenerateRequestDtos(sb, interfaceInfo);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb, bool nullable)
    {
        sb.AppendLine("// <auto-generated />");
        if (nullable)
            sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingDirectives(StringBuilder sb, bool hasAuthorization, bool hasCancellationToken, string? additionalNamespace)
    {
        if (hasAuthorization)
            sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Text.Json;");
        if (hasCancellationToken)
            sb.AppendLine("using System.Threading;");
        if (!string.IsNullOrEmpty(additionalNamespace))
            sb.Append("using ").Append(additionalNamespace).AppendLine(";");
        sb.AppendLine();
    }

    private static void GenerateMapEndpointsMethod(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        var baseRoute = $"/{interfaceInfo.Configuration.BaseRoute.TrimStart('/')}/{interfaceInfo.RoutePrefix}";
        var routeNaming = interfaceInfo.Configuration.RouteNaming;

        sb.Append("    internal static IEndpointRouteBuilder Map")
            .Append(interfaceInfo.Name)
            .AppendLine("Endpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");
        sb.Append("        var group = endpoints.MapGroup(\"")
            .Append(baseRoute)
            .AppendLine("\");");

        if (interfaceInfo.RequireAuthorization)
            sb.AppendLine("        group.RequireAuthorization();");

        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
        {
            GenerateEndpoint(sb, interfaceInfo.Name, method, interfaceInfo.RequireAuthorization, routeNaming);
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }

    private static void GenerateEndpoint(StringBuilder sb, string interfaceName, MethodInfo method, bool interfaceRequiresAuth, RouteNaming routeNaming)
    {
        // When the user specified an explicit Route, use it verbatim (no naming transformation).
        // ApplyRouteNaming is only applied to auto-derived method names.
        var routeSegment = method.CustomRoute ?? method.Name.ApplyRouteNaming(routeNaming);

        var routeParams = method.Parameters.Where(static p => p.IsRouteParameter).ToList();
        var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();
        var httpMethod = method.HttpMethod.ToString().ToPascalCase();

        sb.Append("        group.Map").Append(httpMethod).Append("(\"/").Append(routeSegment).AppendLine("\",");

        var asyncKeyword = method.AsyncType is AsyncType.Task or AsyncType.ValueTask ? "async " : string.Empty;
        sb.Append($"            {asyncKeyword}(");

        GenerateLambdaParameters(sb, interfaceName, method, routeParams, nonRouteParams);

        sb.AppendLine(") =>");
        sb.AppendLine("            {");

        GenerateServiceCall(sb, method);

        if (method.AsyncType is not AsyncType.AsyncEnumerable)
            GenerateResultReturn(sb, method.ReturnType);

        sb.AppendLine("            })");

        var methodRequiresAuth = method.RequireAuthorization && !interfaceRequiresAuth;
        sb.Append("            .WithName(\"")
            .Append(interfaceName)
            .Append('_')
            .Append(method.Name)
            .Append('"');

        if (methodRequiresAuth)
        {
            sb.AppendLine(")");
            sb.AppendLine("            .RequireAuthorization();");
        }
        else
        {
            sb.AppendLine(");");
        }

        sb.AppendLine();
    }

    private static void GenerateLambdaParameters(
        StringBuilder sb,
        string interfaceName,
        MethodInfo method,
        List<ParameterInfo> routeParams,
        List<ParameterInfo> nonRouteParams)
    {
        // Route-bound params appear first as typed lambda arguments
        foreach (var rp in routeParams)
        {
            sb.Append(rp.Type).Append(' ').Append(rp.Name).Append(", ");
        }

        // Non-route params are bundled into a DTO (if any exist)
        if (nonRouteParams.Count > 0)
        {
            var bindingAttribute = method.HttpMethod is HttpMethod.Get or HttpMethod.Delete
                ? "[AsParameters]"
                : "[FromBody]";

            sb.Append(bindingAttribute).Append(' ')
                .Append(method.Name)
                .Append("Request request, ");
        }

        sb.Append(interfaceName).Append(" service");

        if (method.HasCancellationToken)
            sb.Append(", CancellationToken cancellationToken");
    }

    private static void GenerateServiceCall(StringBuilder sb, MethodInfo method)
    {
        sb.Append("                ");

        // Streaming: return the IAsyncEnumerable<T> directly — ASP.NET Core handles chunked streaming.
        if (method.AsyncType is AsyncType.AsyncEnumerable)
        {
            sb.Append("return ");
        }
        else
        {
            if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
                sb.Append("var result = ");

            if (method.AsyncType is not AsyncType.None)
                sb.Append("await ");
        }

        sb.Append("service.").Append(method.Name).Append('(');

        if (method.Parameters.Count > 0)
        {
            var paramList = method.Parameters
                .Select(p => p.IsRouteParameter
                    ? p.Name
                    : $"request.{p.Name.ToPascalCase()}");
            sb.Append(string.Join(", ", paramList));

            if (method.HasCancellationToken)
                sb.Append(", cancellationToken");
        }
        else if (method.HasCancellationToken)
        {
            sb.Append("cancellationToken");
        }

        sb.AppendLine(");");
    }

    private static void GenerateResultReturn(StringBuilder sb, string returnType)
    {
        if (!string.Equals(returnType, "void", StringComparison.Ordinal))
        {
            sb.AppendLine("                return Results.Ok(result);");
        }
        else
        {
            sb.AppendLine("                return Results.Ok();");
        }
    }

    private static void GenerateRequestDtos(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        foreach (var method in interfaceInfo.Methods)
        {
            var nonRouteParams = method.Parameters.Where(static p => !p.IsRouteParameter).ToList();
            if (nonRouteParams.Count > 0)
            {
                GenerateRequestDto(sb, method, nonRouteParams);
            }
        }
    }

    private static void GenerateRequestDto(StringBuilder sb, MethodInfo method, List<ParameterInfo> nonRouteParams)
    {
        sb.AppendLine();
        sb.Append("    private record ")
            .Append(method.Name)
            .Append("Request(");

        var properties = nonRouteParams
            .Select(p => $"{p.Type} {p.Name.ToPascalCase()}");

        sb.Append(string.Join(", ", properties));
        sb.AppendLine(");");
    }
}
