using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;
using HttpMethod = BlazorServerFunctions.Generator.Models.HttpMethod;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerEndpointGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        var hasAuthorization = interfaceInfo.RequireAuthorization || interfaceInfo.Methods.Any(m => m.RequireAuthorization);
        var hasCancellationToken = interfaceInfo.Methods.Any(m => m.HasCancellationToken);

        GenerateFileHeader(sb);
        GenerateUsingDirectives(sb, hasAuthorization, hasCancellationToken);

        sb.Append("namespace ").Append(interfaceInfo.Namespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal static class ").Append(interfaceInfo.Name).AppendLine("ServerExtensions");
        sb.AppendLine("{");

        GenerateMapEndpointsMethod(sb, interfaceInfo);
        GenerateRequestDtos(sb, interfaceInfo);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingDirectives(StringBuilder sb, bool hasAuthorization, bool hasCancellationToken)
    {
        if (hasAuthorization)
            sb.AppendLine("using Microsoft.AspNetCore.Authorization;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Text.Json;");
        if (hasCancellationToken)
            sb.AppendLine("using System.Threading;");
        sb.AppendLine();
    }

    private static void GenerateMapEndpointsMethod(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        sb.Append("    internal static IEndpointRouteBuilder Map")
            .Append(interfaceInfo.Name)
            .AppendLine("Endpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");
        sb.Append("        var group = endpoints.MapGroup(\"/api/functions/")
            .Append(interfaceInfo.RoutePrefix)
            .AppendLine("\");");

        if (interfaceInfo.RequireAuthorization)
            sb.AppendLine("        group.RequireAuthorization();");

        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
        {
            GenerateEndpoint(sb, interfaceInfo.Name, method, interfaceInfo.RequireAuthorization);
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }

    private static void GenerateEndpoint(StringBuilder sb, string interfaceName, MethodInfo method, bool interfaceRequiresAuth)
    {
        var routeName = method.CustomRoute ?? method.Name;
        var hasParameters = method.Parameters.Count > 0;
        var httpMethod = method.HttpMethod.ToString().ToPascalCase();

        sb.Append("        group.Map").Append(httpMethod).Append("(\"/").Append(routeName).AppendLine("\",");

        var asyncKeyword = method.AsyncType is not AsyncType.None ? "async " : string.Empty;

        if (hasParameters)
        {
            var bindingAttribute = method.HttpMethod is HttpMethod.Get or HttpMethod.Delete
                ? "[AsParameters]"
                : "[FromBody]";

            sb.Append($"            {asyncKeyword}(").Append(bindingAttribute).Append(' ')
                .Append(method.Name)
                .Append("Request request, ")
                .Append(interfaceName)
                .Append(" service");
        }
        else
        {
            sb.Append($"            {asyncKeyword}(")
                .Append(interfaceName)
                .Append(" service");
        }

        if (method.HasCancellationToken)
            sb.Append(", CancellationToken cancellationToken");

        sb.AppendLine(") =>");
        sb.AppendLine("            {");

        GenerateServiceCall(sb, method);

        GenerateResultReturn(sb, method.ReturnType);

        sb.AppendLine("            })");

        var methodRequiresAuth = method.RequireAuthorization && !interfaceRequiresAuth;
        sb.Append("            .WithName(\"")
            .Append(interfaceName)
            .Append('_')
            .Append(method.Name)
            .Append('"');

        if (methodRequiresAuth)
        {
            sb.AppendLine(")");
            sb.AppendLine("            .RequireAuthorization();");
        }
        else
        {
            sb.AppendLine(");");
        }

        sb.AppendLine();
    }

    private static void GenerateServiceCall(StringBuilder sb, MethodInfo method)
    {
        sb.Append("                ");

        if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
        {
            sb.Append("var result = ");
        }

        if (method.AsyncType is not AsyncType.None)
            sb.Append("await ");

        sb.Append("service.").Append(method.Name).Append('(');

        if (method.Parameters.Count > 0)
        {
            var paramList = method.Parameters
                .Select(p => $"request.{p.Name.ToPascalCase()}");
            sb.Append(string.Join(", ", paramList));

            if (method.HasCancellationToken)
                sb.Append(", cancellationToken");
        }
        else if (method.HasCancellationToken)
        {
            sb.Append("cancellationToken");
        }

        sb.AppendLine(");");
    }

    private static void GenerateResultReturn(StringBuilder sb, string returnType)
    {
        if (!string.Equals(returnType, "void", StringComparison.Ordinal))
        {
            sb.AppendLine("                return Results.Ok(result);");
        }
        else
        {
            sb.AppendLine("                return Results.Ok();");
        }
    }

    private static void GenerateRequestDtos(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        foreach (var method in interfaceInfo.Methods)
        {
            if (method.Parameters.Count > 0)
            {
                GenerateRequestDto(sb, method);
            }
        }
    }

    private static void GenerateRequestDto(StringBuilder sb, MethodInfo method)
    {
        sb.AppendLine();
        sb.Append("    private record ")
            .Append(method.Name)
            .Append("Request(");

        var properties = method.Parameters
            .Select(p => $"{p.Type} {p.Name.ToPascalCase()}");

        sb.Append(string.Join(", ", properties));
        sb.AppendLine(");");
    }
}
