using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerRegistrationGenerator
{
    public static string Generate(IReadOnlyCollection<InterfaceInfo> interfaces)
    {
        if (interfaces.Count == 0)
            return string.Empty;

        var generatedNamespace = FindCommonNamespace(interfaces);
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");

        foreach (var ns in interfaces
            .Select(i => i.Namespace)
            .Distinct(StringComparer.Ordinal)
            .Where(ns => !string.Equals(ns, generatedNamespace, StringComparison.Ordinal))
            .OrderBy(ns => ns, StringComparer.Ordinal))
        {
            sb.Append("using ").Append(ns).AppendLine(";");
        }

        sb.AppendLine();
        sb.Append("namespace ").Append(generatedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.AppendLine("public static class ServerFunctionEndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapServerFunctionEndpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var interfaceInfo in interfaces)
        {
            sb.Append("        endpoints.Map")
                .Append(interfaceInfo.Name)
                .AppendLine("Endpoints();");
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string FindCommonNamespace(IReadOnlyCollection<InterfaceInfo> interfaces)
    {
        var namespaces = interfaces.Select(i => i.Namespace).Distinct(StringComparer.Ordinal).ToList();
        if (namespaces.Count == 1)
            return namespaces[0];

        var parts = namespaces.Select(ns => ns.Split('.')).ToList();
        var common = new List<string>();
        var minLength = parts.Min(p => p.Length);

        for (var i = 0; i < minLength; i++)
        {
            var segment = parts[0][i];
            if (parts.All(p => string.Equals(p[i], segment, StringComparison.Ordinal)))
                common.Add(segment);
            else
                break;
        }

        return common.Count > 0 ? string.Join(".", common) : "BlazorServerFunctions.Generated";
    }
}
