using System.Text;
using BlazorServerFunctions.Generator.Helpers;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerEndpointGenerator
{
    public static string Generate(InterfaceInfo interfaceInfo)
    {
        var sb = new StringBuilder();

        GenerateFileHeader(sb);
        GenerateUsingDirectives(sb, interfaceInfo);

        sb.Append("namespace ").Append(interfaceInfo.Namespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal static class ").Append(interfaceInfo.Name).AppendLine("ServerExtensions");
        sb.AppendLine("{");

        GenerateMapEndpointsMethod(sb, interfaceInfo);
        GenerateRequestDtos(sb, interfaceInfo);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateFileHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void GenerateUsingDirectives(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using System.Text.Json;");

        if (interfaceInfo.Methods.Any(m => m.HasCancellationToken))
            sb.AppendLine("using System.Threading;");

        sb.AppendLine();
    }

    private static void GenerateMapEndpointsMethod(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        sb.Append("    internal static IEndpointRouteBuilder Map")
            .Append(interfaceInfo.Name)
            .AppendLine("Endpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");
        sb.Append("        var group = endpoints.MapGroup(\"/api/functions/")
            .Append(interfaceInfo.RoutePrefix)
            .AppendLine("\");");

        if (interfaceInfo.RequireAuthorization)
            sb.AppendLine("        group = group.RequireAuthorization();");

        sb.AppendLine();

        foreach (var method in interfaceInfo.Methods)
            GenerateEndpoint(sb, interfaceInfo.Name, interfaceInfo.RequireAuthorization, method);

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
    }

    private static void GenerateEndpoint(StringBuilder sb, string interfaceName, bool interfaceRequiresAuth, MethodInfo method)
    {
        var routeName = method.CustomRoute ?? method.Name;
        var hasParameters = method.Parameters.Count > 0;
        var httpMethod = method.HttpMethod.ToPascalCase();
        var isGet = string.Equals(method.HttpMethod, "GET", StringComparison.OrdinalIgnoreCase);
        var bindingAttribute = isGet ? "[AsParameters]" : "[FromBody]";

        sb.Append("        group.Map").Append(httpMethod).Append("(\"/").Append(routeName).AppendLine("\",");

        // Build lambda parameter list
        var lambdaParams = new List<string>();
        if (hasParameters)
            lambdaParams.Add($"{bindingAttribute} {method.Name}Request request");
        lambdaParams.Add($"{interfaceName} service");
        if (method.HasCancellationToken)
            lambdaParams.Add("CancellationToken cancellationToken");

        sb.Append("            async (")
            .Append(string.Join(", ", lambdaParams))
            .AppendLine(") =>");

        sb.AppendLine("            {");

        GenerateServiceCall(sb, method);
        GenerateResultReturn(sb, method.ReturnType);

        sb.AppendLine("            })");
        sb.Append("            .WithName(\"")
            .Append(interfaceName)
            .Append('_')
            .Append(method.Name)
            .Append("\")");

        if (method.RequireAuthorization && !interfaceRequiresAuth)
        {
            sb.AppendLine();
            sb.Append("            .RequireAuthorization()");
        }

        sb.AppendLine(";");
        sb.AppendLine();
    }

    private static void GenerateServiceCall(StringBuilder sb, MethodInfo method)
    {
        sb.Append("                ");

        if (!string.Equals(method.ReturnType, "void", StringComparison.Ordinal))
            sb.Append("var result = ");

        sb.Append("await service.").Append(method.Name).Append('(');

        var args = new List<string>();
        if (method.Parameters.Count > 0)
            args.AddRange(method.Parameters.Select(p => $"request.{p.Name.ToPascalCase()}"));
        if (method.HasCancellationToken)
            args.Add("cancellationToken");

        sb.Append(string.Join(", ", args));
        sb.AppendLine(");");
    }

    private static void GenerateResultReturn(StringBuilder sb, string returnType)
    {
        if (!string.Equals(returnType, "void", StringComparison.Ordinal))
            sb.AppendLine("                return Results.Ok(result);");
        else
            sb.AppendLine("                return Results.Ok();");
    }

    private static void GenerateRequestDtos(StringBuilder sb, InterfaceInfo interfaceInfo)
    {
        foreach (var method in interfaceInfo.Methods)
        {
            if (method.Parameters.Count > 0)
                GenerateRequestDto(sb, method);
        }
    }

    private static void GenerateRequestDto(StringBuilder sb, MethodInfo method)
    {
        sb.AppendLine();
        sb.Append("    private record ")
            .Append(method.Name)
            .Append("Request(");

        var properties = method.Parameters
            .Select(p => $"{p.Type} {p.Name.ToPascalCase()}");

        sb.Append(string.Join(", ", properties));
        sb.AppendLine(");");
    }
}
