using System.Text;
using BlazorServerFunctions.Generator.Models;

namespace BlazorServerFunctions.Generator.Generators;

internal static class ServerRegistrationGenerator
{
    public static string Generate(IReadOnlyCollection<InterfaceInfo> interfaces, string? targetNamespace)
    {
        if (interfaces.Count == 0)
            return string.Empty;

        var ns = !string.IsNullOrEmpty(targetNamespace) ? targetNamespace : interfaces.First().Namespace;
        var externalNamespaces = interfaces
            .Select(i => i.Namespace)
            .Where(n => !string.Equals(n, ns, StringComparison.Ordinal) && !string.IsNullOrEmpty(n))
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");

        foreach (var externalNs in externalNamespaces)
            sb.Append("using ").Append(externalNs).AppendLine(";");

        sb.AppendLine();
        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        sb.AppendLine("public static class ServerFunctionEndpointsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapServerFunctionEndpoints(");
        sb.AppendLine("        this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var interfaceInfo in interfaces)
        {
            sb.Append("        endpoints.Map")
                .Append(interfaceInfo.Name)
                .AppendLine("Endpoints();");
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
