//HintName: ServerFunctionEndpointsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;

namespace BlazorServerFunctions.Sample.Shared;

public static class ServerFunctionEndpointsRegistration
{
    public static IEndpointRouteBuilder MapServerFunctionEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapIWeatherServiceEndpoints();
        return endpoints;
    }
}
