//HintName: StockServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Threading.Tasks;

namespace MyApp.Services;

public class StockServiceClient : IStockService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/stock";

    public StockServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<Result<MyApp.Services.StockDto>> GetStockAsync(int id, CancellationToken cancellationToken = null)
    {
        var queryString = System.Web.HttpUtility.ParseQueryString(string.Empty);
        queryString["Id"] = id.ToString(System.Globalization.CultureInfo.InvariantCulture);
        queryString["CancellationToken"] = cancellationToken.ToString(System.Globalization.CultureInfo.InvariantCulture);
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/GetStockAsync?{queryString}");

        if (!response.IsSuccessStatusCode)
        {
            var __body = await response.Content.ReadAsStringAsync();
            var __err = new global::BlazorServerFunctions.Abstractions.ServerFunctionError
            {
                Status = (int)response.StatusCode,
            };
            if (!string.IsNullOrWhiteSpace(__body))
            {
                try
                {
                    using var __doc = JsonDocument.Parse(__body);
                    var __root = __doc.RootElement;
                    if (__root.TryGetProperty("status", out var __s) && __s.TryGetInt32(out var __sc))
                        __err.Status = __sc;
                    if (__root.TryGetProperty("title", out var __t))
                        __err.Title = __t.GetString();
                    if (__root.TryGetProperty("detail", out var __d))
                        __err.Detail = __d.GetString();
                    if (__root.TryGetProperty("type", out var __tp))
                        __err.Type = __tp.GetString();
                }
                catch (JsonException) { __err.Detail = __body; }
            }
            return new global::ResultMapper<MyApp.Services.StockDto>().WrapFailure(__err);
        }

        var __value = await response.Content.ReadFromJsonAsync<MyApp.Services.StockDto?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
        return new global::ResultMapper<MyApp.Services.StockDto>().WrapValue(__value);
    }

    public async Task<Result<MyApp.Services.StockDto>> ReserveStockAsync(string sku, CancellationToken cancellationToken = null)
    {
        var request = new
        {
            Sku = sku,
            CancellationToken = cancellationToken,
        };

        var response = await _httpClient.PostAsJsonAsync(
            $"{BaseRoute}/ReserveStockAsync",
            request);

        if (!response.IsSuccessStatusCode)
        {
            var __body = await response.Content.ReadAsStringAsync();
            var __err = new global::BlazorServerFunctions.Abstractions.ServerFunctionError
            {
                Status = (int)response.StatusCode,
            };
            if (!string.IsNullOrWhiteSpace(__body))
            {
                try
                {
                    using var __doc = JsonDocument.Parse(__body);
                    var __root = __doc.RootElement;
                    if (__root.TryGetProperty("status", out var __s) && __s.TryGetInt32(out var __sc))
                        __err.Status = __sc;
                    if (__root.TryGetProperty("title", out var __t))
                        __err.Title = __t.GetString();
                    if (__root.TryGetProperty("detail", out var __d))
                        __err.Detail = __d.GetString();
                    if (__root.TryGetProperty("type", out var __tp))
                        __err.Type = __tp.GetString();
                }
                catch (JsonException) { __err.Detail = __body; }
            }
            return new global::ResultMapper<MyApp.Services.StockDto>().WrapFailure(__err);
        }

        var __value = await response.Content.ReadFromJsonAsync<MyApp.Services.StockDto?>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
        return new global::ResultMapper<MyApp.Services.StockDto>().WrapValue(__value);
    }

}
