//HintName: IProductServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IProductServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIProductServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/products");

        group.MapGet("/GetProductAsync",
            async ([AsParameters] GetProductAsyncRequest request, IProductService service) =>
            {
                var result = await service.GetProductAsync(request.Id);
                var __mapper = new global::ResultMapper<MyApp.Services.ProductDto>();
                if (__mapper.IsSuccess(result))
                    return Results.Ok(__mapper.GetValue(result));
                var __error = __mapper.GetError(result);
                return Results.Problem(
                    __error.Detail,
                    statusCode: __error.Status,
                    title: __error.Title,
                    type: __error.Type);
            })
            .WithName("IProductService_GetProductAsync")
            .WithTags("ProductService")
            .Produces<MyApp.Services.ProductDto>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        group.MapDelete("/DeleteProductAsync",
            async ([AsParameters] DeleteProductAsyncRequest request, IProductService service) =>
            {
                await service.DeleteProductAsync(request.Id);
                return Results.Ok();
            })
            .WithName("IProductService_DeleteProductAsync")
            .WithTags("ProductService")
            .Produces(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetProductAsyncRequest(int Id);

    private record DeleteProductAsyncRequest(int Id);
}
