//HintName: IOrderServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IOrderServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIOrderServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/orders");

        group.MapGet("/GetOrderAsync",
            async ([AsParameters] GetOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.GetOrderAsync(request.Id);
                var __mapper = new global::ResultMapper<MyApp.Services.OrderDto>();
                if (__mapper.IsSuccess(result))
                    return Results.Ok(__mapper.GetValue(result));
                var __error = __mapper.GetError(result);
                return Results.Problem(
                    __error.Detail,
                    statusCode: __error.Status,
                    title: __error.Title,
                    type: __error.Type);
            })
            .WithName("IOrderService_GetOrderAsync")
            .WithTags("OrderService")
            .Produces<MyApp.Services.OrderDto>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        group.MapPost("/CreateOrderAsync",
            async ([FromBody] CreateOrderAsyncRequest request, IOrderService service) =>
            {
                var result = await service.CreateOrderAsync(request.Name);
                var __mapper = new global::ResultMapper<MyApp.Services.OrderDto>();
                if (__mapper.IsSuccess(result))
                    return Results.Ok(__mapper.GetValue(result));
                var __error = __mapper.GetError(result);
                return Results.Problem(
                    __error.Detail,
                    statusCode: __error.Status,
                    title: __error.Title,
                    type: __error.Type);
            })
            .WithName("IOrderService_CreateOrderAsync")
            .WithTags("OrderService")
            .Produces<MyApp.Services.OrderDto>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetOrderAsyncRequest(int Id);

    private record CreateOrderAsyncRequest(string Name);
}
