//HintName: IEventServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IEventServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIEventServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/events");

        group.MapGet("/StreamEventsAsync",
            ([AsParameters] StreamEventsAsyncRequest request, IEventService service) =>
            {
                return service.StreamEventsAsync(request.CancellationToken);
            })
            .WithName("IEventService_StreamEventsAsync")
            .WithTags("EventService");

        return endpoints;
    }

    private record StreamEventsAsyncRequest(CancellationToken CancellationToken);
}
