//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/users");

        group.MapGet("/GetUserAsync",
            async Task<Results<Ok<MyApp.Services.UserDto>, ProblemHttpResult>> ([AsParameters] GetUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.GetUserAsync(request.Id);
                var __mapper = new global::ResultMapper<MyApp.Services.UserDto, Error>();
                if (__mapper.IsSuccess(result))
                    return TypedResults.Ok(__mapper.GetValue(result));
                var __error = __mapper.GetError(result);
                return TypedResults.Problem(
                    __error.Detail,
                    statusCode: __error.Status,
                    title: __error.Title,
                    type: __error.Type);
            })
            .WithName("IUserService_GetUserAsync")
            .WithTags("UserService");

        group.MapDelete("/DeleteUserAsync",
            async Task<Results<Ok<MyApp.Services.UserDto>, ProblemHttpResult>> ([AsParameters] DeleteUserAsyncRequest request, IUserService service) =>
            {
                var result = await service.DeleteUserAsync(request.Id);
                var __mapper = new global::ResultMapper<MyApp.Services.UserDto, Error>();
                if (__mapper.IsSuccess(result))
                    return TypedResults.Ok(__mapper.GetValue(result));
                var __error = __mapper.GetError(result);
                return TypedResults.Problem(
                    __error.Detail,
                    statusCode: __error.Status,
                    title: __error.Title,
                    type: __error.Type);
            })
            .WithName("IUserService_DeleteUserAsync")
            .WithTags("UserService");

        return endpoints;
    }

    private record GetUserAsyncRequest(int Id);

    private record DeleteUserAsyncRequest(int Id);
}
