//HintName: IRestServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using System.Threading.Tasks;
using MyApp.Services;

namespace Tests;

internal static class IRestServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIRestServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/restservice");

        group.MapGet("/GetAsync",
            async Task<Results<Ok<string>, ProblemHttpResult>> ([AsParameters] GetAsyncRequest request, IRestService service) =>
            {
                var result = await service.GetAsync(request.Id);
                return TypedResults.Ok(result);
            })
            .WithName("IRestService_GetAsync")
            .WithTags("RestService");

        return endpoints;
    }

    private record GetAsyncRequest(int Id);
}
