//HintName: IGrpcServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class GrpcServiceCallAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract]
public sealed class GrpcServiceGrpcService
{
    private readonly IGrpcService _service;

    public GrpcServiceGrpcService(IGrpcService service) => _service = service;

    [OperationContract]
    public Task<string> CallAsync(GrpcServiceCallAsyncGrpcRequest request, CallContext context = default)
        => _service.CallAsync(request.Id);

}
