//HintName: IUserServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class UserServiceGetUserAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
    [ProtoMember(2)]
    public string Name { get; set; } = default!;
}

public sealed class UserServiceGrpcService : IUserServiceGrpcContract
{
    private readonly IUserService _service;

    public UserServiceGrpcService(IUserService service) => _service = service;

    public Task<string> GetUserAsync(UserServiceGetUserAsyncGrpcRequest request, CallContext context = default)
        => _service.GetUserAsync(request.Id, request.Name);

}
