//HintName: IUserServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class UserServiceGetUserAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract]
public sealed class UserServiceGrpcService
{
    private readonly IUserService _service;

    public UserServiceGrpcService(IUserService service) => _service = service;

    [OperationContract]
    public Task<string> GetUserAsync(UserServiceGetUserAsyncGrpcRequest request, CallContext context = default)
        => _service.GetUserAsync(request.Id);

}
