//HintName: IStreamServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class StreamServiceStreamNamesAsyncGrpcRequest
{
    [ProtoMember(1)]
    public string Prefix { get; set; } = default!;
}

[ServiceContract]
public sealed class StreamServiceGrpcService
{
    private readonly IStreamService _service;

    public StreamServiceGrpcService(IStreamService service) => _service = service;

    [OperationContract]
    public IAsyncEnumerable<string> StreamNamesAsync(StreamServiceStreamNamesAsyncGrpcRequest request, CallContext context = default)
        => _service.StreamNamesAsync(request.Prefix);

}
