//HintName: IUserServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class UserServiceCreateUserAsyncGrpcRequest
{
    [ProtoMember(1)]
    public MyApp.Services.CreateUserRequest Request { get; set; } = default!;
}

[ServiceContract]
public sealed class UserServiceGrpcService
{
    private readonly IUserService _service;

    public UserServiceGrpcService(IUserService service) => _service = service;

    [OperationContract]
    public Task<MyApp.Services.UserDto> CreateUserAsync(UserServiceCreateUserAsyncGrpcRequest request, CallContext context = default)
        => _service.CreateUserAsync(request.Request);

}
