//HintName: IPingServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

public sealed class PingServiceGrpcService : IPingServiceGrpcContract
{
    private readonly IPingService _service;

    public PingServiceGrpcService(IPingService service) => _service = service;

    public Task PingAsync(CallContext context = default)
        => _service.PingAsync();

}
