//HintName: IPingServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Threading.Tasks;

namespace MyApp.Services;

[ServiceContract]
public sealed class PingServiceGrpcService
{
    private readonly IPingService _service;

    public PingServiceGrpcService(IPingService service) => _service = service;

    [OperationContract]
    public Task PingAsync(CallContext context = default)
        => _service.PingAsync();

}
