//HintName: ICommandServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class CommandServiceDeleteAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

public sealed class CommandServiceGrpcService : ICommandServiceGrpcContract
{
    private readonly ICommandService _service;

    public CommandServiceGrpcService(ICommandService service) => _service = service;

    public Task DeleteAsync(CommandServiceDeleteAsyncGrpcRequest request, CallContext context = default)
        => _service.DeleteAsync(request.Id);

}
