//HintName: ISecretServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using System.ServiceModel;
using System.Threading.Tasks;

namespace MyApp.Services;

public sealed class SecretServiceGrpcService : ISecretServiceGrpcContract
{
    private readonly ISecretService _service;

    public SecretServiceGrpcService(ISecretService service) => _service = service;

    [global::Microsoft.AspNetCore.Authorization.Authorize(Roles = "Admin,Manager")]
    public Task<string> GetSecretAsync(CallContext context = default)
        => _service.GetSecretAsync();

}
