//HintName: IRestServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp.Services;

namespace Tests;

internal static class IRestServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIRestServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/restservice");

        group.MapGet("/GetAsync",
            async ([AsParameters] GetAsyncRequest request, IRestService service) =>
            {
                var result = await service.GetAsync(request.Id);
                return Results.Ok(result);
            })
            .WithName("IRestService_GetAsync")
            .WithTags("RestService")
            .Produces<string>(StatusCodes.Status200OK)
            .ProducesProblem(StatusCodes.Status500InternalServerError);

        return endpoints;
    }

    private record GetAsyncRequest(int Id);
}
