//HintName: ICommandServiceGrpcService.g.cs
// <auto-generated />
#nullable enable

using ProtoBuf;
using ProtoBuf.Grpc;
using ProtoBuf.Grpc.Configuration;
using System.Threading.Tasks;

namespace MyApp.Services;

[ProtoContract]
public sealed class CommandServiceDeleteAsyncGrpcRequest
{
    [ProtoMember(1)]
    public int Id { get; set; }
}

[ServiceContract]
public sealed class CommandServiceGrpcService
{
    private readonly ICommandService _service;

    public CommandServiceGrpcService(ICommandService service) => _service = service;

    [OperationContract]
    public Task DeleteAsync(CommandServiceDeleteAsyncGrpcRequest request, CallContext context = default)
        => _service.DeleteAsync(request.Id);

}
