//HintName: ServerFunctionEndpointsRegistration.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;

namespace BlazorServerFunctions.Sample.Shared.Generated;

internal static class ServerFunctionEndpointsRegistration
{
    internal static IEndpointRouteBuilder MapServerFunctionEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        endpoints.MapIWeatherServiceEndpoints();
        return endpoints;
    }
}
