//HintName: IWeatherServiceClient.g.cs
// <auto-generated />
#nullable enable

using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace BlazorServerFunctions.Sample.Shared.Generated;

public class WeatherServiceClient : IWeatherService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/weatherservice";

    public WeatherServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<BlazorServerFunctions.Sample.Shared.WeatherForecastDto[]> GetWeatherForecastsAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/GetWeatherForecastsAsync",
            null);

        response.EnsureSuccessStatusCode();

        return await response.Content.ReadFromJsonAsync<BlazorServerFunctions.Sample.Shared.WeatherForecastDto[]>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
