//HintName: IWeatherServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace BlazorServerFunctions.Sample.Shared.Generated;

internal static class IWeatherServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIWeatherServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/weatherservice");

        group.MapPost("/GetWeatherForecastsAsync",
            async (IWeatherService service) =>
            {
                var result = await service.GetWeatherForecastsAsync();
                return Results.Ok(result);
            })
            .WithName("IWeatherService_GetWeatherForecastsAsync");

        return endpoints;
    }
}
