//HintName: CommandServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp;

public class CommandServiceClient : ICommandService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/functions/commandservice";

    public CommandServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task ExecuteAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/ExecuteAsync",
            null);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

    }

}
