//HintName: OrderServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp;

public class OrderServiceClient : IOrderService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/v3/orderservice";

    public OrderServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task CreateOrderAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/CreateOrderAsync",
            null);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

    }

}
