//HintName: AdminServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp;

public class AdminServiceClient : IAdminService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/v1/admin/adminservice";

    public AdminServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> GetStatsAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/get-stats-async");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<string>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

}
