//HintName: OrderServiceClient.g.cs
// <auto-generated />
#nullable enable

using System;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading.Tasks;

namespace MyApp;

public class OrderServiceClient : IOrderService
{
    private readonly HttpClient _httpClient;
    private const string BaseRoute = "/api/v2/orderservice";

    public OrderServiceClient(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public async Task<string> GetOrderDetailsAsync()
    {
        var response = await _httpClient.GetAsync(
            $"{BaseRoute}/get-order-details-async");

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

        return await response.Content.ReadFromJsonAsync<string>()
            ?? throw new InvalidOperationException("Response deserialization returned null");
    }

    public async Task CreateNewOrderAsync()
    {
        var response = await _httpClient.PostAsync(
            $"{BaseRoute}/create-new-order-async",
            null);

        if (!response.IsSuccessStatusCode)
        {
            var errorBody = await response.Content.ReadAsStringAsync();
            throw new HttpRequestException(errorBody, null, response.StatusCode);
        }

    }

}
