//HintName: IUserServiceServerExtensions.g.cs
// <auto-generated />
#nullable enable

using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
using MyApp;

namespace Tests;

internal static class IUserServiceServerExtensions
{
    internal static IEndpointRouteBuilder MapIUserServiceEndpoints(
        this IEndpointRouteBuilder endpoints)
    {
        var group = endpoints.MapGroup("/api/functions/userservice");

        group.MapGet("/get-user-by-id-async",
            async (IUserService service) =>
            {
                var result = await service.GetUserByIdAsync();
                return Results.Ok(result);
            })
            .WithName("IUserService_GetUserByIdAsync");

        return endpoints;
    }
}
